
;;; catppuccin-theme.el --- Generated by Book of Colours

(deftheme catppuccin "catppuccin")

(custom-theme-set-faces
 'catppuccin

 ;; common
 '(default ((t (:foreground "#CCD5F3" :background "#1E1E2E"))))
 '(cursor ((t (:foreground "#1E1E2E" :background "#F4DFDB"))))
 '(region ((t (:foreground "#F4DFDB" :background "#1E1E2E"))))
 '(hl-line ((t (:background "#181825"))))
 '(minibuffer-prompt ((t (:foreground "#9399B2"))))
 '(link ((t (:foreground "#B4BEFD" :underline t))))
 '(warning ((t (:foreground "#F8E1AF"))))
 '(error ((t (:foreground "#F28BA8"))))
 '(success ((t (:foreground "#A6E2A1"))))
 '(bold ((t (:foreground "#F8E1AF" :weight bold))))
 '(isearch ((t (:foreground "#F4DFDB" :background "#1E1E2E"))))
 '(lazy-highlight ((t (:foreground "#CCD5F3" :background "#1E1E2E"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#F8E1AF" :background "#1E1E2E" :weight bold))))
 '(tooltip ((t (:foreground "#89B4F9" :background "#1E1E2E" :weight bold))))
 '(fringe ((t (:background "#1E1E2E"))))
 '(vertical-border ((t (:foreground "#6C7086"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#CCD5F3"))))
 '(header-line ((t (:foreground "#9399B2" :background "#1E1E2E"))))
 '(header-line-highlight ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))
 '(highlight ((t (:foreground "#F9B387" :background "#1E1E2E"))))
 '(button ((t (:foreground "#CAA6F6" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#9399B2" :background "#1E1E2E" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#CCD5F3" :background "#1E1E2E" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#CCD5F3"))))
 '(font-lock-type-face ((t (:foreground "#94E1D4"))))
 '(font-lock-preprocessor-face ((t (:foreground "#F4C1E6"))))
 '(font-lock-operator-face ((t (:foreground "#89DBEA"))))
 '(font-lock-string-face ((t (:foreground "#A6E2A1"))))
 '(font-lock-variable-name-face ((t (:foreground "#CCD5F3"))))
 '(font-lock-constant-face ((t (:foreground "#F9B387"))))
 '(font-lock-keyword-face ((t (:foreground "#CAA6F6"))))
 '(font-lock-warning-face ((t (:foreground "#F8E1AF"))))
 '(font-lock-function-name-face ((t (:foreground "#89B4F9"))))
 '(font-lock-negation-char-face ((t (:foreground "#89DBEA"))))
 '(font-lock-variable-use-face ((t (:foreground "#CCD5F3"))))
 '(font-lock-property-use-face ((t (:foreground "#CCD5F3"))))
 '(font-lock-number-face ((t (:foreground "#F9B387"))))
 '(font-lock-bracket-face ((t (:foreground "#9399B2"))))
 '(font-lock-delimiter-face ((t (:foreground "#7F849C"))))
 '(font-lock-escape-face ((t (:foreground "#F8E1AF"))))
 '(show-paren-match ((t (:foreground "#CCD5F3"))))
 '(show-paren-mismatch-face ((t (:foreground "#F28BA8" :background "#1E1E2E"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#9399B2" :background "#1E1E2E" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#A6E2A1"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#89B4F9"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#94E1D4"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#F9B387"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#CCD5F3"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#F1CCCC"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#89B4F9" :background "#181825" :overline "#9399B2"))))
 '(org-level-2 ((t (:foreground "#F4DFDB" :background "#181825" :overline "#9399B2"))))
 '(org-level-3 ((t (:foreground "#F4DFDB" :background "#181825" :overline "#9399B2"))))
 '(org-level-4 ((t (:foreground "#89B4F9" :background "#181825" :overline "#9399B2"))))
 '(org-level-5 ((t (:foreground "#89B4F9" :background "#181825" :overline "#9399B2"))))
 '(org-level-6 ((t (:foreground "#89B4F9" :background "#181825" :overline "#9399B2"))))
 '(org-level-7 ((t (:foreground "#89B4F9" :background "#181825" :overline "#9399B2"))))
 '(org-tag ((t (:foreground "#CCD5F3"))))
 '(org-headline-done ((t (:foreground "#CAA6F6" :background "#1E1E2E"))))
 '(org-done ((t (:foreground "#CCD5F3"))))
 '(org-todo ((t (:foreground "#F8E1AF"))))
 '(org-checkbox ((t (:foreground "#F9B387" :background "#B4BEFD"))))
 '(org-link ((t (:foreground "#B4BEFD" :background "#1E1E2E" :underline nil))))
 '(org-verbatim ((t (:foreground "#F8E1AF"))))
 '(org-code ((t (:foreground "#F8E1AF"))))
 '(org-table ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))
 '(org-date ((t (:foreground "#F4DFDB" :underline t))))
 '(org-archived ((t (:foreground "#9399B2" :background "#1E1E2E"))))
 '(org-list-dt ((t (:foreground "#CCD5F3"))))
 '(org-drawer ((t (:foreground "#F4C1E6"))))
 '(org-special-keyword ((t (:foreground "#7F849C"))))
 '(org-property-value ((t (:foreground "#CCD5F3" :background "#1E1E2E"))))
 '(org-block ((t (:background "#181825" :extend t))))
 '(org-block-begin-line ((t (:foreground "#9399B2" :background "#1E1E2E" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#7F849C"))))
 '(org-superstar-header-bullet ((t (:foreground "#F9B387" :background "#1E1E2E" :overline t))))
 '(org-superstar-item ((t (:foreground "#F8E1AF"))))
 '(org-superstar-ordered-item ((t (:foreground "#F1CCCC"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#F8E1AF" :height 220 :underline "#89B4F9"))))
 '(markdown-header-face-2 ((t (:foreground "#F8E1AF" :height 180 :underline "#89B4F9"))))
 '(markdown-header-face-3 ((t (:foreground "#F8E1AF" :underline "#CCD5F3"))))
 '(markdown-header-face-4 ((t (:foreground "#F8E1AF"))))
 '(markdown-header-face-5 ((t (:foreground "#F8E1AF"))))
 '(markdown-header-face-6 ((t (:foreground "#F8E1AF"))))
 '(markdown-list-face ((t (:foreground "#F8E1AF"))))
 '(markdown-inline-code-face ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))
 '(markdown-language-keyword-face ((t (:foreground "#CCD5F3"))))
 '(markdown-pre-face ((t (:foreground "#F8E1AF"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#9399B2"))))
 '(markdown-header-delimiter-face ((t (:foreground "#9399B2"))))
 '(markdown-bold-face ((t (:foreground "#F8E1AF" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#F8E1AF" :slant italic))))
 '(markdown-link-face ((t (:foreground "#F8E1AF"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#89B4F9"))))
 '(compilation-warning ((t (:foreground "#89B4F9"))))
 '(compilation-error ((t (:foreground "#F28BA8"))))
 '(compilation-line-number ((t (:foreground "#F8E1AF" :underline t))))
 '(compilation-column-number ((t (:foreground "#F8E1AF" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#F28BA8"))))
 '(flycheck-fringe-warning ((t (:foreground "#89B4F9"))))
 '(flycheck-fringe-info ((t (:foreground "#89B4F9"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#1E1E2E"))))
 '(lsp-face-highlight-textual ((t (:background "#1E1E2E"))))
 '(lsp-face-highlight-write ((t (:background "#1E1E2E"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#1E1E2E"))))
 '(eglot-inlay-hint-face ((t (:foreground "#F8E1AF" :background "#1E1E2E" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#F8E1AF"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#CCD5F3" :background "#1E1E2E"))))
 '(company-preview-common ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))
 '(company-preview-search ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))
 '(company-tooltip-common ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))
 '(company-tooltip-common-selection ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))
 '(company-tooltip-annotation ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))
 '(company-tooltip-search-selection ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))
 '(company-tooltip-mouse ((t (:foreground "#F8E1AF" :background "#1E1E2E"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#CCD5F3" :background "#1E1E2E"))))
 '(magit-branch-current ((t (:foreground "#89B4F9" :box 1))))
 '(magit-branch-remote ((t (:foreground "#89B4F9" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#CAA6F6"))))
 '(rg-line-number-face ((t (:foreground "#F8E1AF"))))

 ;; line numbers
 '(line-number ((t (:foreground "#9399B2" :background "#1E1E2E"))))
 '(line-number-current-line ((t (:foreground "#9399B2" :background "#1E1E2E"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#585B70"))))
 '(doom-modeline-bar ((t (:background "#1E1E2E"))))
 '(doom-modeline-bar-inactive ((t (:background "#1E1E2E"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#F1CCCC" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#CAA6F6"))))
 '(doom-modeline-project-dir ((t (:foreground "#CCD5F3"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#CCD5F3"))))
 '(doom-modeline-urgent ((t (:foreground "#CAA6F6"))))
 '(doom-modeline-info ((t (:foreground "#CCD5F3"))))
 '(doom-modeline-warning ((t (:foreground "#CAA6F6"))))
 '(doom-modeline-error ((t (:foreground "#F28BA8"))))
 '(doom-modeline-inactive-bar ((t (:background "#1E1E2E"))))
 '(mode-line ((t (:foreground "#181825" :background "#1E1E2E"))))
 '(mode-line-inactive ((t (:background "#1E1E2E"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#181825"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#181825"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#7F849C" :background "#1E1E2E"))))
 '(tab-bar-tab ((t (:foreground "#F4DFDB" :background "#1E1E2E" :box (:line-width 2 :color "#1E1E2E")))))
 '(tab-bar-tab-inactive ((t (:foreground "#7F849C" :background "#1E1E2E"))))

 ;; misc
 '(secondary-selection ((t (:background "#181825"))))
 '(shadow ((t (:foreground "#9399B2")))))

(provide-theme 'catppuccin)
