
;;; catppuccin-latte-theme.el --- Generated by Book of Colours

(deftheme catppuccin-latte "catppuccin-latte")

(custom-theme-set-faces
 'catppuccin-latte

 ;; common
 '(default ((t (:foreground "#4C4F69" :background "#EEF0F4"))))
 '(cursor ((t (:foreground "#EEF0F4" :background "#222222"))))
 '(region ((t (:foreground "#DB8A78" :background "#EEF0F4"))))
 '(hl-line ((t (:background "#E8EAF0"))))
 '(minibuffer-prompt ((t (:foreground "#7C7F93"))))
 '(link ((t (:foreground "#1E66F4" :underline t))))
 '(warning ((t (:foreground "#E54553"))))
 '(error ((t (:foreground "#D10F39"))))
 '(success ((t (:foreground "#429434"))))
 '(bold ((t (:foreground "#8839EE" :weight bold))))
 '(isearch ((t (:foreground "#DB8A78" :background "#EEF0F4"))))
 '(lazy-highlight ((t (:foreground "#4C4F69" :background "#EEF0F4"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#E54553" :background "#EEF0F4" :weight bold))))
 '(tooltip ((t (:foreground "#6C6F85" :background "#EEF0F4" :weight bold))))
 '(fringe ((t (:background "#EEF0F4"))))
 '(vertical-border ((t (:foreground "#9CA0B0"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#4C4F69"))))
 '(header-line ((t (:foreground "#7C7F93" :background "#EEF0F4"))))
 '(header-line-highlight ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(highlight ((t (:foreground "#4C4F69" :background "#EEF0F4"))))
 '(button ((t (:foreground "#8839EE" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#7C7F93" :background "#EEF0F4" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#4C4F69" :background "#EEF0F4" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#4C4F69"))))
 '(font-lock-type-face ((t (:foreground "#4C4F69"))))
 '(font-lock-preprocessor-face ((t (:foreground "#8839EE"))))
 '(font-lock-operator-face ((t (:foreground "#04A5E4"))))
 '(font-lock-string-face ((t (:foreground "#429434"))))
 '(font-lock-variable-name-face ((t (:foreground "#E54553"))))
 '(font-lock-constant-face ((t (:foreground "#FD640B"))))
 '(font-lock-keyword-face ((t (:foreground "#8839EE"))))
 '(font-lock-warning-face ((t (:foreground "#E54553"))))
 '(font-lock-function-name-face ((t (:foreground "#1E66F4"))))
 '(font-lock-negation-char-face ((t (:foreground "#04A5E4"))))
 '(font-lock-variable-use-face ((t (:foreground "#4C4F69"))))
 '(font-lock-property-use-face ((t (:foreground "#4C4F69"))))
 '(font-lock-number-face ((t (:foreground "#FD640B"))))
 '(font-lock-bracket-face ((t (:foreground "#7C7F93"))))
 '(font-lock-delimiter-face ((t (:foreground "#9CA0B0"))))
 '(font-lock-escape-face ((t (:foreground "#8839EE"))))
 '(show-paren-match ((t (:foreground "#4C4F69"))))
 '(show-paren-mismatch-face ((t (:foreground "#D10F39" :background "#EEF0F4"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#7C7F93" :background "#EEF0F4" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#429434"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#1E66F4"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#4C4F69"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#FD640B"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#4C4F69"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#E54553"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#6C6F85" :background "#E8EAF0" :overline "#7C7F93"))))
 '(org-level-2 ((t (:foreground "#1E66F4" :background "#E8EAF0" :overline "#7C7F93"))))
 '(org-level-3 ((t (:foreground "#1E66F4" :background "#E8EAF0" :overline "#7C7F93"))))
 '(org-level-4 ((t (:foreground "#1E66F4" :background "#E8EAF0" :overline "#7C7F93"))))
 '(org-level-5 ((t (:foreground "#1E66F4" :background "#E8EAF0" :overline "#7C7F93"))))
 '(org-level-6 ((t (:foreground "#1E66F4" :background "#E8EAF0" :overline "#7C7F93"))))
 '(org-level-7 ((t (:foreground "#1E66F4" :background "#E8EAF0" :overline "#7C7F93"))))
 '(org-tag ((t (:foreground "#E54553"))))
 '(org-headline-done ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(org-done ((t (:foreground "#4C4F69"))))
 '(org-todo ((t (:foreground "#E54553"))))
 '(org-checkbox ((t (:foreground "#4C4F69" :background "#EEF0F4"))))
 '(org-link ((t (:foreground "#1E66F4" :background "#EEF0F4" :underline nil))))
 '(org-verbatim ((t (:foreground "#8839EE"))))
 '(org-code ((t (:foreground "#8839EE"))))
 '(org-table ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(org-date ((t (:foreground "#1E66F4" :underline t))))
 '(org-archived ((t (:foreground "#7C7F93" :background "#EEF0F4"))))
 '(org-list-dt ((t (:foreground "#4C4F69"))))
 '(org-drawer ((t (:foreground "#8839EE"))))
 '(org-special-keyword ((t (:foreground "#9CA0B0"))))
 '(org-property-value ((t (:foreground "#4C4F69" :background "#EEF0F4"))))
 '(org-block ((t (:background "#E8EAF0" :extend t))))
 '(org-block-begin-line ((t (:foreground "#7C7F93" :background "#EEF0F4" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#9CA0B0"))))
 '(org-superstar-header-bullet ((t (:foreground "#4C4F69" :background "#EEF0F4" :overline t))))
 '(org-superstar-item ((t (:foreground "#E54553"))))
 '(org-superstar-ordered-item ((t (:foreground "#E54553"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#8839EE" :height 220 :underline "#6C6F85"))))
 '(markdown-header-face-2 ((t (:foreground "#8839EE" :height 180 :underline "#6C6F85"))))
 '(markdown-header-face-3 ((t (:foreground "#8839EE" :underline "#4C4F69"))))
 '(markdown-header-face-4 ((t (:foreground "#8839EE"))))
 '(markdown-header-face-5 ((t (:foreground "#8839EE"))))
 '(markdown-header-face-6 ((t (:foreground "#8839EE"))))
 '(markdown-list-face ((t (:foreground "#E54553"))))
 '(markdown-inline-code-face ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(markdown-language-keyword-face ((t (:foreground "#E54553"))))
 '(markdown-pre-face ((t (:foreground "#8839EE"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#7C7F93"))))
 '(markdown-header-delimiter-face ((t (:foreground "#7C7F93"))))
 '(markdown-bold-face ((t (:foreground "#8839EE" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#8839EE" :slant italic))))
 '(markdown-link-face ((t (:foreground "#8839EE"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#6C6F85"))))
 '(compilation-warning ((t (:foreground "#6C6F85"))))
 '(compilation-error ((t (:foreground "#D10F39"))))
 '(compilation-line-number ((t (:foreground "#8839EE" :underline t))))
 '(compilation-column-number ((t (:foreground "#8839EE" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#D10F39"))))
 '(flycheck-fringe-warning ((t (:foreground "#6C6F85"))))
 '(flycheck-fringe-info ((t (:foreground "#6C6F85"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#EEF0F4"))))
 '(lsp-face-highlight-textual ((t (:background "#EEF0F4"))))
 '(lsp-face-highlight-write ((t (:background "#EEF0F4"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#EEF0F4"))))
 '(eglot-inlay-hint-face ((t (:foreground "#8839EE" :background "#EEF0F4" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#8839EE"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#4C4F69" :background "#EEF0F4"))))
 '(company-preview-common ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(company-preview-search ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(company-tooltip-common ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(company-tooltip-common-selection ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(company-tooltip-annotation ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(company-tooltip-search-selection ((t (:foreground "#8839EE" :background "#EEF0F4"))))
 '(company-tooltip-mouse ((t (:foreground "#8839EE" :background "#EEF0F4"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#4C4F69" :background "#EEF0F4"))))
 '(magit-branch-current ((t (:foreground "#6C6F85" :box 1))))
 '(magit-branch-remote ((t (:foreground "#6C6F85" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#8839EE"))))
 '(rg-line-number-face ((t (:foreground "#8839EE"))))

 ;; line numbers
 '(line-number ((t (:foreground "#7C7F93" :background "#EEF0F4"))))
 '(line-number-current-line ((t (:foreground "#7C7F93" :background "#EEF0F4"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#8C8FA1"))))
 '(doom-modeline-bar ((t (:background "#EEF0F4"))))
 '(doom-modeline-bar-inactive ((t (:background "#EEF0F4"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#E54553" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#8839EE"))))
 '(doom-modeline-project-dir ((t (:foreground "#4C4F69"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#4C4F69"))))
 '(doom-modeline-urgent ((t (:foreground "#8839EE"))))
 '(doom-modeline-info ((t (:foreground "#4C4F69"))))
 '(doom-modeline-warning ((t (:foreground "#8839EE"))))
 '(doom-modeline-error ((t (:foreground "#D10F39"))))
 '(doom-modeline-inactive-bar ((t (:background "#EEF0F4"))))
 '(mode-line ((t (:foreground "#E5E8EE" :background "#EEF0F4"))))
 '(mode-line-inactive ((t (:background "#EEF0F4"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#E5E8EE"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#E5E8EE"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#9CA0B0" :background "#EEF0F4"))))
 '(tab-bar-tab ((t (:foreground "#1E66F4" :background "#EEF0F4" :box (:line-width 2 :color "#EEF0F4")))))
 '(tab-bar-tab-inactive ((t (:foreground "#9CA0B0" :background "#EEF0F4"))))

 ;; misc
 '(secondary-selection ((t (:background "#E8EAF0"))))
 '(shadow ((t (:foreground "#7C7F93")))))

(provide-theme 'catppuccin-latte)
