
;;; ethereal-theme.el --- Generated by Book of Colours

(deftheme ethereal "ethereal")

(custom-theme-set-faces
 'ethereal

 ;; common
 '(default ((t (:foreground "#8E93DD" :background "#060B1E"))))
 '(cursor ((t (:foreground "#060B1E" :background "#FFCDAD"))))
 '(region ((t (:foreground "#FFCDAD" :background "#060B1E"))))
 '(hl-line ((t (:background "#161D30"))))
 '(minibuffer-prompt ((t (:foreground "#6D7DB6"))))
 '(link ((t (:foreground "#A3BFD0" :underline t))))
 '(warning ((t (:foreground "#E8BB4F"))))
 '(error ((t (:foreground "#EC5B5A"))))
 '(success ((t (:foreground "#B4F8F7"))))
 '(bold ((t (:foreground "#E8BB4F" :weight bold))))
 '(isearch ((t (:foreground "#FFCDAD" :background "#060B1E"))))
 '(lazy-highlight ((t (:foreground "#92A593" :background "#060B1E"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#E8BB4F" :background "#060B1E" :weight bold))))
 '(tooltip ((t (:foreground "#E8BB4F" :background "#060B1E" :weight bold))))
 '(fringe ((t (:background "#060B1E"))))
 '(vertical-border ((t (:foreground "#401F2D"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#7D82D8"))))
 '(header-line ((t (:foreground "#6D7DB6" :background "#060B1E"))))
 '(header-line-highlight ((t (:foreground "#E8BB4F" :background "#060B1E"))))
 '(highlight ((t (:foreground "#92A593" :background "#060B1E"))))
 '(button ((t (:foreground "#C79DC0" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#6D7DB6" :background "#060B1E" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#8E93DD" :background "#060B1E" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#92A593"))))
 '(font-lock-type-face ((t (:foreground "#E8BB4F"))))
 '(font-lock-preprocessor-face ((t (:foreground "#C79DC0"))))
 '(font-lock-operator-face ((t (:foreground "#A3BFD0"))))
 '(font-lock-string-face ((t (:foreground "#92A593"))))
 '(font-lock-variable-name-face ((t (:foreground "#C3CEC3"))))
 '(font-lock-constant-face ((t (:foreground "#F9AAA9"))))
 '(font-lock-keyword-face ((t (:foreground "#C79DC0"))))
 '(font-lock-warning-face ((t (:foreground "#E8BB4F"))))
 '(font-lock-function-name-face ((t (:foreground "#8E93DD"))))
 '(font-lock-negation-char-face ((t (:foreground "#A3BFD0"))))
 '(font-lock-variable-use-face ((t (:foreground "#7D82D8"))))
 '(font-lock-property-use-face ((t (:foreground "#8E93DD"))))
 '(font-lock-number-face ((t (:foreground "#F9AAA9"))))
 '(font-lock-bracket-face ((t (:foreground "#F89957"))))
 '(font-lock-delimiter-face ((t (:foreground "#6D7DB6"))))
 '(font-lock-escape-face ((t (:foreground "#E8BB4F"))))
 '(show-paren-match ((t (:foreground "#FFCDAD"))))
 '(show-paren-mismatch-face ((t (:foreground "#EC5B5A" :background "#060B1E"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#6D7DB6" :background "#060B1E" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#92A593"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#8E93DD"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#E8BB4F"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#F9AAA9"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#7D82D8"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#C3CEC3"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#E8BB4F" :background "#161D30" :overline "#6D7DB6"))))
 '(org-level-2 ((t (:foreground "#F6DB9C" :background "#161D30" :overline "#6D7DB6"))))
 '(org-level-3 ((t (:foreground "#F6DB9C" :background "#161D30" :overline "#6D7DB6"))))
 '(org-level-4 ((t (:foreground "#7D82D8" :background "#161D30" :overline "#6D7DB6"))))
 '(org-level-5 ((t (:foreground "#7D82D8" :background "#161D30" :overline "#6D7DB6"))))
 '(org-level-6 ((t (:foreground "#7D82D8" :background "#161D30" :overline "#6D7DB6"))))
 '(org-level-7 ((t (:foreground "#7D82D8" :background "#161D30" :overline "#6D7DB6"))))
 '(org-tag ((t (:foreground "#C3CEC3"))))
 '(org-headline-done ((t (:foreground "#C79DC0" :background "#060B1E"))))
 '(org-done ((t (:foreground "#8E93DD"))))
 '(org-todo ((t (:foreground "#E8BB4F"))))
 '(org-checkbox ((t (:foreground "#92A593" :background "#060B1E"))))
 '(org-link ((t (:foreground "#A3BFD0" :background "#060B1E" :underline nil))))
 '(org-verbatim ((t (:foreground "#E8BB4F"))))
 '(org-code ((t (:foreground "#E8BB4F"))))
 '(org-table ((t (:foreground "#E8BB4F" :background "#060B1E"))))
 '(org-date ((t (:foreground "#F6DB9C" :underline t))))
 '(org-archived ((t (:foreground "#6D7DB6" :background "#060B1E"))))
 '(org-list-dt ((t (:foreground "#92A593"))))
 '(org-drawer ((t (:foreground "#C79DC0"))))
 '(org-special-keyword ((t (:foreground "#6D7DB6"))))
 '(org-property-value ((t (:foreground "#7D82D8" :background "#060B1E"))))
 '(org-block ((t (:background "#161D30" :extend t))))
 '(org-block-begin-line ((t (:foreground "#6D7DB6" :background "#060B1E" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#6D7DB6"))))
 '(org-superstar-header-bullet ((t (:foreground "#92A593" :background "#060B1E" :overline t))))
 '(org-superstar-item ((t (:foreground "#E8BB4F"))))
 '(org-superstar-ordered-item ((t (:foreground "#C3CEC3"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#E8BB4F" :height 220 :underline "#E8BB4F"))))
 '(markdown-header-face-2 ((t (:foreground "#E8BB4F" :height 180 :underline "#E8BB4F"))))
 '(markdown-header-face-3 ((t (:foreground "#E8BB4F" :underline "#8E93DD"))))
 '(markdown-header-face-4 ((t (:foreground "#E8BB4F"))))
 '(markdown-header-face-5 ((t (:foreground "#E8BB4F"))))
 '(markdown-header-face-6 ((t (:foreground "#E8BB4F"))))
 '(markdown-list-face ((t (:foreground "#E8BB4F"))))
 '(markdown-inline-code-face ((t (:foreground "#E8BB4F" :background "#060B1E"))))
 '(markdown-language-keyword-face ((t (:foreground "#C3CEC3"))))
 '(markdown-pre-face ((t (:foreground "#E8BB4F"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#6D7DB6"))))
 '(markdown-header-delimiter-face ((t (:foreground "#F89957"))))
 '(markdown-bold-face ((t (:foreground "#E8BB4F" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#E8BB4F" :slant italic))))
 '(markdown-link-face ((t (:foreground "#E8BB4F"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#E8BB4F"))))
 '(compilation-warning ((t (:foreground "#E8BB4F"))))
 '(compilation-error ((t (:foreground "#EC5B5A"))))
 '(compilation-line-number ((t (:foreground "#E8BB4F" :underline t))))
 '(compilation-column-number ((t (:foreground "#E8BB4F" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#EC5B5A"))))
 '(flycheck-fringe-warning ((t (:foreground "#E8BB4F"))))
 '(flycheck-fringe-info ((t (:foreground "#E8BB4F"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#060B1E"))))
 '(lsp-face-highlight-textual ((t (:background "#060B1E"))))
 '(lsp-face-highlight-write ((t (:background "#060B1E"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#060B1E"))))
 '(eglot-inlay-hint-face ((t (:foreground "#E8BB4F" :background "#060B1E" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#E8BB4F"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#7D82D8" :background "#060B1E"))))
 '(company-preview-common ((t (:foreground "#E8BB4F" :background "#060B1E"))))
 '(company-preview-search ((t (:foreground "#E8BB4F" :background "#060B1E"))))
 '(company-tooltip-common ((t (:foreground "#E8BB4F" :background "#060B1E"))))
 '(company-tooltip-common-selection ((t (:foreground "#E8BB4F" :background "#060B1E"))))
 '(company-tooltip-annotation ((t (:foreground "#E8BB4F" :background "#060B1E"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#E8BB4F" :background "#060B1E"))))
 '(company-tooltip-search-selection ((t (:foreground "#E8BB4F" :background "#060B1E"))))
 '(company-tooltip-mouse ((t (:foreground "#E8BB4F" :background "#060B1E"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#8E93DD" :background "#060B1E"))))
 '(magit-branch-current ((t (:foreground "#E8BB4F" :box 1))))
 '(magit-branch-remote ((t (:foreground "#E8BB4F" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#C79DC0"))))
 '(rg-line-number-face ((t (:foreground "#E8BB4F"))))

 ;; line numbers
 '(line-number ((t (:foreground "#6D7DB6" :background "#060B1E"))))
 '(line-number-current-line ((t (:foreground "#6D7DB6" :background "#060B1E"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#586698"))))
 '(doom-modeline-bar ((t (:background "#060B1E"))))
 '(doom-modeline-bar-inactive ((t (:background "#060B1E"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#C3CEC3" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#C79DC0"))))
 '(doom-modeline-project-dir ((t (:foreground "#7D82D8"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#8E93DD"))))
 '(doom-modeline-urgent ((t (:foreground "#C79DC0"))))
 '(doom-modeline-info ((t (:foreground "#7D82D8"))))
 '(doom-modeline-warning ((t (:foreground "#C79DC0"))))
 '(doom-modeline-error ((t (:foreground "#EC5B5A"))))
 '(doom-modeline-inactive-bar ((t (:background "#060B1E"))))
 '(mode-line ((t (:foreground "#161D30" :background "#060B1E"))))
 '(mode-line-inactive ((t (:background "#060B1E"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#161D30"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#161D30"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#6D7DB6" :background "#060B1E"))))
 '(tab-bar-tab ((t (:foreground "#F6DB9C" :background "#060B1E" :box (:line-width 2 :color "#060B1E")))))
 '(tab-bar-tab-inactive ((t (:foreground "#6D7DB6" :background "#060B1E"))))

 ;; misc
 '(secondary-selection ((t (:background "#161D30"))))
 '(shadow ((t (:foreground "#6D7DB6")))))

(provide-theme 'ethereal)
