
;;; event-horizon-theme.el --- Generated by Book of Colours

(deftheme event-horizon "event-horizon")

(custom-theme-set-faces
 'event-horizon

 ;; common
 '(default ((t (:foreground "#F9D9D0" :background "#1C1E26"))))
 '(cursor ((t (:foreground "#1C1E26" :background "#F9D9D0"))))
 '(region ((t (:foreground "#26BBD8" :background "#1C1E26"))))
 '(hl-line ((t (:background "#1D2E38"))))
 '(minibuffer-prompt ((t (:foreground "#29D298"))))
 '(link ((t (:foreground "#59E2E2" :underline t))))
 '(warning ((t (:foreground "#F9B795"))))
 '(error ((t (:foreground "#E85678"))))
 '(success ((t (:foreground "#29D298"))))
 '(bold ((t (:foreground "#EB6A88" :weight bold))))
 '(isearch ((t (:foreground "#26BBD8" :background "#1C1E26"))))
 '(lazy-highlight ((t (:foreground "#FAC2A7" :background "#1C1E26"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#F9B795" :background "#27272F" :weight bold))))
 '(tooltip ((t (:foreground "#26BBD8" :background "#1D2E38" :weight bold))))
 '(fringe ((t (:background "#1C1E26"))))
 '(vertical-border ((t (:foreground "#4F2C3B"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#F9D9D0"))))
 '(header-line ((t (:foreground "#29D298" :background "#27272F"))))
 '(header-line-highlight ((t (:foreground "#EB6A88" :background "#27272F"))))
 '(highlight ((t (:foreground "#FAC2A7" :background "#1C1E26"))))
 '(button ((t (:foreground "#ED64AC" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#29D298" :background "#1D2E38" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#F9D9D0" :background "#1D2E38" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#FAC2A7"))))
 '(font-lock-type-face ((t (:foreground "#F9B795"))))
 '(font-lock-preprocessor-face ((t (:foreground "#26BBD8"))))
 '(font-lock-operator-face ((t (:foreground "#26BBD8"))))
 '(font-lock-string-face ((t (:foreground "#29D298"))))
 '(font-lock-variable-name-face ((t (:foreground "#F9D9D0"))))
 '(font-lock-constant-face ((t (:foreground "#EB6A88"))))
 '(font-lock-keyword-face ((t (:foreground "#ED64AC"))))
 '(font-lock-warning-face ((t (:foreground "#F9B795"))))
 '(font-lock-function-name-face ((t (:foreground "#26BBD8"))))
 '(font-lock-negation-char-face ((t (:foreground "#26BBD8"))))
 '(font-lock-variable-use-face ((t (:foreground "#F9D9D0"))))
 '(font-lock-property-use-face ((t (:foreground "#F9D9D0"))))
 '(font-lock-number-face ((t (:foreground "#EB6A88"))))
 '(font-lock-bracket-face ((t (:foreground "#F9D9D0"))))
 '(font-lock-delimiter-face ((t (:foreground "#F9D9D0"))))
 '(font-lock-escape-face ((t (:foreground "#EB6A88"))))
 '(show-paren-match ((t (:foreground "#F9D9D0"))))
 '(show-paren-mismatch-face ((t (:foreground "#E85678" :background "#1C1E26"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#29D298" :background "#1D2E38" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#29D298"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#26BBD8"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#F9B795"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#EB6A88"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#F9D9D0"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#59E2E2"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#26BBD8" :background "#1D2E38" :overline "#29D298"))))
 '(org-level-2 ((t (:foreground "#29D298" :background "#1D2E38" :overline "#29D298"))))
 '(org-level-3 ((t (:foreground "#29D298" :background "#1D2E38" :overline "#29D298"))))
 '(org-level-4 ((t (:foreground "#29D298" :background "#1D2E38" :overline "#29D298"))))
 '(org-level-5 ((t (:foreground "#29D298" :background "#1D2E38" :overline "#29D298"))))
 '(org-level-6 ((t (:foreground "#29D298" :background "#1D2E38" :overline "#29D298"))))
 '(org-level-7 ((t (:foreground "#29D298" :background "#1D2E38" :overline "#29D298"))))
 '(org-tag ((t (:foreground "#F9D9D0"))))
 '(org-headline-done ((t (:foreground "#ED64AC" :background "#1D2E38"))))
 '(org-done ((t (:foreground "#F9D9D0"))))
 '(org-todo ((t (:foreground "#F9B795"))))
 '(org-checkbox ((t (:foreground "#FAC2A7" :background "#1D2E38"))))
 '(org-link ((t (:foreground "#59E2E2" :background "#1C1E26" :underline nil))))
 '(org-verbatim ((t (:foreground "#EB6A88"))))
 '(org-code ((t (:foreground "#EB6A88"))))
 '(org-table ((t (:foreground "#EB6A88" :background "#27272F"))))
 '(org-date ((t (:foreground "#29D298" :underline t))))
 '(org-archived ((t (:foreground "#29D298" :background "#1D2E38"))))
 '(org-list-dt ((t (:foreground "#FAC2A7"))))
 '(org-drawer ((t (:foreground "#26BBD8"))))
 '(org-special-keyword ((t (:foreground "#F9D9D0"))))
 '(org-property-value ((t (:foreground "#F9D9D0" :background "#1C1E26"))))
 '(org-block ((t (:background "#1D2E38" :extend t))))
 '(org-block-begin-line ((t (:foreground "#29D298" :background "#1C1E26" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#F9D9D0"))))
 '(org-superstar-header-bullet ((t (:foreground "#FAC2A7" :background "#27272F" :overline t))))
 '(org-superstar-item ((t (:foreground "#F9B795"))))
 '(org-superstar-ordered-item ((t (:foreground "#59E2E2"))))
 '(org-hide ((t (:foreground "#1C1E26"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#26BBD8" :height 220 :underline "#26BBD8"))))
 '(markdown-header-face-2 ((t (:foreground "#29D298" :height 180 :underline "#26BBD8"))))
 '(markdown-header-face-3 ((t (:foreground "#29D298" :underline "#F9D9D0"))))
 '(markdown-header-face-4 ((t (:foreground "#EB6A88"))))
 '(markdown-header-face-5 ((t (:foreground "#EB6A88"))))
 '(markdown-header-face-6 ((t (:foreground "#EB6A88"))))
 '(markdown-list-face ((t (:foreground "#F9B795"))))
 '(markdown-inline-code-face ((t (:foreground "#EB6A88" :background "#1D2E38"))))
 '(markdown-language-keyword-face ((t (:foreground "#F9D9D0"))))
 '(markdown-pre-face ((t (:foreground "#EB6A88"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#29D298"))))
 '(markdown-header-delimiter-face ((t (:foreground "#F9D9D0"))))
 '(markdown-bold-face ((t (:foreground "#EB6A88" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#EB6A88" :slant italic))))
 '(markdown-link-face ((t (:foreground "#EB6A88"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#26BBD8"))))
 '(compilation-warning ((t (:foreground "#26BBD8"))))
 '(compilation-error ((t (:foreground "#E85678"))))
 '(compilation-line-number ((t (:foreground "#EB6A88" :underline t))))
 '(compilation-column-number ((t (:foreground "#EB6A88" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#E85678"))))
 '(flycheck-fringe-warning ((t (:foreground "#26BBD8"))))
 '(flycheck-fringe-info ((t (:foreground "#26BBD8"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#27272F"))))
 '(lsp-face-highlight-textual ((t (:background "#1C1E26"))))
 '(lsp-face-highlight-write ((t (:background "#1C1E26"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#1C1E26"))))
 '(eglot-inlay-hint-face ((t (:foreground "#EB6A88" :background "#1D2E38" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#EB6A88"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#F9D9D0" :background "#27272F"))))
 '(company-preview-common ((t (:foreground "#EB6A88" :background "#27272F"))))
 '(company-preview-search ((t (:foreground "#EB6A88" :background "#27272F"))))
 '(company-tooltip-common ((t (:foreground "#EB6A88" :background "#27272F"))))
 '(company-tooltip-common-selection ((t (:foreground "#EB6A88" :background "#27272F"))))
 '(company-tooltip-annotation ((t (:foreground "#EB6A88" :background "#27272F"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#EB6A88" :background "#27272F"))))
 '(company-tooltip-search-selection ((t (:foreground "#EB6A88" :background "#1C1E26"))))
 '(company-tooltip-mouse ((t (:foreground "#EB6A88" :background "#1C1E26"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#F9D9D0" :background "#1D2E38"))))
 '(magit-branch-current ((t (:foreground "#26BBD8" :box 1))))
 '(magit-branch-remote ((t (:foreground "#26BBD8" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#ED64AC"))))
 '(rg-line-number-face ((t (:foreground "#EB6A88"))))

 ;; line numbers
 '(line-number ((t (:foreground "#29D298" :background "#1C1E26"))))
 '(line-number-current-line ((t (:foreground "#29D298" :background "#1C1E26"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#5C5F7D"))))
 '(doom-modeline-bar ((t (:background "#27272F"))))
 '(doom-modeline-bar-inactive ((t (:background "#1C1E26"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#59E2E2" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#ED64AC"))))
 '(doom-modeline-project-dir ((t (:foreground "#F9D9D0"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#F9D9D0"))))
 '(doom-modeline-urgent ((t (:foreground "#ED64AC"))))
 '(doom-modeline-info ((t (:foreground "#F9D9D0"))))
 '(doom-modeline-warning ((t (:foreground "#ED64AC"))))
 '(doom-modeline-error ((t (:foreground "#E85678"))))
 '(doom-modeline-inactive-bar ((t (:background "#1C1E26"))))
 '(mode-line ((t (:foreground "#484448" :background "#27272F"))))
 '(mode-line-inactive ((t (:background "#27272F"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#484448"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#484448"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#F9D9D0" :background "#1C1E26"))))
 '(tab-bar-tab ((t (:foreground "#29D298" :background "#1C1E26" :box (:line-width 2 :color "#1C1E26")))))
 '(tab-bar-tab-inactive ((t (:foreground "#F9D9D0" :background "#1C1E26"))))

 ;; misc
 '(secondary-selection ((t (:background "#1D2E38"))))
 '(shadow ((t (:foreground "#6C6F93")))))

(provide-theme 'event-horizon)
