
;;; everforest-theme.el --- Generated by Book of Colours

(deftheme everforest "everforest")

(custom-theme-set-faces
 'everforest

 ;; common
 '(default ((t (:foreground "#D2C5AA" :background "#2D353B"))))
 '(cursor ((t (:foreground "#2D353B" :background "#ECDDBF"))))
 '(region ((t (:foreground "#D2C5AA" :background "#2D353B"))))
 '(hl-line ((t (:background "#343F44"))))
 '(minibuffer-prompt ((t (:foreground "#859289"))))
 '(link ((t (:foreground "#7FBBB3" :underline t))))
 '(warning ((t (:foreground "#E59875"))))
 '(error ((t (:foreground "#E57E7F"))))
 '(success ((t (:foreground "#A7C07F"))))
 '(bold ((t (:foreground "#DABC7F" :weight bold))))
 '(isearch ((t (:foreground "#D2C5AA" :background "#2D353B"))))
 '(lazy-highlight ((t (:foreground "#859289" :background "#2D353B"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#E59875" :background "#232A2E" :weight bold))))
 '(tooltip ((t (:foreground "#D2C5AA" :background "#343F44" :weight bold))))
 '(fringe ((t (:background "#2D353B"))))
 '(vertical-border ((t (:foreground "#232A2E"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#D2C5AA"))))
 '(header-line ((t (:foreground "#859289" :background "#232A2E"))))
 '(header-line-highlight ((t (:foreground "#DABC7F" :background "#232A2E"))))
 '(highlight ((t (:foreground "#859289" :background "#2D353B"))))
 '(button ((t (:foreground "#E57E7F" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#859289" :background "#343F44" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#D2C5AA" :background "#343F44" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#859289"))))
 '(font-lock-type-face ((t (:foreground "#BFDCD8"))))
 '(font-lock-preprocessor-face ((t (:foreground "#E57E7F"))))
 '(font-lock-operator-face ((t (:foreground "#E59875"))))
 '(font-lock-string-face ((t (:foreground "#83C092"))))
 '(font-lock-variable-name-face ((t (:foreground "#7FBBB3"))))
 '(font-lock-constant-face ((t (:foreground "#ECDDBF"))))
 '(font-lock-keyword-face ((t (:foreground "#E57E7F"))))
 '(font-lock-warning-face ((t (:foreground "#E59875"))))
 '(font-lock-function-name-face ((t (:foreground "#A7C07F"))))
 '(font-lock-negation-char-face ((t (:foreground "#E59875"))))
 '(font-lock-variable-use-face ((t (:foreground "#D2C5AA"))))
 '(font-lock-property-use-face ((t (:foreground "#D2C5AA"))))
 '(font-lock-number-face ((t (:foreground "#ECDDBF"))))
 '(font-lock-bracket-face ((t (:foreground "#DABC7F"))))
 '(font-lock-delimiter-face ((t (:foreground "#7FBBB3"))))
 '(font-lock-escape-face ((t (:foreground "#DABC7F"))))
 '(show-paren-match ((t (:foreground "#859289"))))
 '(show-paren-mismatch-face ((t (:foreground "#E57E7F" :background "#2D353B"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#859289" :background "#343F44" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#83C092"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#A7C07F"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#BFDCD8"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#ECDDBF"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#D2C5AA"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#7FBBB3"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#D2C5AA" :background "#343F44" :overline "#859289"))))
 '(org-level-2 ((t (:foreground "#DABC7F" :background "#343F44" :overline "#859289"))))
 '(org-level-3 ((t (:foreground "#DABC7F" :background "#343F44" :overline "#859289"))))
 '(org-level-4 ((t (:foreground "#D2C5AA" :background "#343F44" :overline "#859289"))))
 '(org-level-5 ((t (:foreground "#D2C5AA" :background "#343F44" :overline "#859289"))))
 '(org-level-6 ((t (:foreground "#D2C5AA" :background "#343F44" :overline "#859289"))))
 '(org-level-7 ((t (:foreground "#D2C5AA" :background "#343F44" :overline "#859289"))))
 '(org-tag ((t (:foreground "#7FBBB3"))))
 '(org-headline-done ((t (:foreground "#E57E7F" :background "#343F44"))))
 '(org-done ((t (:foreground "#D2C5AA"))))
 '(org-todo ((t (:foreground "#DABC7F"))))
 '(org-checkbox ((t (:foreground "#859289" :background "#2D353B"))))
 '(org-link ((t (:foreground "#7FBBB3" :background "#2D353B" :underline nil))))
 '(org-verbatim ((t (:foreground "#DABC7F"))))
 '(org-code ((t (:foreground "#DABC7F"))))
 '(org-table ((t (:foreground "#DABC7F" :background "#232A2E"))))
 '(org-date ((t (:foreground "#DABC7F" :underline t))))
 '(org-archived ((t (:foreground "#859289" :background "#343F44"))))
 '(org-list-dt ((t (:foreground "#859289"))))
 '(org-drawer ((t (:foreground "#E57E7F"))))
 '(org-special-keyword ((t (:foreground "#7FBBB3"))))
 '(org-property-value ((t (:foreground "#D2C5AA" :background "#2D353B"))))
 '(org-block ((t (:background "#343F44" :extend t))))
 '(org-block-begin-line ((t (:foreground "#859289" :background "#2D353B" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#7FBBB3"))))
 '(org-superstar-header-bullet ((t (:foreground "#859289" :background "#232A2E" :overline t))))
 '(org-superstar-item ((t (:foreground "#E59875"))))
 '(org-superstar-ordered-item ((t (:foreground "#7FBBB3"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#DABC7F" :height 220 :underline "#D2C5AA"))))
 '(markdown-header-face-2 ((t (:foreground "#DABC7F" :height 180 :underline "#D2C5AA"))))
 '(markdown-header-face-3 ((t (:foreground "#DABC7F" :underline "#D2C5AA"))))
 '(markdown-header-face-4 ((t (:foreground "#DABC7F"))))
 '(markdown-header-face-5 ((t (:foreground "#DABC7F"))))
 '(markdown-header-face-6 ((t (:foreground "#DABC7F"))))
 '(markdown-list-face ((t (:foreground "#E59875"))))
 '(markdown-inline-code-face ((t (:foreground "#DABC7F" :background "#343F44"))))
 '(markdown-language-keyword-face ((t (:foreground "#7FBBB3"))))
 '(markdown-pre-face ((t (:foreground "#DABC7F"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#859289"))))
 '(markdown-header-delimiter-face ((t (:foreground "#DABC7F"))))
 '(markdown-bold-face ((t (:foreground "#DABC7F" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#DABC7F" :slant italic))))
 '(markdown-link-face ((t (:foreground "#DABC7F"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#D2C5AA"))))
 '(compilation-warning ((t (:foreground "#D2C5AA"))))
 '(compilation-error ((t (:foreground "#E57E7F"))))
 '(compilation-line-number ((t (:foreground "#DABC7F" :underline t))))
 '(compilation-column-number ((t (:foreground "#DABC7F" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#E57E7F"))))
 '(flycheck-fringe-warning ((t (:foreground "#D2C5AA"))))
 '(flycheck-fringe-info ((t (:foreground "#D2C5AA"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#232A2E"))))
 '(lsp-face-highlight-textual ((t (:background "#2D353B"))))
 '(lsp-face-highlight-write ((t (:background "#2D353B"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#2D353B"))))
 '(eglot-inlay-hint-face ((t (:foreground "#DABC7F" :background "#343F44" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#DABC7F"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#D2C5AA" :background "#232A2E"))))
 '(company-preview-common ((t (:foreground "#DABC7F" :background "#232A2E"))))
 '(company-preview-search ((t (:foreground "#DABC7F" :background "#232A2E"))))
 '(company-tooltip-common ((t (:foreground "#DABC7F" :background "#232A2E"))))
 '(company-tooltip-common-selection ((t (:foreground "#DABC7F" :background "#232A2E"))))
 '(company-tooltip-annotation ((t (:foreground "#DABC7F" :background "#232A2E"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#DABC7F" :background "#232A2E"))))
 '(company-tooltip-search-selection ((t (:foreground "#DABC7F" :background "#2D353B"))))
 '(company-tooltip-mouse ((t (:foreground "#DABC7F" :background "#2D353B"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#D2C5AA" :background "#343F44"))))
 '(magit-branch-current ((t (:foreground "#D2C5AA" :box 1))))
 '(magit-branch-remote ((t (:foreground "#D2C5AA" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#E57E7F"))))
 '(rg-line-number-face ((t (:foreground "#DABC7F"))))

 ;; line numbers
 '(line-number ((t (:foreground "#859289" :background "#2D353B"))))
 '(line-number-current-line ((t (:foreground "#859289" :background "#2D353B"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#7A8478"))))
 '(doom-modeline-bar ((t (:background "#232A2E"))))
 '(doom-modeline-bar-inactive ((t (:background "#2D353B"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#7FBBB3" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#E57E7F"))))
 '(doom-modeline-project-dir ((t (:foreground "#D2C5AA"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#D2C5AA"))))
 '(doom-modeline-urgent ((t (:foreground "#E57E7F"))))
 '(doom-modeline-info ((t (:foreground "#D2C5AA"))))
 '(doom-modeline-warning ((t (:foreground "#E57E7F"))))
 '(doom-modeline-error ((t (:foreground "#E57E7F"))))
 '(doom-modeline-inactive-bar ((t (:background "#2D353B"))))
 '(mode-line ((t (:foreground "#3D484D" :background "#232A2E"))))
 '(mode-line-inactive ((t (:background "#232A2E"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#3D484D"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#3D484D"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#7FBBB3" :background "#2D353B"))))
 '(tab-bar-tab ((t (:foreground "#DABC7F" :background "#2D353B" :box (:line-width 2 :color "#2D353B")))))
 '(tab-bar-tab-inactive ((t (:foreground "#7FBBB3" :background "#2D353B"))))

 ;; misc
 '(secondary-selection ((t (:background "#343F44"))))
 '(shadow ((t (:foreground "#859289")))))

(provide-theme 'everforest)
