
;;; flexoki-theme.el --- Generated by Book of Colours

(deftheme flexoki "flexoki")

(custom-theme-set-faces
 'flexoki

 ;; common
 '(default ((t (:foreground "#6F6E69" :background "#FFFBEF"))))
 '(cursor ((t (:foreground "#FFFBEF" :background "#100F0F"))))
 '(region ((t (:foreground "#100F0F" :background "#CDCCC2"))))
 '(hl-line ((t (:background "#EEEBE0"))))
 '(minibuffer-prompt ((t (:foreground "#6F6E69"))))
 '(link ((t (:foreground "#5E409D" :underline t))))
 '(warning ((t (:foreground "#AF3029"))))
 '(error ((t (:foreground "#AF3029"))))
 '(success ((t (:foreground "#667F0B"))))
 '(bold ((t (:foreground "#A02F6F" :weight bold))))
 '(isearch ((t (:foreground "#100F0F" :background "#CDCCC2"))))
 '(lazy-highlight ((t (:foreground "#100F0F" :background "#CDCCC2"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#AF3029" :background "#FFFBEF" :weight bold))))
 '(tooltip ((t (:foreground "#205EA6" :background "#F1EFE4" :weight bold))))
 '(fringe ((t (:background "#FFFBEF"))))
 '(vertical-border ((t (:foreground "#3AA99F"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#4385BE"))))
 '(header-line ((t (:foreground "#6F6E69" :background "#FFFBEF"))))
 '(header-line-highlight ((t (:foreground "#A02F6F" :background "#FFFBEF"))))
 '(highlight ((t (:foreground "#100F0F" :background "#CDCCC2"))))
 '(button ((t (:foreground "#5E409D" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#6F6E69" :background "#F1EFE4" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#6F6E69" :background "#F1EFE4" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#100F0F"))))
 '(font-lock-type-face ((t (:foreground "#879A39"))))
 '(font-lock-preprocessor-face ((t (:foreground "#879A39"))))
 '(font-lock-operator-face ((t (:foreground "#100F0F"))))
 '(font-lock-string-face ((t (:foreground "#24837B"))))
 '(font-lock-variable-name-face ((t (:foreground "#4385BE"))))
 '(font-lock-constant-face ((t (:foreground "#A02F6F"))))
 '(font-lock-keyword-face ((t (:foreground "#5E409D"))))
 '(font-lock-warning-face ((t (:foreground "#AF3029"))))
 '(font-lock-function-name-face ((t (:foreground "#BC5215"))))
 '(font-lock-negation-char-face ((t (:foreground "#100F0F"))))
 '(font-lock-variable-use-face ((t (:foreground "#4385BE"))))
 '(font-lock-property-use-face ((t (:foreground "#6F6E69"))))
 '(font-lock-number-face ((t (:foreground "#5E409D"))))
 '(font-lock-bracket-face ((t (:foreground "#100F0F"))))
 '(font-lock-delimiter-face ((t (:foreground "#3AA99F"))))
 '(font-lock-escape-face ((t (:foreground "#A02F6F"))))
 '(show-paren-match ((t (:foreground "#100F0F"))))
 '(show-paren-mismatch-face ((t (:foreground "#AF3029" :background "#FFFBEF"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#6F6E69" :background "#F1EFE4" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#24837B"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#BC5215"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#879A39"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#A02F6F"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#4385BE"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#4385BE"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#205EA6" :background "#EEEBE0" :overline "#6F6E69"))))
 '(org-level-2 ((t (:foreground "#205EA6" :background "#EEEBE0" :overline "#6F6E69"))))
 '(org-level-3 ((t (:foreground "#205EA6" :background "#EEEBE0" :overline "#6F6E69"))))
 '(org-level-4 ((t (:foreground "#205EA6" :background "#EEEBE0" :overline "#6F6E69"))))
 '(org-level-5 ((t (:foreground "#205EA6" :background "#EEEBE0" :overline "#6F6E69"))))
 '(org-level-6 ((t (:foreground "#205EA6" :background "#EEEBE0" :overline "#6F6E69"))))
 '(org-level-7 ((t (:foreground "#205EA6" :background "#EEEBE0" :overline "#6F6E69"))))
 '(org-tag ((t (:foreground "#4385BE"))))
 '(org-headline-done ((t (:foreground "#5E409D" :background "#F1EFE4"))))
 '(org-done ((t (:foreground "#6F6E69"))))
 '(org-todo ((t (:foreground "#AD8301"))))
 '(org-checkbox ((t (:foreground "#100F0F" :background "#FFFBEF"))))
 '(org-link ((t (:foreground "#5E409D" :background "#FFFBEF" :underline nil))))
 '(org-verbatim ((t (:foreground "#A02F6F"))))
 '(org-code ((t (:foreground "#A02F6F"))))
 '(org-table ((t (:foreground "#A02F6F" :background "#FFFBEF"))))
 '(org-date ((t (:foreground "#205EA6" :underline t))))
 '(org-archived ((t (:foreground "#6F6E69" :background "#F1EFE4"))))
 '(org-list-dt ((t (:foreground "#100F0F"))))
 '(org-drawer ((t (:foreground "#879A39"))))
 '(org-special-keyword ((t (:foreground "#3AA99F"))))
 '(org-property-value ((t (:foreground "#4385BE" :background "#FFFBEF"))))
 '(org-block ((t (:background "#EEEBE0" :extend t))))
 '(org-block-begin-line ((t (:foreground "#6F6E69" :background "#FFFBEF" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#3AA99F"))))
 '(org-superstar-header-bullet ((t (:foreground "#100F0F" :background "#FFFBEF" :overline t))))
 '(org-superstar-item ((t (:foreground "#AF3029"))))
 '(org-superstar-ordered-item ((t (:foreground "#4385BE"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#A02F6F" :height 220 :underline "#205EA6"))))
 '(markdown-header-face-2 ((t (:foreground "#A02F6F" :height 180 :underline "#205EA6"))))
 '(markdown-header-face-3 ((t (:foreground "#A02F6F" :underline "#6F6E69"))))
 '(markdown-header-face-4 ((t (:foreground "#A02F6F"))))
 '(markdown-header-face-5 ((t (:foreground "#A02F6F"))))
 '(markdown-header-face-6 ((t (:foreground "#A02F6F"))))
 '(markdown-list-face ((t (:foreground "#AF3029"))))
 '(markdown-inline-code-face ((t (:foreground "#A02F6F" :background "#F1EFE4"))))
 '(markdown-language-keyword-face ((t (:foreground "#4385BE"))))
 '(markdown-pre-face ((t (:foreground "#A02F6F"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#6F6E69"))))
 '(markdown-header-delimiter-face ((t (:foreground "#100F0F"))))
 '(markdown-bold-face ((t (:foreground "#A02F6F" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#A02F6F" :slant italic))))
 '(markdown-link-face ((t (:foreground "#A02F6F"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#205EA6"))))
 '(compilation-warning ((t (:foreground "#205EA6"))))
 '(compilation-error ((t (:foreground "#AF3029"))))
 '(compilation-line-number ((t (:foreground "#A02F6F" :underline t))))
 '(compilation-column-number ((t (:foreground "#A02F6F" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#AF3029"))))
 '(flycheck-fringe-warning ((t (:foreground "#205EA6"))))
 '(flycheck-fringe-info ((t (:foreground "#205EA6"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#FFFBEF"))))
 '(lsp-face-highlight-textual ((t (:background "#CDCCC2"))))
 '(lsp-face-highlight-write ((t (:background "#CDCCC2"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#CDCCC2"))))
 '(eglot-inlay-hint-face ((t (:foreground "#A02F6F" :background "#F1EFE4" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#A02F6F"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#4385BE" :background "#FFFBEF"))))
 '(company-preview-common ((t (:foreground "#A02F6F" :background "#FFFBEF"))))
 '(company-preview-search ((t (:foreground "#A02F6F" :background "#FFFBEF"))))
 '(company-tooltip-common ((t (:foreground "#A02F6F" :background "#FFFBEF"))))
 '(company-tooltip-common-selection ((t (:foreground "#A02F6F" :background "#FFFBEF"))))
 '(company-tooltip-annotation ((t (:foreground "#A02F6F" :background "#FFFBEF"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#A02F6F" :background "#FFFBEF"))))
 '(company-tooltip-search-selection ((t (:foreground "#A02F6F" :background "#CDCCC2"))))
 '(company-tooltip-mouse ((t (:foreground "#A02F6F" :background "#CDCCC2"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#6F6E69" :background "#F1EFE4"))))
 '(magit-branch-current ((t (:foreground "#205EA6" :box 1))))
 '(magit-branch-remote ((t (:foreground "#205EA6" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#5E409D"))))
 '(rg-line-number-face ((t (:foreground "#A02F6F"))))

 ;; line numbers
 '(line-number ((t (:foreground "#6F6E69" :background "#FFFBEF"))))
 '(line-number-current-line ((t (:foreground "#6F6E69" :background "#FFFBEF"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#6F6E69"))))
 '(doom-modeline-bar ((t (:background "#FFFBEF"))))
 '(doom-modeline-bar-inactive ((t (:background "#FFFBEF"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#4385BE" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#5E409D"))))
 '(doom-modeline-project-dir ((t (:foreground "#4385BE"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#6F6E69"))))
 '(doom-modeline-urgent ((t (:foreground "#5E409D"))))
 '(doom-modeline-info ((t (:foreground "#4385BE"))))
 '(doom-modeline-warning ((t (:foreground "#5E409D"))))
 '(doom-modeline-error ((t (:foreground "#AF3029"))))
 '(doom-modeline-inactive-bar ((t (:background "#FFFBEF"))))
 '(mode-line ((t (:foreground "#F1EFE4" :background "#FFFBEF"))))
 '(mode-line-inactive ((t (:background "#FFFBEF"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#F1EFE4"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#F1EFE4"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#3AA99F" :background "#FFFBEF"))))
 '(tab-bar-tab ((t (:foreground "#205EA6" :background "#FFFBEF" :box (:line-width 2 :color "#FFFBEF")))))
 '(tab-bar-tab-inactive ((t (:foreground "#3AA99F" :background "#FFFBEF"))))

 ;; misc
 '(secondary-selection ((t (:background "#EEEBE0"))))
 '(shadow ((t (:foreground "#3AA99F")))))

(provide-theme 'flexoki)
