
;;; gruvbox-theme.el --- Generated by Book of Colours

(deftheme gruvbox "gruvbox")

(custom-theme-set-faces
 'gruvbox

 ;; common
 '(default ((t (:foreground "#D3BE98" :background "#282828"))))
 '(cursor ((t (:foreground "#282828" :background "#FAF0C6"))))
 '(region ((t (:foreground "#FAF0C6" :background "#504945"))))
 '(hl-line ((t (:background "#3C3836"))))
 '(minibuffer-prompt ((t (:foreground "#928374"))))
 '(link ((t (:foreground "#D3BE98" :underline t))))
 '(warning ((t (:foreground "#F9BD2F"))))
 '(error ((t (:foreground "#FA4934"))))
 '(success ((t (:foreground "#8EC07C"))))
 '(bold ((t (:foreground "#FAF0C6" :weight bold))))
 '(isearch ((t (:foreground "#FAF0C6" :background "#504945"))))
 '(lazy-highlight ((t (:foreground "#F9BD2F" :background "#504945"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#F9BD2F" :background "#3C3836" :weight bold))))
 '(tooltip ((t (:foreground "#B8BB26" :background "#282828" :weight bold))))
 '(fringe ((t (:background "#282828"))))
 '(vertical-border ((t (:foreground "#722529"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#7DAEA3"))))
 '(header-line ((t (:foreground "#928374" :background "#3C3836"))))
 '(header-line-highlight ((t (:foreground "#F9BD2F" :background "#3C3836"))))
 '(highlight ((t (:foreground "#F9BD2F" :background "#504945"))))
 '(button ((t (:foreground "#E96962" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#928374" :background "#282828" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#D3BE98" :background "#282828" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#F9BD2F"))))
 '(font-lock-type-face ((t (:foreground "#D7A657"))))
 '(font-lock-preprocessor-face ((t (:foreground "#89B482"))))
 '(font-lock-operator-face ((t (:foreground "#FD7F19"))))
 '(font-lock-string-face ((t (:foreground "#A9B665"))))
 '(font-lock-variable-name-face ((t (:foreground "#EADAB2"))))
 '(font-lock-constant-face ((t (:foreground "#D2869B"))))
 '(font-lock-keyword-face ((t (:foreground "#E96962"))))
 '(font-lock-warning-face ((t (:foreground "#F9BD2F"))))
 '(font-lock-function-name-face ((t (:foreground "#B8BB26"))))
 '(font-lock-negation-char-face ((t (:foreground "#FD7F19"))))
 '(font-lock-variable-use-face ((t (:foreground "#7DAEA3"))))
 '(font-lock-property-use-face ((t (:foreground "#D3BE98"))))
 '(font-lock-number-face ((t (:foreground "#D2869B"))))
 '(font-lock-bracket-face ((t (:foreground "#A89984"))))
 '(font-lock-delimiter-face ((t (:foreground "#928374"))))
 '(font-lock-escape-face ((t (:foreground "#FAF0C6"))))
 '(show-paren-match ((t (:foreground "#F9BD2F"))))
 '(show-paren-mismatch-face ((t (:foreground "#FA4934" :background "#282828"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#928374" :background "#282828" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#A9B665"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#B8BB26"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#D7A657"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#D2869B"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#7DAEA3"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#EADAB2"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#B8BB26" :background "#3C3836" :overline "#928374"))))
 '(org-level-2 ((t (:foreground "#B8BB26" :background "#3C3836" :overline "#928374"))))
 '(org-level-3 ((t (:foreground "#B8BB26" :background "#3C3836" :overline "#928374"))))
 '(org-level-4 ((t (:foreground "#B8BB26" :background "#3C3836" :overline "#928374"))))
 '(org-level-5 ((t (:foreground "#B8BB26" :background "#3C3836" :overline "#928374"))))
 '(org-level-6 ((t (:foreground "#B8BB26" :background "#3C3836" :overline "#928374"))))
 '(org-level-7 ((t (:foreground "#B8BB26" :background "#3C3836" :overline "#928374"))))
 '(org-tag ((t (:foreground "#EADAB2"))))
 '(org-headline-done ((t (:foreground "#E96962" :background "#282828"))))
 '(org-done ((t (:foreground "#D3BE98"))))
 '(org-todo ((t (:foreground "#F9BD2F"))))
 '(org-checkbox ((t (:foreground "#F9BD2F" :background "#282828"))))
 '(org-link ((t (:foreground "#D3BE98" :background "#282828" :underline nil))))
 '(org-verbatim ((t (:foreground "#F9BD2F"))))
 '(org-code ((t (:foreground "#FAF0C6"))))
 '(org-table ((t (:foreground "#F9BD2F" :background "#3C3836"))))
 '(org-date ((t (:foreground "#B8BB26" :underline t))))
 '(org-archived ((t (:foreground "#928374" :background "#282828"))))
 '(org-list-dt ((t (:foreground "#F9BD2F"))))
 '(org-drawer ((t (:foreground "#89B482"))))
 '(org-special-keyword ((t (:foreground "#83A598"))))
 '(org-property-value ((t (:foreground "#7DAEA3" :background "#282828"))))
 '(org-block ((t (:background "#3C3836" :extend t))))
 '(org-block-begin-line ((t (:foreground "#928374" :background "#282828" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#928374"))))
 '(org-superstar-header-bullet ((t (:foreground "#F9BD2F" :background "#3C3836" :overline t))))
 '(org-superstar-item ((t (:foreground "#F9BD2F"))))
 '(org-superstar-ordered-item ((t (:foreground "#EADAB2"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#FAF0C6" :height 220 :underline "#B8BB26"))))
 '(markdown-header-face-2 ((t (:foreground "#F9BD2F" :height 180 :underline "#B8BB26"))))
 '(markdown-header-face-3 ((t (:foreground "#FAF0C6" :underline "#D3BE98"))))
 '(markdown-header-face-4 ((t (:foreground "#F9BD2F"))))
 '(markdown-header-face-5 ((t (:foreground "#FAF0C6"))))
 '(markdown-header-face-6 ((t (:foreground "#F9BD2F"))))
 '(markdown-list-face ((t (:foreground "#F9BD2F"))))
 '(markdown-inline-code-face ((t (:foreground "#FAF0C6" :background "#282828"))))
 '(markdown-language-keyword-face ((t (:foreground "#EADAB2"))))
 '(markdown-pre-face ((t (:foreground "#F9BD2F"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#928374"))))
 '(markdown-header-delimiter-face ((t (:foreground "#A89984"))))
 '(markdown-bold-face ((t (:foreground "#FAF0C6" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#F9BD2F" :slant italic))))
 '(markdown-link-face ((t (:foreground "#FAF0C6"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#B8BB26"))))
 '(compilation-warning ((t (:foreground "#B8BB26"))))
 '(compilation-error ((t (:foreground "#FA4934"))))
 '(compilation-line-number ((t (:foreground "#F9BD2F" :underline t))))
 '(compilation-column-number ((t (:foreground "#FAF0C6" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#FA4934"))))
 '(flycheck-fringe-warning ((t (:foreground "#B8BB26"))))
 '(flycheck-fringe-info ((t (:foreground "#B8BB26"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#3C3836"))))
 '(lsp-face-highlight-textual ((t (:background "#504945"))))
 '(lsp-face-highlight-write ((t (:background "#504945"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#504945"))))
 '(eglot-inlay-hint-face ((t (:foreground "#F9BD2F" :background "#282828" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#FAF0C6"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#7DAEA3" :background "#3C3836"))))
 '(company-preview-common ((t (:foreground "#F9BD2F" :background "#3C3836"))))
 '(company-preview-search ((t (:foreground "#FAF0C6" :background "#3C3836"))))
 '(company-tooltip-common ((t (:foreground "#F9BD2F" :background "#3C3836"))))
 '(company-tooltip-common-selection ((t (:foreground "#FAF0C6" :background "#3C3836"))))
 '(company-tooltip-annotation ((t (:foreground "#F9BD2F" :background "#3C3836"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#FAF0C6" :background "#3C3836"))))
 '(company-tooltip-search-selection ((t (:foreground "#F9BD2F" :background "#504945"))))
 '(company-tooltip-mouse ((t (:foreground "#FAF0C6" :background "#504945"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#D3BE98" :background "#282828"))))
 '(magit-branch-current ((t (:foreground "#B8BB26" :box 1))))
 '(magit-branch-remote ((t (:foreground "#B8BB26" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#E96962"))))
 '(rg-line-number-face ((t (:foreground "#F9BD2F"))))

 ;; line numbers
 '(line-number ((t (:foreground "#928374" :background "#282828"))))
 '(line-number-current-line ((t (:foreground "#928374" :background "#282828"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#7C6F64"))))
 '(doom-modeline-bar ((t (:background "#3C3836"))))
 '(doom-modeline-bar-inactive ((t (:background "#282828"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#EADAB2" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#E96962"))))
 '(doom-modeline-project-dir ((t (:foreground "#7DAEA3"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#D3BE98"))))
 '(doom-modeline-urgent ((t (:foreground "#E96962"))))
 '(doom-modeline-info ((t (:foreground "#7DAEA3"))))
 '(doom-modeline-warning ((t (:foreground "#E96962"))))
 '(doom-modeline-error ((t (:foreground "#FA4934"))))
 '(doom-modeline-inactive-bar ((t (:background "#282828"))))
 '(mode-line ((t (:foreground "#49503B" :background "#3C3836"))))
 '(mode-line-inactive ((t (:background "#3C3836"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#49503B"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#49503B"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#83A598" :background "#282828"))))
 '(tab-bar-tab ((t (:foreground "#B8BB26" :background "#282828" :box (:line-width 2 :color "#282828")))))
 '(tab-bar-tab-inactive ((t (:foreground "#928374" :background "#282828"))))

 ;; misc
 '(secondary-selection ((t (:background "#3C3836"))))
 '(shadow ((t (:foreground "#928374")))))

(provide-theme 'gruvbox)
