
;;; hackerman-theme.el --- Generated by Book of Colours

(deftheme hackerman "hackerman")

(custom-theme-set-faces
 'hackerman

 ;; common
 '(default ((t (:foreground "#C0CBD4" :background "#1A1D24"))))
 '(cursor ((t (:foreground "#1A1D24" :background "#DCF6FF"))))
 '(region ((t (:foreground "#DCF6FF" :background "#0B0C16"))))
 '(hl-line ((t (:background "#13161C"))))
 '(minibuffer-prompt ((t (:foreground "#4A5366"))))
 '(link ((t (:foreground "#5B9EA0" :underline t))))
 '(warning ((t (:foreground "#D3A05A"))))
 '(error ((t (:foreground "#C36E5A"))))
 '(success ((t (:foreground "#7EB89A"))))
 '(bold ((t (:foreground "#D3A05A" :weight bold))))
 '(isearch ((t (:foreground "#DCF6FF" :background "#0B0C16"))))
 '(lazy-highlight ((t (:foreground "#C9A36D" :background "#0B0C16"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#D3A05A" :background "#1F222B" :weight bold))))
 '(tooltip ((t (:foreground "#5E9A7E" :background "#1A1D24" :weight bold))))
 '(fringe ((t (:background "#1A1D24"))))
 '(vertical-border ((t (:foreground "#3F372F"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#4D788F"))))
 '(header-line ((t (:foreground "#4A5366" :background "#1F222B"))))
 '(header-line-highlight ((t (:foreground "#D3A05A" :background "#1F222B"))))
 '(highlight ((t (:foreground "#C9A36D" :background "#0B0C16"))))
 '(button ((t (:foreground "#A68EBA" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#4A5366" :background "#1A1D24" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#5B9EA0" :background "#1A1D24" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#C9A36D"))))
 '(font-lock-type-face ((t (:foreground "#DFB87A"))))
 '(font-lock-preprocessor-face ((t (:foreground "#5A8FAA"))))
 '(font-lock-operator-face ((t (:foreground "#7AAAC1"))))
 '(font-lock-string-face ((t (:foreground "#5E9A7E"))))
 '(font-lock-variable-name-face ((t (:foreground "#5B9EA0"))))
 '(font-lock-constant-face ((t (:foreground "#5E9A7E"))))
 '(font-lock-keyword-face ((t (:foreground "#A68EBA"))))
 '(font-lock-warning-face ((t (:foreground "#D3A05A"))))
 '(font-lock-function-name-face ((t (:foreground "#5A8FAA"))))
 '(font-lock-negation-char-face ((t (:foreground "#7AAAC1"))))
 '(font-lock-variable-use-face ((t (:foreground "#C0CBD4"))))
 '(font-lock-property-use-face ((t (:foreground "#4D788F"))))
 '(font-lock-number-face ((t (:foreground "#C37A4E"))))
 '(font-lock-bracket-face ((t (:foreground "#A2AEBB"))))
 '(font-lock-delimiter-face ((t (:foreground "#6B7688"))))
 '(font-lock-escape-face ((t (:foreground "#D3A05A"))))
 '(show-paren-match ((t (:foreground "#A2AEBB"))))
 '(show-paren-mismatch-face ((t (:foreground "#C36E5A" :background "#1A1D24"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#4A5366" :background "#1A1D24" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#5E9A7E"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#5A8FAA"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#DFB87A"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#5E9A7E"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#5B9EA0"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#5B9EA0"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#5E9A7E" :background "#13161C" :overline "#4A5366"))))
 '(org-level-2 ((t (:foreground "#5B9EA0" :background "#13161C" :overline "#4A5366"))))
 '(org-level-3 ((t (:foreground "#5B9EA0" :background "#13161C" :overline "#4A5366"))))
 '(org-level-4 ((t (:foreground "#5B9EA0" :background "#13161C" :overline "#4A5366"))))
 '(org-level-5 ((t (:foreground "#5B9EA0" :background "#13161C" :overline "#4A5366"))))
 '(org-level-6 ((t (:foreground "#5B9EA0" :background "#13161C" :overline "#4A5366"))))
 '(org-level-7 ((t (:foreground "#5B9EA0" :background "#13161C" :overline "#4A5366"))))
 '(org-tag ((t (:foreground "#5B9EA0"))))
 '(org-headline-done ((t (:foreground "#A68EBA" :background "#1A1D24"))))
 '(org-done ((t (:foreground "#C0CBD4"))))
 '(org-todo ((t (:foreground "#D3A05A"))))
 '(org-checkbox ((t (:foreground "#C9A36D" :background "#C37A4E"))))
 '(org-link ((t (:foreground "#5B9EA0" :background "#1A1D24" :underline nil))))
 '(org-verbatim ((t (:foreground "#D3A05A"))))
 '(org-code ((t (:foreground "#D3A05A"))))
 '(org-table ((t (:foreground "#D3A05A" :background "#1F222B"))))
 '(org-date ((t (:foreground "#5B9EA0" :underline t))))
 '(org-archived ((t (:foreground "#4A5366" :background "#1A1D24"))))
 '(org-list-dt ((t (:foreground "#C9A36D"))))
 '(org-drawer ((t (:foreground "#5A8FAA"))))
 '(org-special-keyword ((t (:foreground "#6B7688"))))
 '(org-property-value ((t (:foreground "#4D788F" :background "#1A1D24"))))
 '(org-block ((t (:background "#13161C" :extend t))))
 '(org-block-begin-line ((t (:foreground "#4A5366" :background "#1A1D24" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#6B7688"))))
 '(org-superstar-header-bullet ((t (:foreground "#C9A36D" :background "#1F222B" :overline t))))
 '(org-superstar-item ((t (:foreground "#D3A05A"))))
 '(org-superstar-ordered-item ((t (:foreground "#5B9EA0"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#D3A05A" :height 220 :underline "#5E9A7E"))))
 '(markdown-header-face-2 ((t (:foreground "#D3A05A" :height 180 :underline "#5E9A7E"))))
 '(markdown-header-face-3 ((t (:foreground "#D3A05A" :underline "#5B9EA0"))))
 '(markdown-header-face-4 ((t (:foreground "#D3A05A"))))
 '(markdown-header-face-5 ((t (:foreground "#D3A05A"))))
 '(markdown-header-face-6 ((t (:foreground "#D3A05A"))))
 '(markdown-list-face ((t (:foreground "#D3A05A"))))
 '(markdown-inline-code-face ((t (:foreground "#D3A05A" :background "#1A1D24"))))
 '(markdown-language-keyword-face ((t (:foreground "#5B9EA0"))))
 '(markdown-pre-face ((t (:foreground "#D3A05A"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#4A5366"))))
 '(markdown-header-delimiter-face ((t (:foreground "#7AAAC1"))))
 '(markdown-bold-face ((t (:foreground "#D3A05A" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#D3A05A" :slant italic))))
 '(markdown-link-face ((t (:foreground "#D3A05A"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#5E9A7E"))))
 '(compilation-warning ((t (:foreground "#5E9A7E"))))
 '(compilation-error ((t (:foreground "#C36E5A"))))
 '(compilation-line-number ((t (:foreground "#D3A05A" :underline t))))
 '(compilation-column-number ((t (:foreground "#D3A05A" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#C36E5A"))))
 '(flycheck-fringe-warning ((t (:foreground "#5E9A7E"))))
 '(flycheck-fringe-info ((t (:foreground "#5E9A7E"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#1F222B"))))
 '(lsp-face-highlight-textual ((t (:background "#0B0C16"))))
 '(lsp-face-highlight-write ((t (:background "#0B0C16"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#0B0C16"))))
 '(eglot-inlay-hint-face ((t (:foreground "#D3A05A" :background "#1A1D24" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#D3A05A"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#C0CBD4" :background "#1F222B"))))
 '(company-preview-common ((t (:foreground "#D3A05A" :background "#1F222B"))))
 '(company-preview-search ((t (:foreground "#D3A05A" :background "#1F222B"))))
 '(company-tooltip-common ((t (:foreground "#D3A05A" :background "#1F222B"))))
 '(company-tooltip-common-selection ((t (:foreground "#D3A05A" :background "#1F222B"))))
 '(company-tooltip-annotation ((t (:foreground "#D3A05A" :background "#1F222B"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#D3A05A" :background "#1F222B"))))
 '(company-tooltip-search-selection ((t (:foreground "#D3A05A" :background "#0B0C16"))))
 '(company-tooltip-mouse ((t (:foreground "#D3A05A" :background "#0B0C16"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#4D788F" :background "#1A1D24"))))
 '(magit-branch-current ((t (:foreground "#5E9A7E" :box 1))))
 '(magit-branch-remote ((t (:foreground "#5E9A7E" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#A68EBA"))))
 '(rg-line-number-face ((t (:foreground "#D3A05A"))))

 ;; line numbers
 '(line-number ((t (:foreground "#4A5366" :background "#1A1D24"))))
 '(line-number-current-line ((t (:foreground "#4A5366" :background "#1A1D24"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#476D82"))))
 '(doom-modeline-bar ((t (:background "#1F222B"))))
 '(doom-modeline-bar-inactive ((t (:background "#1A1D24"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#5B9EA0" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#A68EBA"))))
 '(doom-modeline-project-dir ((t (:foreground "#5B9EA0"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#C0CBD4"))))
 '(doom-modeline-urgent ((t (:foreground "#A68EBA"))))
 '(doom-modeline-info ((t (:foreground "#4D788F"))))
 '(doom-modeline-warning ((t (:foreground "#A68EBA"))))
 '(doom-modeline-error ((t (:foreground "#C36E5A"))))
 '(doom-modeline-inactive-bar ((t (:background "#1A1D24"))))
 '(mode-line ((t (:foreground "#202831" :background "#1F222B"))))
 '(mode-line-inactive ((t (:background "#1F222B"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#202831"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#202831"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#6B7688" :background "#1A1D24"))))
 '(tab-bar-tab ((t (:foreground "#5B9EA0" :background "#1A1D24" :box (:line-width 2 :color "#1A1D24")))))
 '(tab-bar-tab-inactive ((t (:foreground "#6B7688" :background "#1A1D24"))))

 ;; misc
 '(secondary-selection ((t (:background "#13161C"))))
 '(shadow ((t (:foreground "#4A5366")))))

(provide-theme 'hackerman)
