
;;; kanagawa-theme.el --- Generated by Book of Colours

(deftheme kanagawa "kanagawa")

(custom-theme-set-faces
 'kanagawa

 ;; common
 '(default ((t (:foreground "#DBD6BA" :background "#1F1F28"))))
 '(cursor ((t (:foreground "#1F1F28" :background "#DBD6BA"))))
 '(region ((t (:foreground "#C7C093" :background "#2D4F67"))))
 '(hl-line ((t (:background "#363646"))))
 '(minibuffer-prompt ((t (:foreground "#727169"))))
 '(link ((t (:foreground "#7FB4C9" :underline t))))
 '(warning ((t (:foreground "#FF9E3B"))))
 '(error ((t (:foreground "#DBD6BA"))))
 '(success ((t (:foreground "#98BB6C"))))
 '(bold ((t (:foreground "#E5C284" :weight bold))))
 '(isearch ((t (:foreground "#C7C093" :background "#2D4F67"))))
 '(lazy-highlight ((t (:foreground "#DBD6BA" :background "#2D4F67"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#FF9E3B" :background "#16161D" :weight bold))))
 '(tooltip ((t (:foreground "#7E9CD7" :background "#1F1F28" :weight bold))))
 '(fringe ((t (:background "#1F1F28"))))
 '(vertical-border ((t (:foreground "#363646"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#E5C284"))))
 '(header-line ((t (:foreground "#727169" :background "#16161D"))))
 '(header-line-highlight ((t (:foreground "#E5C284" :background "#16161D"))))
 '(highlight ((t (:foreground "#DBD6BA" :background "#2D4F67"))))
 '(button ((t (:foreground "#957FB8" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#727169" :background "#1F1F28" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#DBD6BA" :background "#1F1F28" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#DBD6BA"))))
 '(font-lock-type-face ((t (:foreground "#7FB4C9"))))
 '(font-lock-preprocessor-face ((t (:foreground "#E36876"))))
 '(font-lock-operator-face ((t (:foreground "#E5C284"))))
 '(font-lock-string-face ((t (:foreground "#98BB6C"))))
 '(font-lock-variable-name-face ((t (:foreground "#DBD6BA"))))
 '(font-lock-constant-face ((t (:foreground "#98BB6C"))))
 '(font-lock-keyword-face ((t (:foreground "#957FB8"))))
 '(font-lock-warning-face ((t (:foreground "#FF9E3B"))))
 '(font-lock-function-name-face ((t (:foreground "#7E9CD7"))))
 '(font-lock-negation-char-face ((t (:foreground "#E5C284"))))
 '(font-lock-variable-use-face ((t (:foreground "#DBD6BA"))))
 '(font-lock-property-use-face ((t (:foreground "#E5C284"))))
 '(font-lock-number-face ((t (:foreground "#98BB6C"))))
 '(font-lock-bracket-face ((t (:foreground "#9CABC9"))))
 '(font-lock-delimiter-face ((t (:foreground "#727169"))))
 '(font-lock-escape-face ((t (:foreground "#E5C284"))))
 '(show-paren-match ((t (:foreground "#DBD6BA"))))
 '(show-paren-mismatch-face ((t (:foreground "#DBD6BA" :background "#1F1F28"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#727169" :background "#1F1F28" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#98BB6C"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#7E9CD7"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#7FB4C9"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#98BB6C"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#DBD6BA"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#E5C284"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#7E9CD7" :background "#363646" :overline "#727169"))))
 '(org-level-2 ((t (:foreground "#9CABC9" :background "#363646" :overline "#727169"))))
 '(org-level-3 ((t (:foreground "#9CABC9" :background "#363646" :overline "#727169"))))
 '(org-level-4 ((t (:foreground "#7E9CD7" :background "#363646" :overline "#727169"))))
 '(org-level-5 ((t (:foreground "#7E9CD7" :background "#363646" :overline "#727169"))))
 '(org-level-6 ((t (:foreground "#7E9CD7" :background "#363646" :overline "#727169"))))
 '(org-level-7 ((t (:foreground "#7E9CD7" :background "#363646" :overline "#727169"))))
 '(org-tag ((t (:foreground "#DBD6BA"))))
 '(org-headline-done ((t (:foreground "#957FB8" :background "#1F1F28"))))
 '(org-done ((t (:foreground "#DBD6BA"))))
 '(org-todo ((t (:foreground "#FF9E3B"))))
 '(org-checkbox ((t (:foreground "#DBD6BA" :background "#223249"))))
 '(org-link ((t (:foreground "#7FB4C9" :background "#1F1F28" :underline nil))))
 '(org-verbatim ((t (:foreground "#E5C284"))))
 '(org-code ((t (:foreground "#E5C284"))))
 '(org-table ((t (:foreground "#E5C284" :background "#16161D"))))
 '(org-date ((t (:foreground "#9CABC9" :underline t))))
 '(org-archived ((t (:foreground "#727169" :background "#1F1F28"))))
 '(org-list-dt ((t (:foreground "#DBD6BA"))))
 '(org-drawer ((t (:foreground "#E36876"))))
 '(org-special-keyword ((t (:foreground "#938AA9"))))
 '(org-property-value ((t (:foreground "#E5C284" :background "#1F1F28"))))
 '(org-block ((t (:background "#363646" :extend t))))
 '(org-block-begin-line ((t (:foreground "#727169" :background "#1F1F28" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#727169"))))
 '(org-superstar-header-bullet ((t (:foreground "#DBD6BA" :background "#16161D" :overline t))))
 '(org-superstar-item ((t (:foreground "#FF9E3B"))))
 '(org-superstar-ordered-item ((t (:foreground "#E5C284"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#E5C284" :height 220 :underline "#7E9CD7"))))
 '(markdown-header-face-2 ((t (:foreground "#E5C284" :height 180 :underline "#7E9CD7"))))
 '(markdown-header-face-3 ((t (:foreground "#E5C284" :underline "#DBD6BA"))))
 '(markdown-header-face-4 ((t (:foreground "#E5C284"))))
 '(markdown-header-face-5 ((t (:foreground "#E5C284"))))
 '(markdown-header-face-6 ((t (:foreground "#E5C284"))))
 '(markdown-list-face ((t (:foreground "#FF9E3B"))))
 '(markdown-inline-code-face ((t (:foreground "#E5C284" :background "#1F1F28"))))
 '(markdown-language-keyword-face ((t (:foreground "#DBD6BA"))))
 '(markdown-pre-face ((t (:foreground "#E5C284"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#727169"))))
 '(markdown-header-delimiter-face ((t (:foreground "#9CABC9"))))
 '(markdown-bold-face ((t (:foreground "#E5C284" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#E5C284" :slant italic))))
 '(markdown-link-face ((t (:foreground "#E5C284"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#7E9CD7"))))
 '(compilation-warning ((t (:foreground "#7E9CD7"))))
 '(compilation-error ((t (:foreground "#DBD6BA"))))
 '(compilation-line-number ((t (:foreground "#E5C284" :underline t))))
 '(compilation-column-number ((t (:foreground "#E5C284" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#DBD6BA"))))
 '(flycheck-fringe-warning ((t (:foreground "#7E9CD7"))))
 '(flycheck-fringe-info ((t (:foreground "#7E9CD7"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#16161D"))))
 '(lsp-face-highlight-textual ((t (:background "#2D4F67"))))
 '(lsp-face-highlight-write ((t (:background "#2D4F67"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#2D4F67"))))
 '(eglot-inlay-hint-face ((t (:foreground "#E5C284" :background "#1F1F28" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#E5C284"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#DBD6BA" :background "#16161D"))))
 '(company-preview-common ((t (:foreground "#E5C284" :background "#16161D"))))
 '(company-preview-search ((t (:foreground "#E5C284" :background "#16161D"))))
 '(company-tooltip-common ((t (:foreground "#E5C284" :background "#16161D"))))
 '(company-tooltip-common-selection ((t (:foreground "#E5C284" :background "#16161D"))))
 '(company-tooltip-annotation ((t (:foreground "#E5C284" :background "#16161D"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#E5C284" :background "#16161D"))))
 '(company-tooltip-search-selection ((t (:foreground "#E5C284" :background "#2D4F67"))))
 '(company-tooltip-mouse ((t (:foreground "#E5C284" :background "#2D4F67"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#E5C284" :background "#1F1F28"))))
 '(magit-branch-current ((t (:foreground "#7E9CD7" :box 1))))
 '(magit-branch-remote ((t (:foreground "#7E9CD7" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#957FB8"))))
 '(rg-line-number-face ((t (:foreground "#E5C284"))))

 ;; line numbers
 '(line-number ((t (:foreground "#727169" :background "#1F1F28"))))
 '(line-number-current-line ((t (:foreground "#727169" :background "#1F1F28"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#727169"))))
 '(doom-modeline-bar ((t (:background "#16161D"))))
 '(doom-modeline-bar-inactive ((t (:background "#1F1F28"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#E5C284" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#957FB8"))))
 '(doom-modeline-project-dir ((t (:foreground "#DBD6BA"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#DBD6BA"))))
 '(doom-modeline-urgent ((t (:foreground "#957FB8"))))
 '(doom-modeline-info ((t (:foreground "#E5C284"))))
 '(doom-modeline-warning ((t (:foreground "#957FB8"))))
 '(doom-modeline-error ((t (:foreground "#DBD6BA"))))
 '(doom-modeline-inactive-bar ((t (:background "#1F1F28"))))
 '(mode-line ((t (:foreground "#2A2A37" :background "#16161D"))))
 '(mode-line-inactive ((t (:background "#16161D"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#2A2A37"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#2A2A37"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#938AA9" :background "#1F1F28"))))
 '(tab-bar-tab ((t (:foreground "#9CABC9" :background "#1F1F28" :box (:line-width 2 :color "#1F1F28")))))
 '(tab-bar-tab-inactive ((t (:foreground "#727169" :background "#1F1F28"))))

 ;; misc
 '(secondary-selection ((t (:background "#363646"))))
 '(shadow ((t (:foreground "#727169")))))

(provide-theme 'kanagawa)
