
;;; kanso-theme.el --- Generated by Book of Colours

(deftheme kanso "kanso")

(custom-theme-set-faces
 'kanso

 ;; common
 '(default ((t (:foreground "#C4C8C6" :background "#090E13"))))
 '(cursor ((t (:foreground "#14171D" :background "#E5C284"))))
 '(region ((t (:foreground "#C4C8C6" :background "#393B44"))))
 '(hl-line ((t (:background "#22262D"))))
 '(minibuffer-prompt ((t (:foreground "#75797F"))))
 '(link ((t (:foreground "#7FB4C9" :underline t))))
 '(warning ((t (:foreground "#DBA561"))))
 '(error ((t (:foreground "#C24043"))))
 '(success ((t (:foreground "#98BB6C"))))
 '(bold ((t (:foreground "#C3B28A" :weight bold))))
 '(isearch ((t (:foreground "#C4C8C6" :background "#393B44"))))
 '(lazy-highlight ((t (:foreground "#8992A7" :background "#393B44"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#DBA561" :background "#090E13" :weight bold))))
 '(tooltip ((t (:foreground "#76946A" :background "#22262D" :weight bold))))
 '(fringe ((t (:background "#090E13"))))
 '(vertical-border ((t (:foreground "#223249"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#A4A7A4"))))
 '(header-line ((t (:foreground "#75797F" :background "#090E13"))))
 '(header-line-highlight ((t (:foreground "#C3B28A" :background "#090E13"))))
 '(highlight ((t (:foreground "#8992A7" :background "#393B44"))))
 '(button ((t (:foreground "#938AA9" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#75797F" :background "#22262D" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#C4C8C6" :background "#22262D" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#8992A7"))))
 '(font-lock-type-face ((t (:foreground "#8EA4A2"))))
 '(font-lock-preprocessor-face ((t (:foreground "#938AA9"))))
 '(font-lock-operator-face ((t (:foreground "#7FB4C9"))))
 '(font-lock-string-face ((t (:foreground "#8A9A7B"))))
 '(font-lock-variable-name-face ((t (:foreground "#C4C8C6"))))
 '(font-lock-constant-face ((t (:foreground "#87A987"))))
 '(font-lock-keyword-face ((t (:foreground "#938AA9"))))
 '(font-lock-warning-face ((t (:foreground "#DBA561"))))
 '(font-lock-function-name-face ((t (:foreground "#8BA4B0"))))
 '(font-lock-negation-char-face ((t (:foreground "#7FB4C9"))))
 '(font-lock-variable-use-face ((t (:foreground "#A4A7A4"))))
 '(font-lock-property-use-face ((t (:foreground "#C4C8C6"))))
 '(font-lock-number-face ((t (:foreground "#938AA9"))))
 '(font-lock-bracket-face ((t (:foreground "#909398"))))
 '(font-lock-delimiter-face ((t (:foreground "#75797F"))))
 '(font-lock-escape-face ((t (:foreground "#C3B28A"))))
 '(show-paren-match ((t (:foreground "#F1F0EE"))))
 '(show-paren-mismatch-face ((t (:foreground "#C24043" :background "#090E13"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#75797F" :background "#22262D" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#8A9A7B"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#8BA4B0"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#8EA4A2"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#87A987"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#A4A7A4"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#C4C8C6"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#76946A" :background "#22262D" :overline "#75797F"))))
 '(org-level-2 ((t (:foreground "#7AA89F" :background "#22262D" :overline "#75797F"))))
 '(org-level-3 ((t (:foreground "#7AA89F" :background "#22262D" :overline "#75797F"))))
 '(org-level-4 ((t (:foreground "#8BA4B0" :background "#22262D" :overline "#75797F"))))
 '(org-level-5 ((t (:foreground "#8BA4B0" :background "#22262D" :overline "#75797F"))))
 '(org-level-6 ((t (:foreground "#8BA4B0" :background "#22262D" :overline "#75797F"))))
 '(org-level-7 ((t (:foreground "#8BA4B0" :background "#22262D" :overline "#75797F"))))
 '(org-tag ((t (:foreground "#C4C8C6"))))
 '(org-headline-done ((t (:foreground "#938AA9" :background "#22262D"))))
 '(org-done ((t (:foreground "#C4C8C6"))))
 '(org-todo ((t (:foreground "#DBA561"))))
 '(org-checkbox ((t (:foreground "#8992A7" :background "#090E13"))))
 '(org-link ((t (:foreground "#7FB4C9" :background "#090E13" :underline nil))))
 '(org-verbatim ((t (:foreground "#C3B28A"))))
 '(org-code ((t (:foreground "#C3B28A"))))
 '(org-table ((t (:foreground "#C3B28A" :background "#090E13"))))
 '(org-date ((t (:foreground "#7AA89F" :underline t))))
 '(org-archived ((t (:foreground "#75797F" :background "#22262D"))))
 '(org-list-dt ((t (:foreground "#8992A7"))))
 '(org-drawer ((t (:foreground "#938AA9"))))
 '(org-special-keyword ((t (:foreground "#75797F"))))
 '(org-property-value ((t (:foreground "#A4A7A4" :background "#090E13"))))
 '(org-block ((t (:background "#22262D" :extend t))))
 '(org-block-begin-line ((t (:foreground "#75797F" :background "#090E13" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#75797F"))))
 '(org-superstar-header-bullet ((t (:foreground "#8992A7" :background "#090E13" :overline t))))
 '(org-superstar-item ((t (:foreground "#DBA561"))))
 '(org-superstar-ordered-item ((t (:foreground "#C4C8C6"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#C3B28A" :height 220 :underline "#76946A"))))
 '(markdown-header-face-2 ((t (:foreground "#C3B28A" :height 180 :underline "#76946A"))))
 '(markdown-header-face-3 ((t (:foreground "#C3B28A" :underline "#C4C8C6"))))
 '(markdown-header-face-4 ((t (:foreground "#C3B28A"))))
 '(markdown-header-face-5 ((t (:foreground "#C3B28A"))))
 '(markdown-header-face-6 ((t (:foreground "#C3B28A"))))
 '(markdown-list-face ((t (:foreground "#DBA561"))))
 '(markdown-inline-code-face ((t (:foreground "#C3B28A" :background "#22262D"))))
 '(markdown-language-keyword-face ((t (:foreground "#C4C8C6"))))
 '(markdown-pre-face ((t (:foreground "#C3B28A"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#75797F"))))
 '(markdown-header-delimiter-face ((t (:foreground "#909398"))))
 '(markdown-bold-face ((t (:foreground "#C3B28A" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#C3B28A" :slant italic))))
 '(markdown-link-face ((t (:foreground "#C3B28A"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#76946A"))))
 '(compilation-warning ((t (:foreground "#76946A"))))
 '(compilation-error ((t (:foreground "#C24043"))))
 '(compilation-line-number ((t (:foreground "#C3B28A" :underline t))))
 '(compilation-column-number ((t (:foreground "#C3B28A" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#C24043"))))
 '(flycheck-fringe-warning ((t (:foreground "#76946A"))))
 '(flycheck-fringe-info ((t (:foreground "#76946A"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#090E13"))))
 '(lsp-face-highlight-textual ((t (:background "#393B44"))))
 '(lsp-face-highlight-write ((t (:background "#393B44"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#393B44"))))
 '(eglot-inlay-hint-face ((t (:foreground "#C3B28A" :background "#22262D" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#C3B28A"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#A4A7A4" :background "#090E13"))))
 '(company-preview-common ((t (:foreground "#C3B28A" :background "#090E13"))))
 '(company-preview-search ((t (:foreground "#C3B28A" :background "#090E13"))))
 '(company-tooltip-common ((t (:foreground "#C3B28A" :background "#090E13"))))
 '(company-tooltip-common-selection ((t (:foreground "#C3B28A" :background "#090E13"))))
 '(company-tooltip-annotation ((t (:foreground "#C3B28A" :background "#090E13"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#C3B28A" :background "#090E13"))))
 '(company-tooltip-search-selection ((t (:foreground "#C3B28A" :background "#393B44"))))
 '(company-tooltip-mouse ((t (:foreground "#C3B28A" :background "#393B44"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#C4C8C6" :background "#22262D"))))
 '(magit-branch-current ((t (:foreground "#76946A" :box 1))))
 '(magit-branch-remote ((t (:foreground "#76946A" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#938AA9"))))
 '(rg-line-number-face ((t (:foreground "#C3B28A"))))

 ;; line numbers
 '(line-number ((t (:foreground "#75797F" :background "#090E13"))))
 '(line-number-current-line ((t (:foreground "#75797F" :background "#090E13"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#5C6066"))))
 '(doom-modeline-bar ((t (:background "#090E13"))))
 '(doom-modeline-bar-inactive ((t (:background "#090E13"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#C4C8C6" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#938AA9"))))
 '(doom-modeline-project-dir ((t (:foreground "#A4A7A4"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#C4C8C6"))))
 '(doom-modeline-urgent ((t (:foreground "#938AA9"))))
 '(doom-modeline-info ((t (:foreground "#A4A7A4"))))
 '(doom-modeline-warning ((t (:foreground "#938AA9"))))
 '(doom-modeline-error ((t (:foreground "#C24043"))))
 '(doom-modeline-inactive-bar ((t (:background "#090E13"))))
 '(mode-line ((t (:foreground "#22262D" :background "#090E13"))))
 '(mode-line-inactive ((t (:background "#090E13"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#22262D"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#22262D"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#75797F" :background "#090E13"))))
 '(tab-bar-tab ((t (:foreground "#7AA89F" :background "#090E13" :box (:line-width 2 :color "#090E13")))))
 '(tab-bar-tab-inactive ((t (:foreground "#75797F" :background "#090E13"))))

 ;; misc
 '(secondary-selection ((t (:background "#22262D"))))
 '(shadow ((t (:foreground "#75797F")))))

(provide-theme 'kanso)
