
;;; last-horizon-theme.el --- Generated by Book of Colours

(deftheme last-horizon "last-horizon")

(custom-theme-set-faces
 'last-horizon

 ;; common
 '(default ((t (:foreground "#F9FBFA" :background "#0C0B0C"))))
 '(cursor ((t (:foreground "#0C0B0C" :background "#F9FBFA"))))
 '(region ((t (:foreground "#E1DCDB" :background "#584E51"))))
 '(hl-line ((t (:background "#171516"))))
 '(minibuffer-prompt ((t (:foreground "#584E51"))))
 '(link ((t (:foreground "#A5A0B6" :underline t))))
 '(warning ((t (:foreground "#B59790"))))
 '(error ((t (:foreground "#C28B7B"))))
 '(success ((t (:foreground "#F9FBFA"))))
 '(bold ((t (:foreground "#C3D7E1" :weight bold))))
 '(isearch ((t (:foreground "#E1DCDB" :background "#584E51"))))
 '(lazy-highlight ((t (:foreground "#B59790" :background "#584E51"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#B59790" :background "#1F1C21" :weight bold))))
 '(tooltip ((t (:foreground "#C28B7B" :background "#0C0B0C" :weight bold))))
 '(fringe ((t (:background "#0C0B0C"))))
 '(vertical-border ((t (:foreground "#3A2B28"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#F9FBFA"))))
 '(header-line ((t (:foreground "#584E51" :background "#1F1C21"))))
 '(header-line-highlight ((t (:foreground "#C3D7E1" :background "#1F1C21"))))
 '(highlight ((t (:foreground "#F9FBFA" :background "#584E51"))))
 '(button ((t (:foreground "#A5A0B6" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#584E51" :background "#0C0B0C" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#F9FBFA" :background "#0C0B0C" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#B59790"))))
 '(font-lock-type-face ((t (:foreground "#C3D7E1"))))
 '(font-lock-preprocessor-face ((t (:foreground "#937B76"))))
 '(font-lock-operator-face ((t (:foreground "#C3D7E1"))))
 '(font-lock-string-face ((t (:foreground "#87A9B0"))))
 '(font-lock-variable-name-face ((t (:foreground "#A5A0B6"))))
 '(font-lock-constant-face ((t (:foreground "#B59790"))))
 '(font-lock-keyword-face ((t (:foreground "#A5A0B6"))))
 '(font-lock-warning-face ((t (:foreground "#B59790"))))
 '(font-lock-function-name-face ((t (:foreground "#B59790"))))
 '(font-lock-negation-char-face ((t (:foreground "#C3D7E1"))))
 '(font-lock-variable-use-face ((t (:foreground "#F9FBFA"))))
 '(font-lock-property-use-face ((t (:foreground "#F9FBFA"))))
 '(font-lock-number-face ((t (:foreground "#B59790"))))
 '(font-lock-bracket-face ((t (:foreground "#F9FBFA"))))
 '(font-lock-delimiter-face ((t (:foreground "#584E51"))))
 '(font-lock-escape-face ((t (:foreground "#C3D7E1"))))
 '(show-paren-match ((t (:foreground "#F9FBFA"))))
 '(show-paren-mismatch-face ((t (:foreground "#C28B7B" :background "#0C0B0C"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#584E51" :background "#0C0B0C" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#87A9B0"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#B59790"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#C3D7E1"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#B59790"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#F9FBFA"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#A5A0B6"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#C28B7B" :background "#171516" :overline "#584E51"))))
 '(org-level-2 ((t (:foreground "#B59790" :background "#171516" :overline "#584E51"))))
 '(org-level-3 ((t (:foreground "#B59790" :background "#171516" :overline "#584E51"))))
 '(org-level-4 ((t (:foreground "#B59790" :background "#171516" :overline "#584E51"))))
 '(org-level-5 ((t (:foreground "#B59790" :background "#171516" :overline "#584E51"))))
 '(org-level-6 ((t (:foreground "#B59790" :background "#171516" :overline "#584E51"))))
 '(org-level-7 ((t (:foreground "#B59790" :background "#171516" :overline "#584E51"))))
 '(org-tag ((t (:foreground "#A5A0B6"))))
 '(org-headline-done ((t (:foreground "#A5A0B6" :background "#0C0B0C"))))
 '(org-done ((t (:foreground "#F9FBFA"))))
 '(org-todo ((t (:foreground "#B59790"))))
 '(org-checkbox ((t (:foreground "#F9FBFA" :background "#171516"))))
 '(org-link ((t (:foreground "#A5A0B6" :background "#0C0B0C" :underline nil))))
 '(org-verbatim ((t (:foreground "#C3D7E1"))))
 '(org-code ((t (:foreground "#C3D7E1"))))
 '(org-table ((t (:foreground "#C3D7E1" :background "#1F1C21"))))
 '(org-date ((t (:foreground "#B59790" :underline t))))
 '(org-archived ((t (:foreground "#584E51" :background "#0C0B0C"))))
 '(org-list-dt ((t (:foreground "#B59790"))))
 '(org-drawer ((t (:foreground "#937B76"))))
 '(org-special-keyword ((t (:foreground "#584E51"))))
 '(org-property-value ((t (:foreground "#F9FBFA" :background "#0C0B0C"))))
 '(org-block ((t (:background "#171516" :extend t))))
 '(org-block-begin-line ((t (:foreground "#584E51" :background "#0C0B0C" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#584E51"))))
 '(org-superstar-header-bullet ((t (:foreground "#F9FBFA" :background "#1F1C21" :overline t))))
 '(org-superstar-item ((t (:foreground "#B59790"))))
 '(org-superstar-ordered-item ((t (:foreground "#A5A0B6"))))
 '(org-hide ((t (:foreground "#0C0B0C"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#C28B7B" :height 220 :underline "#C28B7B"))))
 '(markdown-header-face-2 ((t (:foreground "#B59790" :height 180 :underline "#C28B7B"))))
 '(markdown-header-face-3 ((t (:foreground "#B59790" :underline "#F9FBFA"))))
 '(markdown-header-face-4 ((t (:foreground "#C3D7E1"))))
 '(markdown-header-face-5 ((t (:foreground "#C3D7E1"))))
 '(markdown-header-face-6 ((t (:foreground "#C3D7E1"))))
 '(markdown-list-face ((t (:foreground "#B59790"))))
 '(markdown-inline-code-face ((t (:foreground "#C3D7E1" :background "#0C0B0C"))))
 '(markdown-language-keyword-face ((t (:foreground "#A5A0B6"))))
 '(markdown-pre-face ((t (:foreground "#C3D7E1"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#584E51"))))
 '(markdown-header-delimiter-face ((t (:foreground "#F9FBFA"))))
 '(markdown-bold-face ((t (:foreground "#C3D7E1" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#C3D7E1" :slant italic))))
 '(markdown-link-face ((t (:foreground "#C3D7E1"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#C28B7B"))))
 '(compilation-warning ((t (:foreground "#C28B7B"))))
 '(compilation-error ((t (:foreground "#C28B7B"))))
 '(compilation-line-number ((t (:foreground "#C3D7E1" :underline t))))
 '(compilation-column-number ((t (:foreground "#C3D7E1" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#C28B7B"))))
 '(flycheck-fringe-warning ((t (:foreground "#C28B7B"))))
 '(flycheck-fringe-info ((t (:foreground "#C28B7B"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#1F1C21"))))
 '(lsp-face-highlight-textual ((t (:background "#584E51"))))
 '(lsp-face-highlight-write ((t (:background "#584E51"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#584E51"))))
 '(eglot-inlay-hint-face ((t (:foreground "#C3D7E1" :background "#0C0B0C" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#C3D7E1"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#F9FBFA" :background "#1F1C21"))))
 '(company-preview-common ((t (:foreground "#C3D7E1" :background "#1F1C21"))))
 '(company-preview-search ((t (:foreground "#C3D7E1" :background "#1F1C21"))))
 '(company-tooltip-common ((t (:foreground "#C3D7E1" :background "#1F1C21"))))
 '(company-tooltip-common-selection ((t (:foreground "#C3D7E1" :background "#1F1C21"))))
 '(company-tooltip-annotation ((t (:foreground "#C3D7E1" :background "#1F1C21"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#C3D7E1" :background "#1F1C21"))))
 '(company-tooltip-search-selection ((t (:foreground "#C3D7E1" :background "#584E51"))))
 '(company-tooltip-mouse ((t (:foreground "#C3D7E1" :background "#584E51"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#F9FBFA" :background "#0C0B0C"))))
 '(magit-branch-current ((t (:foreground "#C28B7B" :box 1))))
 '(magit-branch-remote ((t (:foreground "#C28B7B" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#A5A0B6"))))
 '(rg-line-number-face ((t (:foreground "#C3D7E1"))))

 ;; line numbers
 '(line-number ((t (:foreground "#584E51" :background "#0C0B0C"))))
 '(line-number-current-line ((t (:foreground "#584E51" :background "#0C0B0C"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#6B5E73"))))
 '(doom-modeline-bar ((t (:background "#1F1C21"))))
 '(doom-modeline-bar-inactive ((t (:background "#0C0B0C"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#A5A0B6" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#A5A0B6"))))
 '(doom-modeline-project-dir ((t (:foreground "#F9FBFA"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#F9FBFA"))))
 '(doom-modeline-urgent ((t (:foreground "#A5A0B6"))))
 '(doom-modeline-info ((t (:foreground "#F9FBFA"))))
 '(doom-modeline-warning ((t (:foreground "#A5A0B6"))))
 '(doom-modeline-error ((t (:foreground "#C28B7B"))))
 '(doom-modeline-inactive-bar ((t (:background "#0C0B0C"))))
 '(mode-line ((t (:foreground "#242324" :background "#1F1C21"))))
 '(mode-line-inactive ((t (:background "#1F1C21"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#242324"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#242324"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#584E51" :background "#0C0B0C"))))
 '(tab-bar-tab ((t (:foreground "#B59790" :background "#0C0B0C" :box (:line-width 2 :color "#0C0B0C")))))
 '(tab-bar-tab-inactive ((t (:foreground "#584E51" :background "#0C0B0C"))))

 ;; misc
 '(secondary-selection ((t (:background "#171516"))))
 '(shadow ((t (:foreground "#584E51")))))

(provide-theme 'last-horizon)
