
;;; lumon-theme.el --- Generated by Book of Colours

(deftheme lumon "lumon")

(custom-theme-set-faces
 'lumon

 ;; common
 '(default ((t (:foreground "#D5E1ED" :background "#16242D"))))
 '(cursor ((t (:foreground "#1B2D40" :background "#F1FBFF"))))
 '(region ((t (:foreground "#4D9ED2" :background "#1B2D40"))))
 '(hl-line ((t (:background "#16242D"))))
 '(minibuffer-prompt ((t (:foreground "#6E99B5"))))
 '(link ((t (:foreground "#B5DDEE" :underline t))))
 '(warning ((t (:foreground "#B5DDEE"))))
 '(error ((t (:foreground "#B5DDEE"))))
 '(success ((t (:foreground "#B5DDEE"))))
 '(bold ((t (:foreground "#92C6E6" :weight bold))))
 '(isearch ((t (:foreground "#4D9ED2" :background "#1B2D40"))))
 '(lazy-highlight ((t (:foreground "#C6D1DD" :background "#1B2D40"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#B5DDEE" :background "#16242D" :weight bold))))
 '(tooltip ((t (:foreground "#92C6E6" :background "#16242D" :weight bold))))
 '(fringe ((t (:background "#16242D"))))
 '(vertical-border ((t (:foreground "#16242D"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#D5E1ED"))))
 '(header-line ((t (:foreground "#6E99B5" :background "#16242D"))))
 '(header-line-highlight ((t (:foreground "#B5DDEE" :background "#16242D"))))
 '(highlight ((t (:foreground "#C6D1DD" :background "#1B2D40"))))
 '(button ((t (:foreground "#B5DDEE" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#6E99B5" :background "#16242D" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#D5E1ED" :background "#16242D" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#C6D1DD"))))
 '(font-lock-type-face ((t (:foreground "#86B6D9"))))
 '(font-lock-preprocessor-face ((t (:foreground "#B5DDEE"))))
 '(font-lock-operator-face ((t (:foreground "#B5DDEE"))))
 '(font-lock-string-face ((t (:foreground "#B5DDEE"))))
 '(font-lock-variable-name-face ((t (:foreground "#9FCEE8"))))
 '(font-lock-constant-face ((t (:foreground "#B5DDEE"))))
 '(font-lock-keyword-face ((t (:foreground "#B5DDEE"))))
 '(font-lock-warning-face ((t (:foreground "#B5DDEE"))))
 '(font-lock-function-name-face ((t (:foreground "#9FCEE8"))))
 '(font-lock-negation-char-face ((t (:foreground "#B5DDEE"))))
 '(font-lock-variable-use-face ((t (:foreground "#D5E1ED"))))
 '(font-lock-property-use-face ((t (:foreground "#D5E1ED"))))
 '(font-lock-number-face ((t (:foreground "#B5DDEE"))))
 '(font-lock-bracket-face ((t (:foreground "#C6D1DD"))))
 '(font-lock-delimiter-face ((t (:foreground "#8FB9DB"))))
 '(font-lock-escape-face ((t (:foreground "#92C6E6"))))
 '(show-paren-match ((t (:foreground "#C6D1DD"))))
 '(show-paren-mismatch-face ((t (:foreground "#B5DDEE" :background "#16242D"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#6E99B5" :background "#16242D" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#B5DDEE"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#9FCEE8"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#86B6D9"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#B5DDEE"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#D5E1ED"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#9FCEE8"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#92C6E6" :background "#16242D" :overline "#6E99B5"))))
 '(org-level-2 ((t (:foreground "#C6D1DD" :background "#16242D" :overline "#6E99B5"))))
 '(org-level-3 ((t (:foreground "#C6D1DD" :background "#16242D" :overline "#6E99B5"))))
 '(org-level-4 ((t (:foreground "#92C6E6" :background "#16242D" :overline "#6E99B5"))))
 '(org-level-5 ((t (:foreground "#92C6E6" :background "#16242D" :overline "#6E99B5"))))
 '(org-level-6 ((t (:foreground "#92C6E6" :background "#16242D" :overline "#6E99B5"))))
 '(org-level-7 ((t (:foreground "#92C6E6" :background "#16242D" :overline "#6E99B5"))))
 '(org-tag ((t (:foreground "#9FCEE8"))))
 '(org-headline-done ((t (:foreground "#B5DDEE" :background "#16242D"))))
 '(org-done ((t (:foreground "#D5E1ED"))))
 '(org-todo ((t (:foreground "#B5DDEE"))))
 '(org-checkbox ((t (:foreground "#C6D1DD" :background "#8FB9DB"))))
 '(org-link ((t (:foreground "#B5DDEE" :background "#16242D" :underline nil))))
 '(org-verbatim ((t (:foreground "#B5DDEE"))))
 '(org-code ((t (:foreground "#92C6E6"))))
 '(org-table ((t (:foreground "#B5DDEE" :background "#16242D"))))
 '(org-date ((t (:foreground "#C6D1DD" :underline t))))
 '(org-archived ((t (:foreground "#6E99B5" :background "#16242D"))))
 '(org-list-dt ((t (:foreground "#C6D1DD"))))
 '(org-drawer ((t (:foreground "#B5DDEE"))))
 '(org-special-keyword ((t (:foreground "#8FB9DB"))))
 '(org-property-value ((t (:foreground "#D5E1ED" :background "#16242D"))))
 '(org-block ((t (:background "#16242D" :extend t))))
 '(org-block-begin-line ((t (:foreground "#6E99B5" :background "#16242D" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#8FB9DB"))))
 '(org-superstar-header-bullet ((t (:foreground "#C6D1DD" :background "#16242D" :overline t))))
 '(org-superstar-item ((t (:foreground "#B5DDEE"))))
 '(org-superstar-ordered-item ((t (:foreground "#9FCEE8"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#92C6E6" :height 220 :underline "#92C6E6"))))
 '(markdown-header-face-2 ((t (:foreground "#B5DDEE" :height 180 :underline "#92C6E6"))))
 '(markdown-header-face-3 ((t (:foreground "#92C6E6" :underline "#D5E1ED"))))
 '(markdown-header-face-4 ((t (:foreground "#B5DDEE"))))
 '(markdown-header-face-5 ((t (:foreground "#92C6E6"))))
 '(markdown-header-face-6 ((t (:foreground "#B5DDEE"))))
 '(markdown-list-face ((t (:foreground "#B5DDEE"))))
 '(markdown-inline-code-face ((t (:foreground "#92C6E6" :background "#16242D"))))
 '(markdown-language-keyword-face ((t (:foreground "#9FCEE8"))))
 '(markdown-pre-face ((t (:foreground "#B5DDEE"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#6E99B5"))))
 '(markdown-header-delimiter-face ((t (:foreground "#C6D1DD"))))
 '(markdown-bold-face ((t (:foreground "#92C6E6" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#B5DDEE" :slant italic))))
 '(markdown-link-face ((t (:foreground "#92C6E6"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#92C6E6"))))
 '(compilation-warning ((t (:foreground "#92C6E6"))))
 '(compilation-error ((t (:foreground "#B5DDEE"))))
 '(compilation-line-number ((t (:foreground "#B5DDEE" :underline t))))
 '(compilation-column-number ((t (:foreground "#92C6E6" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#B5DDEE"))))
 '(flycheck-fringe-warning ((t (:foreground "#92C6E6"))))
 '(flycheck-fringe-info ((t (:foreground "#92C6E6"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#16242D"))))
 '(lsp-face-highlight-textual ((t (:background "#1B2D40"))))
 '(lsp-face-highlight-write ((t (:background "#1B2D40"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#1B2D40"))))
 '(eglot-inlay-hint-face ((t (:foreground "#B5DDEE" :background "#16242D" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#92C6E6"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#D5E1ED" :background "#16242D"))))
 '(company-preview-common ((t (:foreground "#B5DDEE" :background "#16242D"))))
 '(company-preview-search ((t (:foreground "#92C6E6" :background "#16242D"))))
 '(company-tooltip-common ((t (:foreground "#B5DDEE" :background "#16242D"))))
 '(company-tooltip-common-selection ((t (:foreground "#92C6E6" :background "#16242D"))))
 '(company-tooltip-annotation ((t (:foreground "#B5DDEE" :background "#16242D"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#92C6E6" :background "#16242D"))))
 '(company-tooltip-search-selection ((t (:foreground "#B5DDEE" :background "#1B2D40"))))
 '(company-tooltip-mouse ((t (:foreground "#92C6E6" :background "#1B2D40"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#D5E1ED" :background "#16242D"))))
 '(magit-branch-current ((t (:foreground "#92C6E6" :box 1))))
 '(magit-branch-remote ((t (:foreground "#92C6E6" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#B5DDEE"))))
 '(rg-line-number-face ((t (:foreground "#B5DDEE"))))

 ;; line numbers
 '(line-number ((t (:foreground "#6E99B5" :background "#16242D"))))
 '(line-number-current-line ((t (:foreground "#6E99B5" :background "#16242D"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#6E99B5"))))
 '(doom-modeline-bar ((t (:background "#16242D"))))
 '(doom-modeline-bar-inactive ((t (:background "#16242D"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#9FCEE8" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#B5DDEE"))))
 '(doom-modeline-project-dir ((t (:foreground "#D5E1ED"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#D5E1ED"))))
 '(doom-modeline-urgent ((t (:foreground "#B5DDEE"))))
 '(doom-modeline-info ((t (:foreground "#D5E1ED"))))
 '(doom-modeline-warning ((t (:foreground "#B5DDEE"))))
 '(doom-modeline-error ((t (:foreground "#B5DDEE"))))
 '(doom-modeline-inactive-bar ((t (:background "#16242D"))))
 '(mode-line ((t (:foreground "#16242D" :background "#16242D"))))
 '(mode-line-inactive ((t (:background "#16242D"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#16242D"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#16242D"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#8FB9DB" :background "#16242D"))))
 '(tab-bar-tab ((t (:foreground "#C6D1DD" :background "#16242D" :box (:line-width 2 :color "#16242D")))))
 '(tab-bar-tab-inactive ((t (:foreground "#8FB9DB" :background "#16242D"))))

 ;; misc
 '(secondary-selection ((t (:background "#16242D"))))
 '(shadow ((t (:foreground "#6E99B5")))))

(provide-theme 'lumon)
