
;;; lupine-theme.el --- Generated by Book of Colours

(deftheme lupine "lupine")

(custom-theme-set-faces
 'lupine

 ;; common
 '(default ((t (:foreground "#212121" :background "#F9F9F9"))))
 '(cursor ((t (:foreground "#F9F9F9" :background "#000000"))))
 '(region ((t (:foreground "#000000" :background "#CFCFCF"))))
 '(hl-line ((t (:background "#F4F4F4"))))
 '(minibuffer-prompt ((t (:foreground "#9E9E9E"))))
 '(link ((t (:foreground "#0C67DD" :underline t))))
 '(warning ((t (:foreground "#212121"))))
 '(error ((t (:foreground "#212121"))))
 '(success ((t (:foreground "#212121"))))
 '(bold ((t (:foreground "#4A2FCF" :weight bold))))
 '(isearch ((t (:foreground "#000000" :background "#CFCFCF"))))
 '(lazy-highlight ((t (:foreground "#3264EA" :background "#CFCFCF"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#212121" :background "#EBEBEB" :weight bold))))
 '(tooltip ((t (:foreground "#3264EA" :background "#F9F9F9" :weight bold))))
 '(fringe ((t (:background "#F9F9F9"))))
 '(vertical-border ((t (:foreground "#9E9E9E"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#212121"))))
 '(header-line ((t (:foreground "#9E9E9E" :background "#EBEBEB"))))
 '(header-line-highlight ((t (:foreground "#4A2FCF" :background "#EBEBEB"))))
 '(highlight ((t (:foreground "#212121" :background "#CFCFCF"))))
 '(button ((t (:foreground "#B363FF" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#9E9E9E" :background "#F9F9F9" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#212121" :background "#F9F9F9" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#3264EA"))))
 '(font-lock-type-face ((t (:foreground "#026FDD"))))
 '(font-lock-preprocessor-face ((t (:foreground "#5482FF"))))
 '(font-lock-operator-face ((t (:foreground "#085FB8"))))
 '(font-lock-string-face ((t (:foreground "#212121"))))
 '(font-lock-variable-name-face ((t (:foreground "#212121"))))
 '(font-lock-constant-face ((t (:foreground "#212121"))))
 '(font-lock-keyword-face ((t (:foreground "#B363FF"))))
 '(font-lock-warning-face ((t (:foreground "#212121"))))
 '(font-lock-function-name-face ((t (:foreground "#3264EA"))))
 '(font-lock-negation-char-face ((t (:foreground "#085FB8"))))
 '(font-lock-variable-use-face ((t (:foreground "#212121"))))
 '(font-lock-property-use-face ((t (:foreground "#212121"))))
 '(font-lock-number-face ((t (:foreground "#212121"))))
 '(font-lock-bracket-face ((t (:foreground "#212121"))))
 '(font-lock-delimiter-face ((t (:foreground "#757575"))))
 '(font-lock-escape-face ((t (:foreground "#4A2FCF"))))
 '(show-paren-match ((t (:foreground "#212121"))))
 '(show-paren-mismatch-face ((t (:foreground "#212121" :background "#F9F9F9"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#9E9E9E" :background "#F9F9F9" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#212121"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#3264EA"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#026FDD"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#212121"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#212121"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#0C67DD"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#3264EA" :background "#F4F4F4" :overline "#9E9E9E"))))
 '(org-level-2 ((t (:foreground "#3264EA" :background "#F4F4F4" :overline "#9E9E9E"))))
 '(org-level-3 ((t (:foreground "#3264EA" :background "#F4F4F4" :overline "#9E9E9E"))))
 '(org-level-4 ((t (:foreground "#3264EA" :background "#F4F4F4" :overline "#9E9E9E"))))
 '(org-level-5 ((t (:foreground "#3264EA" :background "#F4F4F4" :overline "#9E9E9E"))))
 '(org-level-6 ((t (:foreground "#3264EA" :background "#F4F4F4" :overline "#9E9E9E"))))
 '(org-level-7 ((t (:foreground "#3264EA" :background "#F4F4F4" :overline "#9E9E9E"))))
 '(org-tag ((t (:foreground "#212121"))))
 '(org-headline-done ((t (:foreground "#B363FF" :background "#F9F9F9"))))
 '(org-done ((t (:foreground "#212121"))))
 '(org-todo ((t (:foreground "#B363FF"))))
 '(org-checkbox ((t (:foreground "#212121" :background "#F4F4F4"))))
 '(org-link ((t (:foreground "#3264EA" :background "#F9F9F9" :underline nil))))
 '(org-verbatim ((t (:foreground "#4A2FCF"))))
 '(org-code ((t (:foreground "#4A2FCF"))))
 '(org-table ((t (:foreground "#4A2FCF" :background "#EBEBEB"))))
 '(org-date ((t (:foreground "#3264EA" :underline t))))
 '(org-archived ((t (:foreground "#9E9E9E" :background "#F9F9F9"))))
 '(org-list-dt ((t (:foreground "#3264EA"))))
 '(org-drawer ((t (:foreground "#5482FF"))))
 '(org-special-keyword ((t (:foreground "#757575"))))
 '(org-property-value ((t (:foreground "#212121" :background "#F9F9F9"))))
 '(org-block ((t (:background "#F4F4F4" :extend t))))
 '(org-block-begin-line ((t (:foreground "#9E9E9E" :background "#F9F9F9" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#757575"))))
 '(org-superstar-header-bullet ((t (:foreground "#212121" :background "#EBEBEB" :overline t))))
 '(org-superstar-item ((t (:foreground "#212121"))))
 '(org-superstar-ordered-item ((t (:foreground "#0C67DD"))))
 '(org-hide ((t (:foreground "#F9F9F9"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#3264EA" :height 220 :underline "#3264EA"))))
 '(markdown-header-face-2 ((t (:foreground "#3264EA" :height 180 :underline "#3264EA"))))
 '(markdown-header-face-3 ((t (:foreground "#3264EA" :underline "#212121"))))
 '(markdown-header-face-4 ((t (:foreground "#4A2FCF"))))
 '(markdown-header-face-5 ((t (:foreground "#4A2FCF"))))
 '(markdown-header-face-6 ((t (:foreground "#4A2FCF"))))
 '(markdown-list-face ((t (:foreground "#212121"))))
 '(markdown-inline-code-face ((t (:foreground "#4A2FCF" :background "#F9F9F9"))))
 '(markdown-language-keyword-face ((t (:foreground "#212121"))))
 '(markdown-pre-face ((t (:foreground "#4A2FCF"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#9E9E9E"))))
 '(markdown-header-delimiter-face ((t (:foreground "#212121"))))
 '(markdown-bold-face ((t (:foreground "#4A2FCF" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#4A2FCF" :slant italic))))
 '(markdown-link-face ((t (:foreground "#4A2FCF"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#3264EA"))))
 '(compilation-warning ((t (:foreground "#3264EA"))))
 '(compilation-error ((t (:foreground "#212121"))))
 '(compilation-line-number ((t (:foreground "#4A2FCF" :underline t))))
 '(compilation-column-number ((t (:foreground "#4A2FCF" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#212121"))))
 '(flycheck-fringe-warning ((t (:foreground "#3264EA"))))
 '(flycheck-fringe-info ((t (:foreground "#3264EA"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#EBEBEB"))))
 '(lsp-face-highlight-textual ((t (:background "#CFCFCF"))))
 '(lsp-face-highlight-write ((t (:background "#CFCFCF"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#CFCFCF"))))
 '(eglot-inlay-hint-face ((t (:foreground "#4A2FCF" :background "#F9F9F9" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#4A2FCF"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#212121" :background "#EBEBEB"))))
 '(company-preview-common ((t (:foreground "#4A2FCF" :background "#EBEBEB"))))
 '(company-preview-search ((t (:foreground "#4A2FCF" :background "#EBEBEB"))))
 '(company-tooltip-common ((t (:foreground "#4A2FCF" :background "#EBEBEB"))))
 '(company-tooltip-common-selection ((t (:foreground "#4A2FCF" :background "#EBEBEB"))))
 '(company-tooltip-annotation ((t (:foreground "#4A2FCF" :background "#EBEBEB"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#4A2FCF" :background "#EBEBEB"))))
 '(company-tooltip-search-selection ((t (:foreground "#4A2FCF" :background "#CFCFCF"))))
 '(company-tooltip-mouse ((t (:foreground "#4A2FCF" :background "#CFCFCF"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#212121" :background "#F9F9F9"))))
 '(magit-branch-current ((t (:foreground "#3264EA" :box 1))))
 '(magit-branch-remote ((t (:foreground "#3264EA" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#B363FF"))))
 '(rg-line-number-face ((t (:foreground "#4A2FCF"))))

 ;; line numbers
 '(line-number ((t (:foreground "#9E9E9E" :background "#F9F9F9"))))
 '(line-number-current-line ((t (:foreground "#9E9E9E" :background "#F9F9F9"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#9E9E9E"))))
 '(doom-modeline-bar ((t (:background "#EBEBEB"))))
 '(doom-modeline-bar-inactive ((t (:background "#F9F9F9"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#0C67DD" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#B363FF"))))
 '(doom-modeline-project-dir ((t (:foreground "#212121"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#212121"))))
 '(doom-modeline-urgent ((t (:foreground "#B363FF"))))
 '(doom-modeline-info ((t (:foreground "#212121"))))
 '(doom-modeline-warning ((t (:foreground "#B363FF"))))
 '(doom-modeline-error ((t (:foreground "#212121"))))
 '(doom-modeline-inactive-bar ((t (:background "#F9F9F9"))))
 '(mode-line ((t (:foreground "#B0B0B0" :background "#EBEBEB"))))
 '(mode-line-inactive ((t (:background "#EBEBEB"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#B0B0B0"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#B0B0B0"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#757575" :background "#F9F9F9"))))
 '(tab-bar-tab ((t (:foreground "#3264EA" :background "#F9F9F9" :box (:line-width 2 :color "#F9F9F9")))))
 '(tab-bar-tab-inactive ((t (:foreground "#757575" :background "#F9F9F9"))))

 ;; misc
 '(secondary-selection ((t (:background "#F4F4F4"))))
 '(shadow ((t (:foreground "#9E9E9E")))))

(provide-theme 'lupine)
