
;;; matte-black-theme.el --- Generated by Book of Colours

(deftheme matte-black "matte-black")

(custom-theme-set-faces
 'matte-black

 ;; common
 '(default ((t (:foreground "#FFC007" :background "#121212"))))
 '(cursor ((t (:foreground "#121212" :background "#E9E9E9"))))
 '(region ((t (:foreground "#BEBEBE" :background "#515151"))))
 '(hl-line ((t (:background "#212121"))))
 '(minibuffer-prompt ((t (:foreground "#8A8A8D"))))
 '(link ((t (:foreground "#10B981" :underline t))))
 '(warning ((t (:foreground "#D87706"))))
 '(error ((t (:foreground "#DB2626"))))
 '(success ((t (:foreground "#10B981"))))
 '(bold ((t (:foreground "#FABF24" :weight bold))))
 '(isearch ((t (:foreground "#BEBEBE" :background "#515151"))))
 '(lazy-highlight ((t (:foreground "#F49E0B" :background "#515151"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#D87706" :background "#121212" :weight bold))))
 '(tooltip ((t (:foreground "#D87706" :background "#1A1A1A" :weight bold))))
 '(fringe ((t (:background "#121212"))))
 '(vertical-border ((t (:foreground "#2A2A2A"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#D87706"))))
 '(header-line ((t (:foreground "#8A8A8D" :background "#121212"))))
 '(header-line-highlight ((t (:foreground "#FABF24" :background "#121212"))))
 '(highlight ((t (:foreground "#F49E0B" :background "#515151"))))
 '(button ((t (:foreground "#10B981" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#8A8A8D" :background "#1A1A1A" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#BEBEBE" :background "#1A1A1A" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#F49E0B"))))
 '(font-lock-type-face ((t (:foreground "#EEBF04"))))
 '(font-lock-preprocessor-face ((t (:foreground "#059669"))))
 '(font-lock-operator-face ((t (:foreground "#8A8A8D"))))
 '(font-lock-string-face ((t (:foreground "#FFFFFF"))))
 '(font-lock-variable-name-face ((t (:foreground "#E9E9E9"))))
 '(font-lock-constant-face ((t (:foreground "#EEBF04"))))
 '(font-lock-keyword-face ((t (:foreground "#10B981"))))
 '(font-lock-warning-face ((t (:foreground "#D87706"))))
 '(font-lock-function-name-face ((t (:foreground "#B91C1C"))))
 '(font-lock-negation-char-face ((t (:foreground "#8A8A8D"))))
 '(font-lock-variable-use-face ((t (:foreground "#FFC007"))))
 '(font-lock-property-use-face ((t (:foreground "#D87706"))))
 '(font-lock-number-face ((t (:foreground "#EEBF04"))))
 '(font-lock-bracket-face ((t (:foreground "#BEBEBE"))))
 '(font-lock-delimiter-face ((t (:foreground "#5C6370"))))
 '(font-lock-escape-face ((t (:foreground "#FABF24"))))
 '(show-paren-match ((t (:foreground "#F49E0B"))))
 '(show-paren-mismatch-face ((t (:foreground "#DB2626" :background "#121212"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#8A8A8D" :background "#1A1A1A" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#FFFFFF"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#B91C1C"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#EEBF04"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#EEBF04"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#BEBEBE"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#BEBEBE"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#D87706" :background "#212121" :overline "#8A8A8D"))))
 '(org-level-2 ((t (:foreground "#D87706" :background "#212121" :overline "#8A8A8D"))))
 '(org-level-3 ((t (:foreground "#D87706" :background "#212121" :overline "#8A8A8D"))))
 '(org-level-4 ((t (:foreground "#D87706" :background "#212121" :overline "#8A8A8D"))))
 '(org-level-5 ((t (:foreground "#D87706" :background "#212121" :overline "#8A8A8D"))))
 '(org-level-6 ((t (:foreground "#D87706" :background "#212121" :overline "#8A8A8D"))))
 '(org-level-7 ((t (:foreground "#D87706" :background "#212121" :overline "#8A8A8D"))))
 '(org-tag ((t (:foreground "#E9E9E9"))))
 '(org-headline-done ((t (:foreground "#10B981" :background "#1A1A1A"))))
 '(org-done ((t (:foreground "#FFC007"))))
 '(org-todo ((t (:foreground "#FABF24"))))
 '(org-checkbox ((t (:foreground "#F49E0B" :background "#121212"))))
 '(org-link ((t (:foreground "#10B981" :background "#121212" :underline nil))))
 '(org-verbatim ((t (:foreground "#FABF24"))))
 '(org-code ((t (:foreground "#FABF24"))))
 '(org-table ((t (:foreground "#FABF24" :background "#121212"))))
 '(org-date ((t (:foreground "#D87706" :underline t))))
 '(org-archived ((t (:foreground "#8A8A8D" :background "#1A1A1A"))))
 '(org-list-dt ((t (:foreground "#F49E0B"))))
 '(org-drawer ((t (:foreground "#059669"))))
 '(org-special-keyword ((t (:foreground "#5C6370"))))
 '(org-property-value ((t (:foreground "#D87706" :background "#121212"))))
 '(org-block ((t (:background "#212121" :extend t))))
 '(org-block-begin-line ((t (:foreground "#8A8A8D" :background "#121212" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#5C6370"))))
 '(org-superstar-header-bullet ((t (:foreground "#F49E0B" :background "#121212" :overline t))))
 '(org-superstar-item ((t (:foreground "#D87706"))))
 '(org-superstar-ordered-item ((t (:foreground "#BEBEBE"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#FABF24" :height 220 :underline "#D87706"))))
 '(markdown-header-face-2 ((t (:foreground "#FABF24" :height 180 :underline "#D87706"))))
 '(markdown-header-face-3 ((t (:foreground "#FABF24" :underline "#BEBEBE"))))
 '(markdown-header-face-4 ((t (:foreground "#FABF24"))))
 '(markdown-header-face-5 ((t (:foreground "#FABF24"))))
 '(markdown-header-face-6 ((t (:foreground "#FABF24"))))
 '(markdown-list-face ((t (:foreground "#D87706"))))
 '(markdown-inline-code-face ((t (:foreground "#FABF24" :background "#1A1A1A"))))
 '(markdown-language-keyword-face ((t (:foreground "#E9E9E9"))))
 '(markdown-pre-face ((t (:foreground "#FABF24"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#8A8A8D"))))
 '(markdown-header-delimiter-face ((t (:foreground "#BEBEBE"))))
 '(markdown-bold-face ((t (:foreground "#FABF24" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#FABF24" :slant italic))))
 '(markdown-link-face ((t (:foreground "#FABF24"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#D87706"))))
 '(compilation-warning ((t (:foreground "#D87706"))))
 '(compilation-error ((t (:foreground "#DB2626"))))
 '(compilation-line-number ((t (:foreground "#FABF24" :underline t))))
 '(compilation-column-number ((t (:foreground "#FABF24" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#DB2626"))))
 '(flycheck-fringe-warning ((t (:foreground "#D87706"))))
 '(flycheck-fringe-info ((t (:foreground "#D87706"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#121212"))))
 '(lsp-face-highlight-textual ((t (:background "#515151"))))
 '(lsp-face-highlight-write ((t (:background "#515151"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#515151"))))
 '(eglot-inlay-hint-face ((t (:foreground "#FABF24" :background "#1A1A1A" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#FABF24"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#FFC007" :background "#121212"))))
 '(company-preview-common ((t (:foreground "#FABF24" :background "#121212"))))
 '(company-preview-search ((t (:foreground "#FABF24" :background "#121212"))))
 '(company-tooltip-common ((t (:foreground "#FABF24" :background "#121212"))))
 '(company-tooltip-common-selection ((t (:foreground "#FABF24" :background "#121212"))))
 '(company-tooltip-annotation ((t (:foreground "#FABF24" :background "#121212"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#FABF24" :background "#121212"))))
 '(company-tooltip-search-selection ((t (:foreground "#FABF24" :background "#515151"))))
 '(company-tooltip-mouse ((t (:foreground "#FABF24" :background "#515151"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#D87706" :background "#1A1A1A"))))
 '(magit-branch-current ((t (:foreground "#D87706" :box 1))))
 '(magit-branch-remote ((t (:foreground "#D87706" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#10B981"))))
 '(rg-line-number-face ((t (:foreground "#FABF24"))))

 ;; line numbers
 '(line-number ((t (:foreground "#8A8A8D" :background "#121212"))))
 '(line-number-current-line ((t (:foreground "#8A8A8D" :background "#121212"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#5C6370"))))
 '(doom-modeline-bar ((t (:background "#121212"))))
 '(doom-modeline-bar-inactive ((t (:background "#121212"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#BEBEBE" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#10B981"))))
 '(doom-modeline-project-dir ((t (:foreground "#BEBEBE"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#FFC007"))))
 '(doom-modeline-urgent ((t (:foreground "#10B981"))))
 '(doom-modeline-info ((t (:foreground "#D87706"))))
 '(doom-modeline-warning ((t (:foreground "#10B981"))))
 '(doom-modeline-error ((t (:foreground "#DB2626"))))
 '(doom-modeline-inactive-bar ((t (:background "#121212"))))
 '(mode-line ((t (:foreground "#212121" :background "#121212"))))
 '(mode-line-inactive ((t (:background "#121212"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#212121"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#212121"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#5C6370" :background "#121212"))))
 '(tab-bar-tab ((t (:foreground "#D87706" :background "#121212" :box (:line-width 2 :color "#121212")))))
 '(tab-bar-tab-inactive ((t (:foreground "#5C6370" :background "#121212"))))

 ;; misc
 '(secondary-selection ((t (:background "#212121"))))
 '(shadow ((t (:foreground "#8A8A8D")))))

(provide-theme 'matte-black)
