
;;; miasma-theme.el --- Generated by Book of Colours

(deftheme miasma "miasma")

(custom-theme-set-faces
 'miasma

 ;; common
 '(default ((t (:foreground "#C1C1B0" :background "#222222"))))
 '(cursor ((t (:foreground "#222222" :background "#C6C6C6"))))
 '(region ((t (:foreground "#C1C1B0" :background "#78824B"))))
 '(hl-line ((t (:background "#1C1C1C"))))
 '(minibuffer-prompt ((t (:foreground "#666666"))))
 '(link ((t (:foreground "#FAEB9F" :underline t))))
 '(warning ((t (:foreground "#D6C383"))))
 '(error ((t (:foreground "#D6C383"))))
 '(success ((t (:foreground "#78834B"))))
 '(bold ((t (:foreground "#D6C383" :weight bold))))
 '(isearch ((t (:foreground "#C1C1B0" :background "#78824B"))))
 '(lazy-highlight ((t (:foreground "#D6C383" :background "#78824B"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#D6C383" :background "#222222" :weight bold))))
 '(tooltip ((t (:foreground "#BB7744" :background "#1C1C1C" :weight bold))))
 '(fringe ((t (:background "#222222"))))
 '(vertical-border ((t (:foreground "#101010"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#D6C383"))))
 '(header-line ((t (:foreground "#666666" :background "#222222"))))
 '(header-line-highlight ((t (:foreground "#D6C383" :background "#222222"))))
 '(highlight ((t (:foreground "#D6C383" :background "#78824B"))))
 '(button ((t (:foreground "#5F875F" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#666666" :background "#1C1C1C" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#C1C1B0" :background "#1C1C1C" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#D6C383"))))
 '(font-lock-type-face ((t (:foreground "#BB7744"))))
 '(font-lock-preprocessor-face ((t (:foreground "#78824B"))))
 '(font-lock-operator-face ((t (:foreground "#FAEB9F"))))
 '(font-lock-string-face ((t (:foreground "#685742"))))
 '(font-lock-variable-name-face ((t (:foreground "#D6C383"))))
 '(font-lock-constant-face ((t (:foreground "#BB7744"))))
 '(font-lock-keyword-face ((t (:foreground "#5F875F"))))
 '(font-lock-warning-face ((t (:foreground "#D6C383"))))
 '(font-lock-function-name-face ((t (:foreground "#78834B"))))
 '(font-lock-negation-char-face ((t (:foreground "#FAEB9F"))))
 '(font-lock-variable-use-face ((t (:foreground "#D6C383"))))
 '(font-lock-property-use-face ((t (:foreground "#C1C1B0"))))
 '(font-lock-number-face ((t (:foreground "#BB7744"))))
 '(font-lock-bracket-face ((t (:foreground "#666666"))))
 '(font-lock-delimiter-face ((t (:foreground "#666666"))))
 '(font-lock-escape-face ((t (:foreground "#D6C383"))))
 '(show-paren-match ((t (:foreground "#D6C383"))))
 '(show-paren-mismatch-face ((t (:foreground "#D6C383" :background "#222222"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#666666" :background "#1C1C1C" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#685742"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#78834B"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#BB7744"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#78834B"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#D6C383"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#C8A554"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#BB7744" :background "#1C1C1C" :overline "#666666"))))
 '(org-level-2 ((t (:foreground "#B36D43" :background "#1C1C1C" :overline "#666666"))))
 '(org-level-3 ((t (:foreground "#B36D43" :background "#1C1C1C" :overline "#666666"))))
 '(org-level-4 ((t (:foreground "#B36D43" :background "#1C1C1C" :overline "#666666"))))
 '(org-level-5 ((t (:foreground "#B36D43" :background "#1C1C1C" :overline "#666666"))))
 '(org-level-6 ((t (:foreground "#B36D43" :background "#1C1C1C" :overline "#666666"))))
 '(org-level-7 ((t (:foreground "#B36D43" :background "#1C1C1C" :overline "#666666"))))
 '(org-tag ((t (:foreground "#D6C383"))))
 '(org-headline-done ((t (:foreground "#5F875F" :background "#1C1C1C"))))
 '(org-done ((t (:foreground "#C1C1B0"))))
 '(org-todo ((t (:foreground "#5F875F"))))
 '(org-checkbox ((t (:foreground "#D6C383" :background "#1C1C1C"))))
 '(org-link ((t (:foreground "#FAEB9F" :background "#222222" :underline nil))))
 '(org-verbatim ((t (:foreground "#D6C383"))))
 '(org-code ((t (:foreground "#D6C383"))))
 '(org-table ((t (:foreground "#D6C383" :background "#222222"))))
 '(org-date ((t (:foreground "#B36D43" :underline t))))
 '(org-archived ((t (:foreground "#666666" :background "#1C1C1C"))))
 '(org-list-dt ((t (:foreground "#D6C383"))))
 '(org-drawer ((t (:foreground "#78824B"))))
 '(org-special-keyword ((t (:foreground "#666666"))))
 '(org-property-value ((t (:foreground "#D6C383" :background "#222222"))))
 '(org-block ((t (:background "#1C1C1C" :extend t))))
 '(org-block-begin-line ((t (:foreground "#666666" :background "#222222" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#666666"))))
 '(org-superstar-header-bullet ((t (:foreground "#D6C383" :background "#222222" :overline t))))
 '(org-superstar-item ((t (:foreground "#D6C383"))))
 '(org-superstar-ordered-item ((t (:foreground "#C8A554"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#D6C383" :height 220 :underline "#BB7744"))))
 '(markdown-header-face-2 ((t (:foreground "#D6C383" :height 180 :underline "#BB7744"))))
 '(markdown-header-face-3 ((t (:foreground "#D6C383" :underline "#C1C1B0"))))
 '(markdown-header-face-4 ((t (:foreground "#D6C383"))))
 '(markdown-header-face-5 ((t (:foreground "#D6C383"))))
 '(markdown-header-face-6 ((t (:foreground "#D6C383"))))
 '(markdown-list-face ((t (:foreground "#D6C383"))))
 '(markdown-inline-code-face ((t (:foreground "#D6C383" :background "#1C1C1C"))))
 '(markdown-language-keyword-face ((t (:foreground "#D6C383"))))
 '(markdown-pre-face ((t (:foreground "#D6C383"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#666666"))))
 '(markdown-header-delimiter-face ((t (:foreground "#666666"))))
 '(markdown-bold-face ((t (:foreground "#D6C383" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#D6C383" :slant italic))))
 '(markdown-link-face ((t (:foreground "#D6C383"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#BB7744"))))
 '(compilation-warning ((t (:foreground "#BB7744"))))
 '(compilation-error ((t (:foreground "#D6C383"))))
 '(compilation-line-number ((t (:foreground "#D6C383" :underline t))))
 '(compilation-column-number ((t (:foreground "#D6C383" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#D6C383"))))
 '(flycheck-fringe-warning ((t (:foreground "#BB7744"))))
 '(flycheck-fringe-info ((t (:foreground "#BB7744"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#222222"))))
 '(lsp-face-highlight-textual ((t (:background "#78824B"))))
 '(lsp-face-highlight-write ((t (:background "#78824B"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#78824B"))))
 '(eglot-inlay-hint-face ((t (:foreground "#D6C383" :background "#1C1C1C" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#D6C383"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#D6C383" :background "#222222"))))
 '(company-preview-common ((t (:foreground "#D6C383" :background "#222222"))))
 '(company-preview-search ((t (:foreground "#D6C383" :background "#222222"))))
 '(company-tooltip-common ((t (:foreground "#D6C383" :background "#222222"))))
 '(company-tooltip-common-selection ((t (:foreground "#D6C383" :background "#222222"))))
 '(company-tooltip-annotation ((t (:foreground "#D6C383" :background "#222222"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#D6C383" :background "#222222"))))
 '(company-tooltip-search-selection ((t (:foreground "#D6C383" :background "#78824B"))))
 '(company-tooltip-mouse ((t (:foreground "#D6C383" :background "#78824B"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#C1C1B0" :background "#1C1C1C"))))
 '(magit-branch-current ((t (:foreground "#BB7744" :box 1))))
 '(magit-branch-remote ((t (:foreground "#BB7744" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#5F875F"))))
 '(rg-line-number-face ((t (:foreground "#D6C383"))))

 ;; line numbers
 '(line-number ((t (:foreground "#666666" :background "#222222"))))
 '(line-number-current-line ((t (:foreground "#666666" :background "#222222"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#666666"))))
 '(doom-modeline-bar ((t (:background "#222222"))))
 '(doom-modeline-bar-inactive ((t (:background "#222222"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#C8A554" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#5F875F"))))
 '(doom-modeline-project-dir ((t (:foreground "#D6C383"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#C1C1B0"))))
 '(doom-modeline-urgent ((t (:foreground "#5F875F"))))
 '(doom-modeline-info ((t (:foreground "#D6C383"))))
 '(doom-modeline-warning ((t (:foreground "#5F875F"))))
 '(doom-modeline-error ((t (:foreground "#D6C383"))))
 '(doom-modeline-inactive-bar ((t (:background "#222222"))))
 '(mode-line ((t (:foreground "#1C1C1C" :background "#222222"))))
 '(mode-line-inactive ((t (:background "#222222"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#1C1C1C"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#1C1C1C"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#666666" :background "#222222"))))
 '(tab-bar-tab ((t (:foreground "#B36D43" :background "#222222" :box (:line-width 2 :color "#222222")))))
 '(tab-bar-tab-inactive ((t (:foreground "#666666" :background "#222222"))))

 ;; misc
 '(secondary-selection ((t (:background "#1C1C1C"))))
 '(shadow ((t (:foreground "#666666")))))

(provide-theme 'miasma)
