
;;; nord-theme.el --- Generated by Book of Colours

(deftheme nord "nord")

(custom-theme-set-faces
 'nord

 ;; common
 '(default ((t (:foreground "#D7DDE8" :background "#2E3440"))))
 '(cursor ((t (:foreground "#2E3440" :background "#D7DDE8"))))
 '(region ((t (:foreground "#D7DDE8" :background "#4C566A"))))
 '(hl-line ((t (:background "#232831"))))
 '(minibuffer-prompt ((t (:foreground "#7E8188"))))
 '(link ((t (:foreground "#A3BE8C" :underline t))))
 '(warning ((t (:foreground "#EACA8B"))))
 '(error ((t (:foreground "#BF616A"))))
 '(success ((t (:foreground "#A3BE8C"))))
 '(bold ((t (:foreground "#EFD299" :weight bold))))
 '(isearch ((t (:foreground "#D7DDE8" :background "#4C566A"))))
 '(lazy-highlight ((t (:foreground "#81A1C0" :background "#4C566A"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#EACA8B" :background "#2E3440" :weight bold))))
 '(tooltip ((t (:foreground "#8CAFD1" :background "#232831" :weight bold))))
 '(fringe ((t (:background "#2E3440"))))
 '(vertical-border ((t (:foreground "#232831"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#D7DDE8"))))
 '(header-line ((t (:foreground "#7E8188" :background "#2E3440"))))
 '(header-line-highlight ((t (:foreground "#EFD299" :background "#2E3440"))))
 '(highlight ((t (:foreground "#81A1C0" :background "#4C566A"))))
 '(button ((t (:foreground "#B48EAD" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#7E8188" :background "#232831" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#D7DDE8" :background "#232831" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#81A1C0"))))
 '(font-lock-type-face ((t (:foreground "#EACA8B"))))
 '(font-lock-preprocessor-face ((t (:foreground "#A96CA5"))))
 '(font-lock-operator-face ((t (:foreground "#93CBDB"))))
 '(font-lock-string-face ((t (:foreground "#B1D096"))))
 '(font-lock-variable-name-face ((t (:foreground "#88C0CF"))))
 '(font-lock-constant-face ((t (:foreground "#A3BE8C"))))
 '(font-lock-keyword-face ((t (:foreground "#B48EAD"))))
 '(font-lock-warning-face ((t (:foreground "#EACA8B"))))
 '(font-lock-function-name-face ((t (:foreground "#8CAFD1"))))
 '(font-lock-negation-char-face ((t (:foreground "#93CBDB"))))
 '(font-lock-variable-use-face ((t (:foreground "#D7DDE8"))))
 '(font-lock-property-use-face ((t (:foreground "#D7DDE8"))))
 '(font-lock-number-face ((t (:foreground "#D79079"))))
 '(font-lock-bracket-face ((t (:foreground "#ABB1BB"))))
 '(font-lock-delimiter-face ((t (:foreground "#7E8188"))))
 '(font-lock-escape-face ((t (:foreground "#EFD299"))))
 '(show-paren-match ((t (:foreground "#D7DDE8"))))
 '(show-paren-mismatch-face ((t (:foreground "#BF616A" :background "#2E3440"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#7E8188" :background "#232831" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#B1D096"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#8CAFD1"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#EACA8B"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#A3BE8C"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#D7DDE8"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#E4E8EF"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#8CAFD1" :background "#232831" :overline "#7E8188"))))
 '(org-level-2 ((t (:foreground "#668AAB" :background "#232831" :overline "#7E8188"))))
 '(org-level-3 ((t (:foreground "#668AAB" :background "#232831" :overline "#7E8188"))))
 '(org-level-4 ((t (:foreground "#668AAB" :background "#232831" :overline "#7E8188"))))
 '(org-level-5 ((t (:foreground "#668AAB" :background "#232831" :overline "#7E8188"))))
 '(org-level-6 ((t (:foreground "#668AAB" :background "#232831" :overline "#7E8188"))))
 '(org-level-7 ((t (:foreground "#668AAB" :background "#232831" :overline "#7E8188"))))
 '(org-tag ((t (:foreground "#88C0CF"))))
 '(org-headline-done ((t (:foreground "#B48EAD" :background "#232831"))))
 '(org-done ((t (:foreground "#D7DDE8"))))
 '(org-todo ((t (:foreground "#EACA8B"))))
 '(org-checkbox ((t (:foreground "#81A1C0" :background "#232831"))))
 '(org-link ((t (:foreground "#A3BE8C" :background "#2E3440" :underline nil))))
 '(org-verbatim ((t (:foreground "#EFD299"))))
 '(org-code ((t (:foreground "#EFD299"))))
 '(org-table ((t (:foreground "#EFD299" :background "#2E3440"))))
 '(org-date ((t (:foreground "#668AAB" :underline t))))
 '(org-archived ((t (:foreground "#7E8188" :background "#232831"))))
 '(org-list-dt ((t (:foreground "#81A1C0"))))
 '(org-drawer ((t (:foreground "#A96CA5"))))
 '(org-special-keyword ((t (:foreground "#7E8188"))))
 '(org-property-value ((t (:foreground "#D7DDE8" :background "#2E3440"))))
 '(org-block ((t (:background "#232831" :extend t))))
 '(org-block-begin-line ((t (:foreground "#7E8188" :background "#2E3440" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#7E8188"))))
 '(org-superstar-header-bullet ((t (:foreground "#81A1C0" :background "#2E3440" :overline t))))
 '(org-superstar-item ((t (:foreground "#EACA8B"))))
 '(org-superstar-ordered-item ((t (:foreground "#E4E8EF"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#EFD299" :height 220 :underline "#8CAFD1"))))
 '(markdown-header-face-2 ((t (:foreground "#EFD299" :height 180 :underline "#8CAFD1"))))
 '(markdown-header-face-3 ((t (:foreground "#EFD299" :underline "#D7DDE8"))))
 '(markdown-header-face-4 ((t (:foreground "#EFD299"))))
 '(markdown-header-face-5 ((t (:foreground "#EFD299"))))
 '(markdown-header-face-6 ((t (:foreground "#EFD299"))))
 '(markdown-list-face ((t (:foreground "#EACA8B"))))
 '(markdown-inline-code-face ((t (:foreground "#EFD299" :background "#232831"))))
 '(markdown-language-keyword-face ((t (:foreground "#88C0CF"))))
 '(markdown-pre-face ((t (:foreground "#EFD299"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#7E8188"))))
 '(markdown-header-delimiter-face ((t (:foreground "#ABB1BB"))))
 '(markdown-bold-face ((t (:foreground "#EFD299" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#EFD299" :slant italic))))
 '(markdown-link-face ((t (:foreground "#EFD299"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#8CAFD1"))))
 '(compilation-warning ((t (:foreground "#8CAFD1"))))
 '(compilation-error ((t (:foreground "#BF616A"))))
 '(compilation-line-number ((t (:foreground "#EFD299" :underline t))))
 '(compilation-column-number ((t (:foreground "#EFD299" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#BF616A"))))
 '(flycheck-fringe-warning ((t (:foreground "#8CAFD1"))))
 '(flycheck-fringe-info ((t (:foreground "#8CAFD1"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#2E3440"))))
 '(lsp-face-highlight-textual ((t (:background "#4C566A"))))
 '(lsp-face-highlight-write ((t (:background "#4C566A"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#4C566A"))))
 '(eglot-inlay-hint-face ((t (:foreground "#EFD299" :background "#232831" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#EFD299"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#D7DDE8" :background "#2E3440"))))
 '(company-preview-common ((t (:foreground "#EFD299" :background "#2E3440"))))
 '(company-preview-search ((t (:foreground "#EFD299" :background "#2E3440"))))
 '(company-tooltip-common ((t (:foreground "#EFD299" :background "#2E3440"))))
 '(company-tooltip-common-selection ((t (:foreground "#EFD299" :background "#2E3440"))))
 '(company-tooltip-annotation ((t (:foreground "#EFD299" :background "#2E3440"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#EFD299" :background "#2E3440"))))
 '(company-tooltip-search-selection ((t (:foreground "#EFD299" :background "#4C566A"))))
 '(company-tooltip-mouse ((t (:foreground "#EFD299" :background "#4C566A"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#D7DDE8" :background "#232831"))))
 '(magit-branch-current ((t (:foreground "#8CAFD1" :box 1))))
 '(magit-branch-remote ((t (:foreground "#8CAFD1" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#B48EAD"))))
 '(rg-line-number-face ((t (:foreground "#EFD299"))))

 ;; line numbers
 '(line-number ((t (:foreground "#7E8188" :background "#2E3440"))))
 '(line-number-current-line ((t (:foreground "#7E8188" :background "#2E3440"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#444C5E"))))
 '(doom-modeline-bar ((t (:background "#2E3440"))))
 '(doom-modeline-bar-inactive ((t (:background "#2E3440"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#E4E8EF" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#B48EAD"))))
 '(doom-modeline-project-dir ((t (:foreground "#D7DDE8"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#D7DDE8"))))
 '(doom-modeline-urgent ((t (:foreground "#B48EAD"))))
 '(doom-modeline-info ((t (:foreground "#D7DDE8"))))
 '(doom-modeline-warning ((t (:foreground "#B48EAD"))))
 '(doom-modeline-error ((t (:foreground "#BF616A"))))
 '(doom-modeline-inactive-bar ((t (:background "#2E3440"))))
 '(mode-line ((t (:foreground "#444C5E" :background "#2E3440"))))
 '(mode-line-inactive ((t (:background "#2E3440"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#444C5E"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#444C5E"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#7E8188" :background "#2E3440"))))
 '(tab-bar-tab ((t (:foreground "#668AAB" :background "#2E3440" :box (:line-width 2 :color "#2E3440")))))
 '(tab-bar-tab-inactive ((t (:foreground "#7E8188" :background "#2E3440"))))

 ;; misc
 '(secondary-selection ((t (:background "#232831"))))
 '(shadow ((t (:foreground "#C6CCD8")))))

(provide-theme 'nord)
