
;;; osaka-jade-theme.el --- Generated by Book of Colours

(deftheme osaka-jade "osaka-jade")

(custom-theme-set-faces
 'osaka-jade

 ;; common
 '(default ((t (:foreground "#F0E8D1" :background "#252623"))))
 '(cursor ((t (:foreground "#252623" :background "#F0E8D1"))))
 '(region ((t (:foreground "#C0C397" :background "#111C18"))))
 '(hl-line ((t (:background "#2F312C"))))
 '(minibuffer-prompt ((t (:foreground "#E1C692"))))
 '(link ((t (:foreground "#70C1BE" :underline t))))
 '(warning ((t (:foreground "#DAB651"))))
 '(error ((t (:foreground "#E65A7C"))))
 '(success ((t (:foreground "#8FB573"))))
 '(bold ((t (:foreground "#CBD5AE" :weight bold))))
 '(isearch ((t (:foreground "#C0C397" :background "#111C18"))))
 '(lazy-highlight ((t (:foreground "#F5F4DC" :background "#111C18"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#DAB651" :background "#383B35" :weight bold))))
 '(tooltip ((t (:foreground "#8FB573" :background "#3A3D37" :weight bold))))
 '(fringe ((t (:background "#252623"))))
 '(vertical-border ((t (:foreground "#111210"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#F0E8D1"))))
 '(header-line ((t (:foreground "#5B5E5A" :background "#383B35"))))
 '(header-line-highlight ((t (:foreground "#CBD5AE" :background "#383B35"))))
 '(highlight ((t (:foreground "#F5F4DC" :background "#111C18"))))
 '(button ((t (:foreground "#549E6A" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#E1C692" :background "#3A3D37" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#F0E8D1" :background "#3A3D37" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#F5F4DC"))))
 '(font-lock-type-face ((t (:foreground "#DAB651"))))
 '(font-lock-preprocessor-face ((t (:foreground "#AAAAFF"))))
 '(font-lock-operator-face ((t (:foreground "#C4C1ED"))))
 '(font-lock-string-face ((t (:foreground "#8FB573"))))
 '(font-lock-variable-name-face ((t (:foreground "#B94863"))))
 '(font-lock-constant-face ((t (:foreground "#FF9966"))))
 '(font-lock-keyword-face ((t (:foreground "#AAAAFF"))))
 '(font-lock-warning-face ((t (:foreground "#DAB651"))))
 '(font-lock-function-name-face ((t (:foreground "#57A5E4"))))
 '(font-lock-negation-char-face ((t (:foreground "#C4C1ED"))))
 '(font-lock-variable-use-face ((t (:foreground "#F0E8D1"))))
 '(font-lock-property-use-face ((t (:foreground "#F0E8D1"))))
 '(font-lock-number-face ((t (:foreground "#FF9966"))))
 '(font-lock-bracket-face ((t (:foreground "#838781"))))
 '(font-lock-delimiter-face ((t (:foreground "#838781"))))
 '(font-lock-escape-face ((t (:foreground "#CBD5AE"))))
 '(show-paren-match ((t (:foreground "#F0E8D1"))))
 '(show-paren-mismatch-face ((t (:foreground "#E65A7C" :background "#252623"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#5B5E5A" :background "#3A3D37" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#8FB573"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#57A5E4"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#DAB651"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#FF9966"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#F0E8D1"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#B94863"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#8FB573" :background "#2F312C" :overline "#E1C692"))))
 '(org-level-2 ((t (:foreground "#63B07A" :background "#2F312C" :overline "#5B5E5A"))))
 '(org-level-3 ((t (:foreground "#63B07A" :background "#2F312C" :overline "#E1C692"))))
 '(org-level-4 ((t (:foreground "#509475" :background "#2F312C" :overline "#5B5E5A"))))
 '(org-level-5 ((t (:foreground "#509475" :background "#2F312C" :overline "#E1C692"))))
 '(org-level-6 ((t (:foreground "#509475" :background "#2F312C" :overline "#5B5E5A"))))
 '(org-level-7 ((t (:foreground "#509475" :background "#2F312C" :overline "#E1C692"))))
 '(org-tag ((t (:foreground "#B94863"))))
 '(org-headline-done ((t (:foreground "#549E6A" :background "#3A3D37"))))
 '(org-done ((t (:foreground "#F0E8D1"))))
 '(org-todo ((t (:foreground "#DAB651"))))
 '(org-checkbox ((t (:foreground "#F5F4DC" :background "#383B35"))))
 '(org-link ((t (:foreground "#70C1BE" :background "#252623" :underline nil))))
 '(org-verbatim ((t (:foreground "#CBD5AE"))))
 '(org-code ((t (:foreground "#CBD5AE"))))
 '(org-table ((t (:foreground "#CBD5AE" :background "#383B35"))))
 '(org-date ((t (:foreground "#63B07A" :underline t))))
 '(org-archived ((t (:foreground "#5B5E5A" :background "#3A3D37"))))
 '(org-list-dt ((t (:foreground "#F5F4DC"))))
 '(org-drawer ((t (:foreground "#AAAAFF"))))
 '(org-special-keyword ((t (:foreground "#838781"))))
 '(org-property-value ((t (:foreground "#F0E8D1" :background "#252623"))))
 '(org-block ((t (:background "#2F312C" :extend t))))
 '(org-block-begin-line ((t (:foreground "#E1C692" :background "#252623" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#838781"))))
 '(org-superstar-header-bullet ((t (:foreground "#F5F4DC" :background "#383B35" :overline t))))
 '(org-superstar-item ((t (:foreground "#DAB651"))))
 '(org-superstar-ordered-item ((t (:foreground "#B94863"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#CBD5AE" :height 220 :underline "#8FB573"))))
 '(markdown-header-face-2 ((t (:foreground "#CBD5AE" :height 180 :underline "#8FB573"))))
 '(markdown-header-face-3 ((t (:foreground "#CBD5AE" :underline "#F0E8D1"))))
 '(markdown-header-face-4 ((t (:foreground "#CBD5AE"))))
 '(markdown-header-face-5 ((t (:foreground "#CBD5AE"))))
 '(markdown-header-face-6 ((t (:foreground "#CBD5AE"))))
 '(markdown-list-face ((t (:foreground "#DAB651"))))
 '(markdown-inline-code-face ((t (:foreground "#CBD5AE" :background "#3A3D37"))))
 '(markdown-language-keyword-face ((t (:foreground "#B94863"))))
 '(markdown-pre-face ((t (:foreground "#CBD5AE"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#5B5E5A"))))
 '(markdown-header-delimiter-face ((t (:foreground "#838781"))))
 '(markdown-bold-face ((t (:foreground "#CBD5AE" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#CBD5AE" :slant italic))))
 '(markdown-link-face ((t (:foreground "#CBD5AE"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#8FB573"))))
 '(compilation-warning ((t (:foreground "#8FB573"))))
 '(compilation-error ((t (:foreground "#E65A7C"))))
 '(compilation-line-number ((t (:foreground "#CBD5AE" :underline t))))
 '(compilation-column-number ((t (:foreground "#CBD5AE" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#E65A7C"))))
 '(flycheck-fringe-warning ((t (:foreground "#8FB573"))))
 '(flycheck-fringe-info ((t (:foreground "#8FB573"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#383B35"))))
 '(lsp-face-highlight-textual ((t (:background "#111C18"))))
 '(lsp-face-highlight-write ((t (:background "#111C18"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#111C18"))))
 '(eglot-inlay-hint-face ((t (:foreground "#CBD5AE" :background "#3A3D37" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#CBD5AE"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#F0E8D1" :background "#383B35"))))
 '(company-preview-common ((t (:foreground "#CBD5AE" :background "#383B35"))))
 '(company-preview-search ((t (:foreground "#CBD5AE" :background "#383B35"))))
 '(company-tooltip-common ((t (:foreground "#CBD5AE" :background "#383B35"))))
 '(company-tooltip-common-selection ((t (:foreground "#CBD5AE" :background "#383B35"))))
 '(company-tooltip-annotation ((t (:foreground "#CBD5AE" :background "#383B35"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#CBD5AE" :background "#383B35"))))
 '(company-tooltip-search-selection ((t (:foreground "#CBD5AE" :background "#111C18"))))
 '(company-tooltip-mouse ((t (:foreground "#CBD5AE" :background "#111C18"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#F0E8D1" :background "#3A3D37"))))
 '(magit-branch-current ((t (:foreground "#8FB573" :box 1))))
 '(magit-branch-remote ((t (:foreground "#8FB573" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#AAAAFF"))))
 '(rg-line-number-face ((t (:foreground "#CBD5AE"))))

 ;; line numbers
 '(line-number ((t (:foreground "#E1C692" :background "#252623"))))
 '(line-number-current-line ((t (:foreground "#5B5E5A" :background "#252623"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#838781"))))
 '(doom-modeline-bar ((t (:background "#383B35"))))
 '(doom-modeline-bar-inactive ((t (:background "#252623"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#B94863" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#549E6A"))))
 '(doom-modeline-project-dir ((t (:foreground "#F0E8D1"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#F0E8D1"))))
 '(doom-modeline-urgent ((t (:foreground "#AAAAFF"))))
 '(doom-modeline-info ((t (:foreground "#F0E8D1"))))
 '(doom-modeline-warning ((t (:foreground "#549E6A"))))
 '(doom-modeline-error ((t (:foreground "#E65A7C"))))
 '(doom-modeline-inactive-bar ((t (:background "#252623"))))
 '(mode-line ((t (:foreground "#5B5E5A" :background "#383B35"))))
 '(mode-line-inactive ((t (:background "#383B35"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#5B5E5A"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#5B5E5A"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#838781" :background "#252623"))))
 '(tab-bar-tab ((t (:foreground "#63B07A" :background "#252623" :box (:line-width 2 :color "#252623")))))
 '(tab-bar-tab-inactive ((t (:foreground "#838781" :background "#252623"))))

 ;; misc
 '(secondary-selection ((t (:background "#2F312C"))))
 '(shadow ((t (:foreground "#838781")))))

(provide-theme 'osaka-jade)
