
;;; retro-82-theme.el --- Generated by Book of Colours

(deftheme retro-82 "retro-82")

(custom-theme-set-faces
 'retro-82

 ;; common
 '(default ((t (:foreground "#F5DBAC" :background "#00172E"))))
 '(cursor ((t (:foreground "#05182E" :background "#F5DBAC"))))
 '(region ((t (:foreground "#F9A968" :background "#00172E"))))
 '(hl-line ((t (:background "#0A3A45"))))
 '(minibuffer-prompt ((t (:foreground "#5F8F96"))))
 '(link ((t (:foreground "#8CBFB8" :underline t))))
 '(warning ((t (:foreground "#F5DBAC"))))
 '(error ((t (:foreground "#FFF0D9"))))
 '(success ((t (:foreground "#8CBFB8"))))
 '(bold ((t (:foreground "#FFF0D9" :weight bold))))
 '(isearch ((t (:foreground "#F9A968" :background "#00172E"))))
 '(lazy-highlight ((t (:foreground "#F5DBAC" :background "#00172E"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#F5DBAC" :background "#05182E" :weight bold))))
 '(tooltip ((t (:foreground "#F9A968" :background "#05182E" :weight bold))))
 '(fringe ((t (:background "#00172E"))))
 '(vertical-border ((t (:foreground "#0A3A45"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#F9A968"))))
 '(header-line ((t (:foreground "#5F8F96" :background "#05182E"))))
 '(header-line-highlight ((t (:foreground "#FFF0D9" :background "#05182E"))))
 '(highlight ((t (:foreground "#FFF0D9" :background "#00172E"))))
 '(button ((t (:foreground "#3F8F8A" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#5F8F96" :background "#05182E" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#F5DBAC" :background "#05182E" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#F5DBAC"))))
 '(font-lock-type-face ((t (:foreground "#8CBFB8"))))
 '(font-lock-preprocessor-face ((t (:foreground "#E87B3C"))))
 '(font-lock-operator-face ((t (:foreground "#8CBFB8"))))
 '(font-lock-string-face ((t (:foreground "#028391"))))
 '(font-lock-variable-name-face ((t (:foreground "#F5DBAC"))))
 '(font-lock-constant-face ((t (:foreground "#F9A968"))))
 '(font-lock-keyword-face ((t (:foreground "#3F8F8A"))))
 '(font-lock-warning-face ((t (:foreground "#F5DBAC"))))
 '(font-lock-function-name-face ((t (:foreground "#E87B3C"))))
 '(font-lock-negation-char-face ((t (:foreground "#8CBFB8"))))
 '(font-lock-variable-use-face ((t (:foreground "#F9A968"))))
 '(font-lock-property-use-face ((t (:foreground "#F5DBAC"))))
 '(font-lock-number-face ((t (:foreground "#F9A968"))))
 '(font-lock-bracket-face ((t (:foreground "#5F8F96"))))
 '(font-lock-delimiter-face ((t (:foreground "#5F8F96"))))
 '(font-lock-escape-face ((t (:foreground "#FFF0D9"))))
 '(show-paren-match ((t (:foreground "#F5DBAC"))))
 '(show-paren-mismatch-face ((t (:foreground "#F5DBAC" :background "#05182E"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#5F8F96" :background "#05182E" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#028391"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#E87B3C"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#8CBFB8"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#F9A968"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#F9A968"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#F5DBAC"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#F9A968" :background "#0A3A45" :overline "#5F8F96"))))
 '(org-level-2 ((t (:foreground "#E87B3C" :background "#0A3A45" :overline "#5F8F96"))))
 '(org-level-3 ((t (:foreground "#E87B3C" :background "#0A3A45" :overline "#5F8F96"))))
 '(org-level-4 ((t (:foreground "#E87B3C" :background "#0A3A45" :overline "#5F8F96"))))
 '(org-level-5 ((t (:foreground "#E87B3C" :background "#0A3A45" :overline "#5F8F96"))))
 '(org-level-6 ((t (:foreground "#E87B3C" :background "#0A3A45" :overline "#5F8F96"))))
 '(org-level-7 ((t (:foreground "#E87B3C" :background "#0A3A45" :overline "#5F8F96"))))
 '(org-tag ((t (:foreground "#F5DBAC"))))
 '(org-headline-done ((t (:foreground "#3F8F8A" :background "#05182E"))))
 '(org-done ((t (:foreground "#F5DBAC"))))
 '(org-todo ((t (:foreground "#F5DBAC"))))
 '(org-checkbox ((t (:foreground "#FFF0D9" :background "#0A3A45"))))
 '(org-link ((t (:foreground "#8CBFB8" :background "#00172E" :underline nil))))
 '(org-verbatim ((t (:foreground "#FFF0D9"))))
 '(org-code ((t (:foreground "#FFF0D9"))))
 '(org-table ((t (:foreground "#FFF0D9" :background "#05182E"))))
 '(org-date ((t (:foreground "#E87B3C" :underline t))))
 '(org-archived ((t (:foreground "#5F8F96" :background "#05182E"))))
 '(org-list-dt ((t (:foreground "#F5DBAC"))))
 '(org-drawer ((t (:foreground "#E87B3C"))))
 '(org-special-keyword ((t (:foreground "#5F8F96"))))
 '(org-property-value ((t (:foreground "#F9A968" :background "#00172E"))))
 '(org-block ((t (:background "#0A3A45" :extend t))))
 '(org-block-begin-line ((t (:foreground "#5F8F96" :background "#05182E" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#5F8F96"))))
 '(org-superstar-header-bullet ((t (:foreground "#FFF0D9" :background "#05182E" :overline t))))
 '(org-superstar-item ((t (:foreground "#F5DBAC"))))
 '(org-superstar-ordered-item ((t (:foreground "#F5DBAC"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#FFF0D9" :height 220 :underline "#F9A968"))))
 '(markdown-header-face-2 ((t (:foreground "#FFF0D9" :height 180 :underline "#F9A968"))))
 '(markdown-header-face-3 ((t (:foreground "#FFF0D9" :underline "#F5DBAC"))))
 '(markdown-header-face-4 ((t (:foreground "#FFF0D9"))))
 '(markdown-header-face-5 ((t (:foreground "#FFF0D9"))))
 '(markdown-header-face-6 ((t (:foreground "#FFF0D9"))))
 '(markdown-list-face ((t (:foreground "#F5DBAC"))))
 '(markdown-inline-code-face ((t (:foreground "#FFF0D9" :background "#05182E"))))
 '(markdown-language-keyword-face ((t (:foreground "#F5DBAC"))))
 '(markdown-pre-face ((t (:foreground "#FFF0D9"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#5F8F96"))))
 '(markdown-header-delimiter-face ((t (:foreground "#5F8F96"))))
 '(markdown-bold-face ((t (:foreground "#FFF0D9" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#FFF0D9" :slant italic))))
 '(markdown-link-face ((t (:foreground "#FFF0D9"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#F9A968"))))
 '(compilation-warning ((t (:foreground "#F9A968"))))
 '(compilation-error ((t (:foreground "#FFF0D9"))))
 '(compilation-line-number ((t (:foreground "#FFF0D9" :underline t))))
 '(compilation-column-number ((t (:foreground "#FFF0D9" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#F5DBAC"))))
 '(flycheck-fringe-warning ((t (:foreground "#F9A968"))))
 '(flycheck-fringe-info ((t (:foreground "#F9A968"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#05182E"))))
 '(lsp-face-highlight-textual ((t (:background "#00172E"))))
 '(lsp-face-highlight-write ((t (:background "#00172E"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#00172E"))))
 '(eglot-inlay-hint-face ((t (:foreground "#FFF0D9" :background "#05182E" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#FFF0D9"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#F9A968" :background "#05182E"))))
 '(company-preview-common ((t (:foreground "#FFF0D9" :background "#05182E"))))
 '(company-preview-search ((t (:foreground "#FFF0D9" :background "#05182E"))))
 '(company-tooltip-common ((t (:foreground "#FFF0D9" :background "#05182E"))))
 '(company-tooltip-common-selection ((t (:foreground "#FFF0D9" :background "#05182E"))))
 '(company-tooltip-annotation ((t (:foreground "#FFF0D9" :background "#05182E"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#FFF0D9" :background "#05182E"))))
 '(company-tooltip-search-selection ((t (:foreground "#FFF0D9" :background "#00172E"))))
 '(company-tooltip-mouse ((t (:foreground "#FFF0D9" :background "#00172E"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#F5DBAC" :background "#05182E"))))
 '(magit-branch-current ((t (:foreground "#F9A968" :box 1))))
 '(magit-branch-remote ((t (:foreground "#F9A968" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#3F8F8A"))))
 '(rg-line-number-face ((t (:foreground "#FFF0D9"))))

 ;; line numbers
 '(line-number ((t (:foreground "#5F8F96" :background "#05182E"))))
 '(line-number-current-line ((t (:foreground "#5F8F96" :background "#05182E"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#176B73"))))
 '(doom-modeline-bar ((t (:background "#05182E"))))
 '(doom-modeline-bar-inactive ((t (:background "#00172E"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#F5DBAC" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#3F8F8A"))))
 '(doom-modeline-project-dir ((t (:foreground "#F9A968"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#F5DBAC"))))
 '(doom-modeline-urgent ((t (:foreground "#3F8F8A"))))
 '(doom-modeline-info ((t (:foreground "#F9A968"))))
 '(doom-modeline-warning ((t (:foreground "#3F8F8A"))))
 '(doom-modeline-error ((t (:foreground "#FFF0D9"))))
 '(doom-modeline-inactive-bar ((t (:background "#05182E"))))
 '(mode-line ((t (:foreground "#0A3A45" :background "#05182E"))))
 '(mode-line-inactive ((t (:background "#05182E"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#0A3A45"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#0A3A45"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#5F8F96" :background "#05182E"))))
 '(tab-bar-tab ((t (:foreground "#E87B3C" :background "#00172E" :box (:line-width 2 :color "#00172E")))))
 '(tab-bar-tab-inactive ((t (:foreground "#5F8F96" :background "#05182E"))))

 ;; misc
 '(secondary-selection ((t (:background "#0A3A45"))))
 '(shadow ((t (:foreground "#5F8F96")))))

(provide-theme 'retro-82)
