
;;; ristretto-theme.el --- Generated by Book of Colours

(deftheme ristretto "ristretto")

(custom-theme-set-faces
 'ristretto

 ;; common
 '(default ((t (:foreground "#FFF0F2" :background "#2C2525"))))
 '(cursor ((t (:foreground "#2C2525" :background "#FFF0F2"))))
 '(region ((t (:foreground "#E5D8DA" :background "#403E41"))))
 '(hl-line ((t (:background "#211C1C"))))
 '(minibuffer-prompt ((t (:foreground "#948A8B"))))
 '(link ((t (:foreground "#94E8DA" :underline t))))
 '(warning ((t (:foreground "#F28D70"))))
 '(error ((t (:foreground "#FC6883"))))
 '(success ((t (:foreground "#819E5B"))))
 '(bold ((t (:foreground "#F8CB6C" :weight bold))))
 '(isearch ((t (:foreground "#E5D8DA" :background "#403E41"))))
 '(lazy-highlight ((t (:foreground "#E5D8DA" :background "#403E41"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#F28D70" :background "#362724" :weight bold))))
 '(tooltip ((t (:foreground "#ADD978" :background "#362E2E" :weight bold))))
 '(fringe ((t (:background "#2C2525"))))
 '(vertical-border ((t (:foreground "#191515"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#FFF0F2"))))
 '(header-line ((t (:foreground "#948A8B" :background "#362724"))))
 '(header-line-highlight ((t (:foreground "#F8CB6C" :background "#362724"))))
 '(highlight ((t (:foreground "#C7E192" :background "#403E41"))))
 '(button ((t (:foreground "#B85062" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#948A8B" :background "#362E2E" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#FFF0F2" :background "#362E2E" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#E5D8DA"))))
 '(font-lock-type-face ((t (:foreground "#85D9CB"))))
 '(font-lock-preprocessor-face ((t (:foreground "#FC6883"))))
 '(font-lock-operator-face ((t (:foreground "#FC6883"))))
 '(font-lock-string-face ((t (:foreground "#F8CB6C"))))
 '(font-lock-variable-name-face ((t (:foreground "#FFF0F2"))))
 '(font-lock-constant-face ((t (:foreground "#F8CB6C"))))
 '(font-lock-keyword-face ((t (:foreground "#B85062"))))
 '(font-lock-warning-face ((t (:foreground "#F28D70"))))
 '(font-lock-function-name-face ((t (:foreground "#ADD978"))))
 '(font-lock-negation-char-face ((t (:foreground "#FC6883"))))
 '(font-lock-variable-use-face ((t (:foreground "#FFF0F2"))))
 '(font-lock-property-use-face ((t (:foreground "#FFF0F2"))))
 '(font-lock-number-face ((t (:foreground "#BEBFFC"))))
 '(font-lock-bracket-face ((t (:foreground "#FC6883"))))
 '(font-lock-delimiter-face ((t (:foreground "#948A8B"))))
 '(font-lock-escape-face ((t (:foreground "#F8CB6C"))))
 '(show-paren-match ((t (:foreground "#F8CB6C"))))
 '(show-paren-mismatch-face ((t (:foreground "#FC6883" :background "#2C2525"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#948A8B" :background "#362E2E" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#F8CB6C"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#ADD978"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#85D9CB"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#F8CB6C"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#FFF0F2"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#FFF0F2"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#ADD978" :background "#211C1C" :overline "#948A8B"))))
 '(org-level-2 ((t (:foreground "#819E5B" :background "#211C1C" :overline "#948A8B"))))
 '(org-level-3 ((t (:foreground "#819E5B" :background "#211C1C" :overline "#948A8B"))))
 '(org-level-4 ((t (:foreground "#E5D8DA" :background "#211C1C" :overline "#948A8B"))))
 '(org-level-5 ((t (:foreground "#E5D8DA" :background "#211C1C" :overline "#948A8B"))))
 '(org-level-6 ((t (:foreground "#E5D8DA" :background "#211C1C" :overline "#948A8B"))))
 '(org-level-7 ((t (:foreground "#E5D8DA" :background "#211C1C" :overline "#948A8B"))))
 '(org-tag ((t (:foreground "#FFF0F2"))))
 '(org-headline-done ((t (:foreground "#B85062" :background "#362E2E"))))
 '(org-done ((t (:foreground "#FFF0F2"))))
 '(org-todo ((t (:foreground "#F28D70"))))
 '(org-checkbox ((t (:foreground "#C7E192" :background "#2C2525"))))
 '(org-link ((t (:foreground "#94E8DA" :background "#2C2525" :underline nil))))
 '(org-verbatim ((t (:foreground "#F8CB6C"))))
 '(org-code ((t (:foreground "#F8CB6C"))))
 '(org-table ((t (:foreground "#F8CB6C" :background "#362724"))))
 '(org-date ((t (:foreground "#819E5B" :underline t))))
 '(org-archived ((t (:foreground "#948A8B" :background "#362E2E"))))
 '(org-list-dt ((t (:foreground "#E5D8DA"))))
 '(org-drawer ((t (:foreground "#FC6883"))))
 '(org-special-keyword ((t (:foreground "#72696A"))))
 '(org-property-value ((t (:foreground "#FFF0F2" :background "#2C2525"))))
 '(org-block ((t (:background "#211C1C" :extend t))))
 '(org-block-begin-line ((t (:foreground "#948A8B" :background "#2C2525" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#948A8B"))))
 '(org-superstar-header-bullet ((t (:foreground "#C7E192" :background "#362724" :overline t))))
 '(org-superstar-item ((t (:foreground "#F28D70"))))
 '(org-superstar-ordered-item ((t (:foreground "#FFF0F2"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#F8CB6C" :height 220 :underline "#ADD978"))))
 '(markdown-header-face-2 ((t (:foreground "#F8CB6C" :height 180 :underline "#ADD978"))))
 '(markdown-header-face-3 ((t (:foreground "#F8CB6C" :underline "#FFF0F2"))))
 '(markdown-header-face-4 ((t (:foreground "#F8CB6C"))))
 '(markdown-header-face-5 ((t (:foreground "#F8CB6C"))))
 '(markdown-header-face-6 ((t (:foreground "#F8CB6C"))))
 '(markdown-list-face ((t (:foreground "#F28D70"))))
 '(markdown-inline-code-face ((t (:foreground "#F8CB6C" :background "#362E2E"))))
 '(markdown-language-keyword-face ((t (:foreground "#FFF0F2"))))
 '(markdown-pre-face ((t (:foreground "#F8CB6C"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#948A8B"))))
 '(markdown-header-delimiter-face ((t (:foreground "#FFF0F2"))))
 '(markdown-bold-face ((t (:foreground "#F8CB6C" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#F8CB6C" :slant italic))))
 '(markdown-link-face ((t (:foreground "#F8CB6C"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#ADD978"))))
 '(compilation-warning ((t (:foreground "#ADD978"))))
 '(compilation-error ((t (:foreground "#FC6883"))))
 '(compilation-line-number ((t (:foreground "#F8CB6C" :underline t))))
 '(compilation-column-number ((t (:foreground "#F8CB6C" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#FC6883"))))
 '(flycheck-fringe-warning ((t (:foreground "#ADD978"))))
 '(flycheck-fringe-info ((t (:foreground "#ADD978"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#362724"))))
 '(lsp-face-highlight-textual ((t (:background "#403E41"))))
 '(lsp-face-highlight-write ((t (:background "#403E41"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#403E41"))))
 '(eglot-inlay-hint-face ((t (:foreground "#F8CB6C" :background "#362E2E" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#F8CB6C"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#FFF0F2" :background "#362724"))))
 '(company-preview-common ((t (:foreground "#F8CB6C" :background "#362724"))))
 '(company-preview-search ((t (:foreground "#F8CB6C" :background "#362724"))))
 '(company-tooltip-common ((t (:foreground "#F8CB6C" :background "#362724"))))
 '(company-tooltip-common-selection ((t (:foreground "#F8CB6C" :background "#362724"))))
 '(company-tooltip-annotation ((t (:foreground "#F8CB6C" :background "#362724"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#F8CB6C" :background "#362724"))))
 '(company-tooltip-search-selection ((t (:foreground "#F8CB6C" :background "#403E41"))))
 '(company-tooltip-mouse ((t (:foreground "#F8CB6C" :background "#403E41"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#FFF0F2" :background "#362E2E"))))
 '(magit-branch-current ((t (:foreground "#ADD978" :box 1))))
 '(magit-branch-remote ((t (:foreground "#ADD978" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#B85062"))))
 '(rg-line-number-face ((t (:foreground "#F8CB6C"))))

 ;; line numbers
 '(line-number ((t (:foreground "#948A8B" :background "#2C2525"))))
 '(line-number-current-line ((t (:foreground "#948A8B" :background "#2C2525"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#72696A"))))
 '(doom-modeline-bar ((t (:background "#362724"))))
 '(doom-modeline-bar-inactive ((t (:background "#2C2525"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#FFF0F2" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#B85062"))))
 '(doom-modeline-project-dir ((t (:foreground "#FFF0F2"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#FFF0F2"))))
 '(doom-modeline-urgent ((t (:foreground "#B85062"))))
 '(doom-modeline-info ((t (:foreground "#FFF0F2"))))
 '(doom-modeline-warning ((t (:foreground "#B85062"))))
 '(doom-modeline-error ((t (:foreground "#FC6883"))))
 '(doom-modeline-inactive-bar ((t (:background "#2C2525"))))
 '(mode-line ((t (:foreground "#5B5353" :background "#362724"))))
 '(mode-line-inactive ((t (:background "#362724"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#5B5353"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#5B5353"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#72696A" :background "#2C2525"))))
 '(tab-bar-tab ((t (:foreground "#819E5B" :background "#2C2525" :box (:line-width 2 :color "#2C2525")))))
 '(tab-bar-tab-inactive ((t (:foreground "#948A8B" :background "#2C2525"))))

 ;; misc
 '(secondary-selection ((t (:background "#211C1C"))))
 '(shadow ((t (:foreground "#948A8B")))))

(provide-theme 'ristretto)
