
;;; rose-pine-theme.el --- Generated by Book of Colours

(deftheme rose-pine "rose-pine")

(custom-theme-set-faces
 'rose-pine

 ;; common
 '(default ((t (:foreground "#464261" :background "#F9F3EC"))))
 '(cursor ((t (:foreground "#F9F3EC" :background "#464261"))))
 '(region ((t (:foreground "#575279" :background "#DED9D8"))))
 '(hl-line ((t (:background "#F1E8E0"))))
 '(minibuffer-prompt ((t (:foreground "#9893A5"))))
 '(link ((t (:foreground "#464261" :underline t))))
 '(warning ((t (:foreground "#907AA9"))))
 '(error ((t (:foreground "#B4637A"))))
 '(success ((t (:foreground "#6D8F89"))))
 '(bold ((t (:foreground "#286983" :weight bold))))
 '(isearch ((t (:foreground "#575279" :background "#DED9D8"))))
 '(lazy-highlight ((t (:foreground "#286983" :background "#DED9D8"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#907AA9" :background "#F7EADA" :weight bold))))
 '(tooltip ((t (:foreground "#56949F" :background "#F9F3EC" :weight bold))))
 '(fringe ((t (:background "#F9F3EC"))))
 '(vertical-border ((t (:foreground "#7CA1AD"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#286983"))))
 '(header-line ((t (:foreground "#9893A5" :background "#F7EADA"))))
 '(header-line-highlight ((t (:foreground "#286983" :background "#F7EADA"))))
 '(highlight ((t (:foreground "#286983" :background "#DED9D8"))))
 '(button ((t (:foreground "#464261" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#9893A5" :background "#F9F3EC" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#B4637A" :background "#F9F3EC" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#286983"))))
 '(font-lock-type-face ((t (:foreground "#56949F"))))
 '(font-lock-preprocessor-face ((t (:foreground "#286983"))))
 '(font-lock-operator-face ((t (:foreground "#797593"))))
 '(font-lock-string-face ((t (:foreground "#E99D34"))))
 '(font-lock-variable-name-face ((t (:foreground "#464261"))))
 '(font-lock-constant-face ((t (:foreground "#E99D34"))))
 '(font-lock-keyword-face ((t (:foreground "#464261"))))
 '(font-lock-warning-face ((t (:foreground "#907AA9"))))
 '(font-lock-function-name-face ((t (:foreground "#D6827E"))))
 '(font-lock-negation-char-face ((t (:foreground "#797593"))))
 '(font-lock-variable-use-face ((t (:foreground "#464261"))))
 '(font-lock-property-use-face ((t (:foreground "#286983"))))
 '(font-lock-number-face ((t (:foreground "#E99D34"))))
 '(font-lock-bracket-face ((t (:foreground "#797593"))))
 '(font-lock-delimiter-face ((t (:foreground "#797593"))))
 '(font-lock-escape-face ((t (:foreground "#286983"))))
 '(show-paren-match ((t (:foreground "#464261"))))
 '(show-paren-mismatch-face ((t (:foreground "#B4637A" :background "#F9F3EC"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#9893A5" :background "#F9F3EC" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#E99D34"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#D6827E"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#56949F"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#E99D34"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#B4637A"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#464261"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#56949F" :background "#F1E8E0" :overline "#9893A5"))))
 '(org-level-2 ((t (:foreground "#797593" :background "#F1E8E0" :overline "#9893A5"))))
 '(org-level-3 ((t (:foreground "#797593" :background "#F1E8E0" :overline "#9893A5"))))
 '(org-level-4 ((t (:foreground "#56949F" :background "#F1E8E0" :overline "#9893A5"))))
 '(org-level-5 ((t (:foreground "#56949F" :background "#F1E8E0" :overline "#9893A5"))))
 '(org-level-6 ((t (:foreground "#56949F" :background "#F1E8E0" :overline "#9893A5"))))
 '(org-level-7 ((t (:foreground "#56949F" :background "#F1E8E0" :overline "#9893A5"))))
 '(org-tag ((t (:foreground "#464261"))))
 '(org-headline-done ((t (:foreground "#464261" :background "#F9F3EC"))))
 '(org-done ((t (:foreground "#464261"))))
 '(org-todo ((t (:foreground "#E99D34"))))
 '(org-checkbox ((t (:foreground "#286983" :background "#DED9D8"))))
 '(org-link ((t (:foreground "#464261" :background "#F9F3EC" :underline nil))))
 '(org-verbatim ((t (:foreground "#286983"))))
 '(org-code ((t (:foreground "#286983"))))
 '(org-table ((t (:foreground "#286983" :background "#F7EADA"))))
 '(org-date ((t (:foreground "#797593" :underline t))))
 '(org-archived ((t (:foreground "#9893A5" :background "#F9F3EC"))))
 '(org-list-dt ((t (:foreground "#286983"))))
 '(org-drawer ((t (:foreground "#286983"))))
 '(org-special-keyword ((t (:foreground "#797593"))))
 '(org-property-value ((t (:foreground "#286983" :background "#F9F3EC"))))
 '(org-block ((t (:background "#F1E8E0" :extend t))))
 '(org-block-begin-line ((t (:foreground "#9893A5" :background "#F9F3EC" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#797593"))))
 '(org-superstar-header-bullet ((t (:foreground "#286983" :background "#F7EADA" :overline t))))
 '(org-superstar-item ((t (:foreground "#907AA9"))))
 '(org-superstar-ordered-item ((t (:foreground "#464261"))))
 '(org-hide ((t (:foreground "#F9F3EC"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#286983" :height 220 :underline "#56949F"))))
 '(markdown-header-face-2 ((t (:foreground "#286983" :height 180 :underline "#56949F"))))
 '(markdown-header-face-3 ((t (:foreground "#286983" :underline "#B4637A"))))
 '(markdown-header-face-4 ((t (:foreground "#286983"))))
 '(markdown-header-face-5 ((t (:foreground "#286983"))))
 '(markdown-header-face-6 ((t (:foreground "#286983"))))
 '(markdown-list-face ((t (:foreground "#907AA9"))))
 '(markdown-inline-code-face ((t (:foreground "#286983" :background "#F9F3EC"))))
 '(markdown-language-keyword-face ((t (:foreground "#464261"))))
 '(markdown-pre-face ((t (:foreground "#286983"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#9893A5"))))
 '(markdown-header-delimiter-face ((t (:foreground "#797593"))))
 '(markdown-bold-face ((t (:foreground "#286983" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#286983" :slant italic))))
 '(markdown-link-face ((t (:foreground "#286983"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#56949F"))))
 '(compilation-warning ((t (:foreground "#56949F"))))
 '(compilation-error ((t (:foreground "#B4637A"))))
 '(compilation-line-number ((t (:foreground "#286983" :underline t))))
 '(compilation-column-number ((t (:foreground "#286983" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#B4637A"))))
 '(flycheck-fringe-warning ((t (:foreground "#56949F"))))
 '(flycheck-fringe-info ((t (:foreground "#56949F"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#F7EADA"))))
 '(lsp-face-highlight-textual ((t (:background "#DED9D8"))))
 '(lsp-face-highlight-write ((t (:background "#DED9D8"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#DED9D8"))))
 '(eglot-inlay-hint-face ((t (:foreground "#286983" :background "#F9F3EC" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#286983"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#464261" :background "#F7EADA"))))
 '(company-preview-common ((t (:foreground "#286983" :background "#F7EADA"))))
 '(company-preview-search ((t (:foreground "#286983" :background "#F7EADA"))))
 '(company-tooltip-common ((t (:foreground "#286983" :background "#F7EADA"))))
 '(company-tooltip-common-selection ((t (:foreground "#286983" :background "#F7EADA"))))
 '(company-tooltip-annotation ((t (:foreground "#286983" :background "#F7EADA"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#286983" :background "#F7EADA"))))
 '(company-tooltip-search-selection ((t (:foreground "#286983" :background "#DED9D8"))))
 '(company-tooltip-mouse ((t (:foreground "#286983" :background "#DED9D8"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#286983" :background "#F9F3EC"))))
 '(magit-branch-current ((t (:foreground "#56949F" :box 1))))
 '(magit-branch-remote ((t (:foreground "#56949F" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#464261"))))
 '(rg-line-number-face ((t (:foreground "#286983"))))

 ;; line numbers
 '(line-number ((t (:foreground "#9893A5" :background "#F9F3EC"))))
 '(line-number-current-line ((t (:foreground "#9893A5" :background "#F9F3EC"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#9893A5"))))
 '(doom-modeline-bar ((t (:background "#F7EADA"))))
 '(doom-modeline-bar-inactive ((t (:background "#F9F3EC"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#464261" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#464261"))))
 '(doom-modeline-project-dir ((t (:foreground "#B4637A"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#464261"))))
 '(doom-modeline-urgent ((t (:foreground "#464261"))))
 '(doom-modeline-info ((t (:foreground "#286983"))))
 '(doom-modeline-warning ((t (:foreground "#464261"))))
 '(doom-modeline-error ((t (:foreground "#B4637A"))))
 '(doom-modeline-inactive-bar ((t (:background "#F9F3EC"))))
 '(mode-line ((t (:foreground "#EFE9E5" :background "#F7EADA"))))
 '(mode-line-inactive ((t (:background "#F7EADA"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#EFE9E5"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#EFE9E5"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#797593" :background "#F9F3EC"))))
 '(tab-bar-tab ((t (:foreground "#797593" :background "#F9F3EC" :box (:line-width 2 :color "#F9F3EC")))))
 '(tab-bar-tab-inactive ((t (:foreground "#797593" :background "#F9F3EC"))))

 ;; misc
 '(secondary-selection ((t (:background "#F1E8E0"))))
 '(shadow ((t (:foreground "#797593")))))

(provide-theme 'rose-pine)
