
;;; solitude-theme.el --- Generated by Book of Colours

(deftheme solitude "solitude")

(custom-theme-set-faces
 'solitude

 ;; common
 '(default ((t (:foreground "#C9CBCB" :background "#121212"))))
 '(cursor ((t (:foreground "#101315" :background "#B4B4B4"))))
 '(region ((t (:foreground "#A5AEB4" :background "#343D41"))))
 '(hl-line ((t (:background "#101315"))))
 '(minibuffer-prompt ((t (:foreground "#737373"))))
 '(link ((t (:foreground "#4A8B8B" :underline t))))
 '(warning ((t (:foreground "#E4A72A"))))
 '(error ((t (:foreground "#C43030"))))
 '(success ((t (:foreground "#629C7D"))))
 '(bold ((t (:foreground "#E4E4E4" :weight bold))))
 '(isearch ((t (:foreground "#A5AEB4" :background "#343D41"))))
 '(lazy-highlight ((t (:foreground "#798186" :background "#343D41"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#E4A72A" :background "#212121" :weight bold))))
 '(tooltip ((t (:foreground "#629C7D" :background "#212121" :weight bold))))
 '(fringe ((t (:background "#121212"))))
 '(vertical-border ((t (:foreground "#323232"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#C9CBCB"))))
 '(header-line ((t (:foreground "#737373" :background "#212121"))))
 '(header-line-highlight ((t (:foreground "#E4E4E4" :background "#212121"))))
 '(highlight ((t (:foreground "#798186" :background "#343D41"))))
 '(button ((t (:foreground "#4A8B8B" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#737373" :background "#212121" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#C9CBCB" :background "#212121" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#798186"))))
 '(font-lock-type-face ((t (:foreground "#4A8B8B"))))
 '(font-lock-preprocessor-face ((t (:foreground "#BD4C4C"))))
 '(font-lock-operator-face ((t (:foreground "#629C7D"))))
 '(font-lock-string-face ((t (:foreground "#C43030"))))
 '(font-lock-variable-name-face ((t (:foreground "#B4B4B4"))))
 '(font-lock-constant-face ((t (:foreground "#C3693D"))))
 '(font-lock-keyword-face ((t (:foreground "#BD4C4C"))))
 '(font-lock-warning-face ((t (:foreground "#E4A72A"))))
 '(font-lock-function-name-face ((t (:foreground "#B4B4B4"))))
 '(font-lock-negation-char-face ((t (:foreground "#629C7D"))))
 '(font-lock-variable-use-face ((t (:foreground "#C9CBCB"))))
 '(font-lock-property-use-face ((t (:foreground "#C9CBCB"))))
 '(font-lock-number-face ((t (:foreground "#C3693D"))))
 '(font-lock-bracket-face ((t (:foreground "#E39A44"))))
 '(font-lock-delimiter-face ((t (:foreground "#535353"))))
 '(font-lock-escape-face ((t (:foreground "#E4E4E4"))))
 '(show-paren-match ((t (:foreground "#737373"))))
 '(show-paren-mismatch-face ((t (:foreground "#C43030" :background "#101315"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#737373" :background "#212121" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#C43030"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#B4B4B4"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#4A8B8B"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#C3693D"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#C9CBCB"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#B4B4B4"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#C8C1B4" :background "#101315" :overline "#737373"))))
 '(org-level-2 ((t (:foreground "#4A8B8B" :background "#101315" :overline "#737373"))))
 '(org-level-3 ((t (:foreground "#4A8B8B" :background "#101315" :overline "#737373"))))
 '(org-level-4 ((t (:foreground "#3A6E6E" :background "#101315" :overline "#737373"))))
 '(org-level-5 ((t (:foreground "#3A6E6E" :background "#101315" :overline "#737373"))))
 '(org-level-6 ((t (:foreground "#3A6E6E" :background "#101315" :overline "#737373"))))
 '(org-level-7 ((t (:foreground "#3A6E6E" :background "#101315" :overline "#737373"))))
 '(org-tag ((t (:foreground "#B4B4B4"))))
 '(org-headline-done ((t (:foreground "#4A8B8B" :background "#212121"))))
 '(org-done ((t (:foreground "#C9CBCB"))))
 '(org-todo ((t (:foreground "#E4A72A"))))
 '(org-checkbox ((t (:foreground "#798186" :background "#101315"))))
 '(org-link ((t (:foreground "#4A8B8B" :background "#121212" :underline nil))))
 '(org-verbatim ((t (:foreground "#E4E4E4"))))
 '(org-code ((t (:foreground "#E4E4E4"))))
 '(org-table ((t (:foreground "#E4E4E4" :background "#212121"))))
 '(org-date ((t (:foreground "#4A8B8B" :underline t))))
 '(org-archived ((t (:foreground "#737373" :background "#212121"))))
 '(org-list-dt ((t (:foreground "#798186"))))
 '(org-drawer ((t (:foreground "#BD4C4C"))))
 '(org-special-keyword ((t (:foreground "#535353"))))
 '(org-property-value ((t (:foreground "#C9CBCB" :background "#121212"))))
 '(org-block ((t (:background "#101315" :extend t))))
 '(org-block-begin-line ((t (:foreground "#737373" :background "#101315" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#535353"))))
 '(org-superstar-header-bullet ((t (:foreground "#798186" :background "#212121" :overline t))))
 '(org-superstar-item ((t (:foreground "#E4A72A"))))
 '(org-superstar-ordered-item ((t (:foreground "#B4B4B4"))))
 '(org-hide ((t (:foreground "#121212"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#629C7D" :height 220 :underline "#C8C1B4"))))
 '(markdown-header-face-2 ((t (:foreground "#4A8B8B" :height 180 :underline "#629C7D"))))
 '(markdown-header-face-3 ((t (:foreground "#3A6E6E" :underline "#C9CBCB"))))
 '(markdown-header-face-4 ((t (:foreground "#E4E4E4"))))
 '(markdown-header-face-5 ((t (:foreground "#E4E4E4"))))
 '(markdown-header-face-6 ((t (:foreground "#E4E4E4"))))
 '(markdown-list-face ((t (:foreground "#E4A72A"))))
 '(markdown-inline-code-face ((t (:foreground "#E4E4E4" :background "#212121"))))
 '(markdown-language-keyword-face ((t (:foreground "#B4B4B4"))))
 '(markdown-pre-face ((t (:foreground "#E4E4E4"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#737373"))))
 '(markdown-header-delimiter-face ((t (:foreground "#D4D4D4"))))
 '(markdown-bold-face ((t (:foreground "#E4E4E4" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#E4E4E4" :slant italic))))
 '(markdown-link-face ((t (:foreground "#E4E4E4"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#C8C1B4"))))
 '(compilation-warning ((t (:foreground "#629C7D"))))
 '(compilation-error ((t (:foreground "#C43030"))))
 '(compilation-line-number ((t (:foreground "#E4E4E4" :underline t))))
 '(compilation-column-number ((t (:foreground "#E4E4E4" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#C43030"))))
 '(flycheck-fringe-warning ((t (:foreground "#C8C1B4"))))
 '(flycheck-fringe-info ((t (:foreground "#629C7D"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#212121"))))
 '(lsp-face-highlight-textual ((t (:background "#343D41"))))
 '(lsp-face-highlight-write ((t (:background "#343D41"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#343D41"))))
 '(eglot-inlay-hint-face ((t (:foreground "#E4E4E4" :background "#212121" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#E4E4E4"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#C9CBCB" :background "#212121"))))
 '(company-preview-common ((t (:foreground "#E4E4E4" :background "#212121"))))
 '(company-preview-search ((t (:foreground "#E4E4E4" :background "#212121"))))
 '(company-tooltip-common ((t (:foreground "#E4E4E4" :background "#212121"))))
 '(company-tooltip-common-selection ((t (:foreground "#E4E4E4" :background "#212121"))))
 '(company-tooltip-annotation ((t (:foreground "#E4E4E4" :background "#212121"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#E4E4E4" :background "#212121"))))
 '(company-tooltip-search-selection ((t (:foreground "#E4E4E4" :background "#343D41"))))
 '(company-tooltip-mouse ((t (:foreground "#E4E4E4" :background "#343D41"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#C9CBCB" :background "#212121"))))
 '(magit-branch-current ((t (:foreground "#C8C1B4" :box 1))))
 '(magit-branch-remote ((t (:foreground "#629C7D" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#BD4C4C"))))
 '(rg-line-number-face ((t (:foreground "#E4E4E4"))))

 ;; line numbers
 '(line-number ((t (:foreground "#737373" :background "#101315"))))
 '(line-number-current-line ((t (:foreground "#737373" :background "#101315"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#3A6E6E"))))
 '(doom-modeline-bar ((t (:background "#212121"))))
 '(doom-modeline-bar-inactive ((t (:background "#121212"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#B4B4B4" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#4A8B8B"))))
 '(doom-modeline-project-dir ((t (:foreground "#C9CBCB"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#C9CBCB"))))
 '(doom-modeline-urgent ((t (:foreground "#BD4C4C"))))
 '(doom-modeline-info ((t (:foreground "#C9CBCB"))))
 '(doom-modeline-warning ((t (:foreground "#4A8B8B"))))
 '(doom-modeline-error ((t (:foreground "#C43030"))))
 '(doom-modeline-inactive-bar ((t (:background "#101315"))))
 '(mode-line ((t (:foreground "#323232" :background "#212121"))))
 '(mode-line-inactive ((t (:background "#212121"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#323232"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#323232"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#535353" :background "#101315"))))
 '(tab-bar-tab ((t (:foreground "#4A8B8B" :background "#121212" :box (:line-width 2 :color "#121212")))))
 '(tab-bar-tab-inactive ((t (:foreground "#535353" :background "#101315"))))

 ;; misc
 '(secondary-selection ((t (:background "#101315"))))
 '(shadow ((t (:foreground "#535353")))))

(provide-theme 'solitude)
