
;;; tokyo-night-theme.el --- Generated by Book of Colours

(deftheme tokyo-night "tokyo-night")

(custom-theme-set-faces
 'tokyo-night

 ;; common
 '(default ((t (:foreground "#C0C9F4" :background "#1A1B26"))))
 '(cursor ((t (:foreground "#1A1B26" :background "#C0C9F4"))))
 '(region ((t (:foreground "#C0C9F4" :background "#283457"))))
 '(hl-line ((t (:background "#292E42"))))
 '(minibuffer-prompt ((t (:foreground "#545C7E"))))
 '(link ((t (:foreground "#1ABC9C" :underline t))))
 '(warning ((t (:foreground "#DFAF68"))))
 '(error ((t (:foreground "#DA4B4B"))))
 '(success ((t (:foreground "#9FDF44"))))
 '(bold ((t (:foreground "#BB9AF6" :weight bold))))
 '(isearch ((t (:foreground "#7AA2F6" :background "#283457"))))
 '(lazy-highlight ((t (:foreground "#FF9E64" :background "#283457"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#DFAF68" :background "#1A1B26" :weight bold))))
 '(tooltip ((t (:foreground "#9ECD6A" :background "#1A1B26" :weight bold))))
 '(fringe ((t (:background "#1A1B26"))))
 '(vertical-border ((t (:foreground "#283457"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#C0C9F4"))))
 '(header-line ((t (:foreground "#545C7E" :background "#1A1B26"))))
 '(header-line-highlight ((t (:foreground "#BB9AF6" :background "#1A1B26"))))
 '(highlight ((t (:foreground "#FF9E64" :background "#283457"))))
 '(button ((t (:foreground "#BB9AF6" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#545C7E" :background "#1A1B26" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#C0C9F4" :background "#1A1B26" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#FF9E64"))))
 '(font-lock-type-face ((t (:foreground "#2AC2DD"))))
 '(font-lock-preprocessor-face ((t (:foreground "#C0C9F4"))))
 '(font-lock-operator-face ((t (:foreground "#89DCFF"))))
 '(font-lock-string-face ((t (:foreground "#9ECD6A"))))
 '(font-lock-variable-name-face ((t (:foreground "#C0C9F4"))))
 '(font-lock-constant-face ((t (:foreground "#9ECD6A"))))
 '(font-lock-keyword-face ((t (:foreground "#BB9AF6"))))
 '(font-lock-warning-face ((t (:foreground "#DFAF68"))))
 '(font-lock-function-name-face ((t (:foreground "#7AA2F6"))))
 '(font-lock-negation-char-face ((t (:foreground "#89DCFF"))))
 '(font-lock-variable-use-face ((t (:foreground "#C0C9F4"))))
 '(font-lock-property-use-face ((t (:foreground "#C0C9F4"))))
 '(font-lock-number-face ((t (:foreground "#FF9E64"))))
 '(font-lock-bracket-face ((t (:foreground "#2AC2DD"))))
 '(font-lock-delimiter-face ((t (:foreground "#737AA2"))))
 '(font-lock-escape-face ((t (:foreground "#BB9AF6"))))
 '(show-paren-match ((t (:foreground "#C0C9F4"))))
 '(show-paren-mismatch-face ((t (:foreground "#DA4B4B" :background "#1A1B26"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#545C7E" :background "#1A1B26" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#9ECD6A"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#7AA2F6"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#2AC2DD"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#9ECD6A"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#C0C9F4"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#73D9C9"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#9ECD6A" :background "#292E42" :overline "#545C7E"))))
 '(org-level-2 ((t (:foreground "#2AC2DD" :background "#292E42" :overline "#545C7E"))))
 '(org-level-3 ((t (:foreground "#2AC2DD" :background "#292E42" :overline "#545C7E"))))
 '(org-level-4 ((t (:foreground "#27A1B9" :background "#292E42" :overline "#545C7E"))))
 '(org-level-5 ((t (:foreground "#27A1B9" :background "#292E42" :overline "#545C7E"))))
 '(org-level-6 ((t (:foreground "#27A1B9" :background "#292E42" :overline "#545C7E"))))
 '(org-level-7 ((t (:foreground "#27A1B9" :background "#292E42" :overline "#545C7E"))))
 '(org-tag ((t (:foreground "#C0C9F4"))))
 '(org-headline-done ((t (:foreground "#BB9AF6" :background "#1A1B26"))))
 '(org-done ((t (:foreground "#C0C9F4"))))
 '(org-todo ((t (:foreground "#DFAF68"))))
 '(org-checkbox ((t (:foreground "#FF9E64" :background "#414868"))))
 '(org-link ((t (:foreground "#1ABC9C" :background "#1A1B26" :underline nil))))
 '(org-verbatim ((t (:foreground "#BB9AF6"))))
 '(org-code ((t (:foreground "#BB9AF6"))))
 '(org-table ((t (:foreground "#BB9AF6" :background "#1A1B26"))))
 '(org-date ((t (:foreground "#2AC2DD" :underline t))))
 '(org-archived ((t (:foreground "#545C7E" :background "#1A1B26"))))
 '(org-list-dt ((t (:foreground "#FF9E64"))))
 '(org-drawer ((t (:foreground "#C0C9F4"))))
 '(org-special-keyword ((t (:foreground "#737AA2"))))
 '(org-property-value ((t (:foreground "#C0C9F4" :background "#1A1B26"))))
 '(org-block ((t (:background "#292E42" :extend t))))
 '(org-block-begin-line ((t (:foreground "#545C7E" :background "#1A1B26" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#737AA2"))))
 '(org-superstar-header-bullet ((t (:foreground "#FF9E64" :background "#1A1B26" :overline t))))
 '(org-superstar-item ((t (:foreground "#DFAF68"))))
 '(org-superstar-ordered-item ((t (:foreground "#73D9C9"))))
 '(org-hide ((t (:foreground "#1A1B26"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#BB9AF6" :height 220 :underline "#9ECD6A"))))
 '(markdown-header-face-2 ((t (:foreground "#BB9AF6" :height 180 :underline "#9ECD6A"))))
 '(markdown-header-face-3 ((t (:foreground "#BB9AF6" :underline "#C0C9F4"))))
 '(markdown-header-face-4 ((t (:foreground "#BB9AF6"))))
 '(markdown-header-face-5 ((t (:foreground "#BB9AF6"))))
 '(markdown-header-face-6 ((t (:foreground "#BB9AF6"))))
 '(markdown-list-face ((t (:foreground "#DFAF68"))))
 '(markdown-inline-code-face ((t (:foreground "#BB9AF6" :background "#1A1B26"))))
 '(markdown-language-keyword-face ((t (:foreground "#C0C9F4"))))
 '(markdown-pre-face ((t (:foreground "#BB9AF6"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#545C7E"))))
 '(markdown-header-delimiter-face ((t (:foreground "#89DCFF"))))
 '(markdown-bold-face ((t (:foreground "#BB9AF6" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#BB9AF6" :slant italic))))
 '(markdown-link-face ((t (:foreground "#BB9AF6"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#9ECD6A"))))
 '(compilation-warning ((t (:foreground "#9ECD6A"))))
 '(compilation-error ((t (:foreground "#DA4B4B"))))
 '(compilation-line-number ((t (:foreground "#BB9AF6" :underline t))))
 '(compilation-column-number ((t (:foreground "#BB9AF6" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#DA4B4B"))))
 '(flycheck-fringe-warning ((t (:foreground "#9ECD6A"))))
 '(flycheck-fringe-info ((t (:foreground "#9ECD6A"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#1A1B26"))))
 '(lsp-face-highlight-textual ((t (:background "#283457"))))
 '(lsp-face-highlight-write ((t (:background "#283457"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#283457"))))
 '(eglot-inlay-hint-face ((t (:foreground "#BB9AF6" :background "#1A1B26" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#BB9AF6"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#C0C9F4" :background "#1A1B26"))))
 '(company-preview-common ((t (:foreground "#BB9AF6" :background "#1A1B26"))))
 '(company-preview-search ((t (:foreground "#BB9AF6" :background "#1A1B26"))))
 '(company-tooltip-common ((t (:foreground "#BB9AF6" :background "#1A1B26"))))
 '(company-tooltip-common-selection ((t (:foreground "#BB9AF6" :background "#1A1B26"))))
 '(company-tooltip-annotation ((t (:foreground "#BB9AF6" :background "#1A1B26"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#BB9AF6" :background "#1A1B26"))))
 '(company-tooltip-search-selection ((t (:foreground "#BB9AF6" :background "#283457"))))
 '(company-tooltip-mouse ((t (:foreground "#BB9AF6" :background "#283457"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#C0C9F4" :background "#1A1B26"))))
 '(magit-branch-current ((t (:foreground "#9ECD6A" :box 1))))
 '(magit-branch-remote ((t (:foreground "#9ECD6A" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#BB9AF6"))))
 '(rg-line-number-face ((t (:foreground "#BB9AF6"))))

 ;; line numbers
 '(line-number ((t (:foreground "#545C7E" :background "#1A1B26"))))
 '(line-number-current-line ((t (:foreground "#545C7E" :background "#1A1B26"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#545C7E"))))
 '(doom-modeline-bar ((t (:background "#1A1B26"))))
 '(doom-modeline-bar-inactive ((t (:background "#1A1B26"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#73D9C9" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#BB9AF6"))))
 '(doom-modeline-project-dir ((t (:foreground "#C0C9F4"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#C0C9F4"))))
 '(doom-modeline-urgent ((t (:foreground "#BB9AF6"))))
 '(doom-modeline-info ((t (:foreground "#C0C9F4"))))
 '(doom-modeline-warning ((t (:foreground "#BB9AF6"))))
 '(doom-modeline-error ((t (:foreground "#DA4B4B"))))
 '(doom-modeline-inactive-bar ((t (:background "#1A1B26"))))
 '(mode-line ((t (:foreground "#16161E" :background "#1A1B26"))))
 '(mode-line-inactive ((t (:background "#1A1B26"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#16161E"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#16161E"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#737AA2" :background "#1A1B26"))))
 '(tab-bar-tab ((t (:foreground "#2AC2DD" :background "#1A1B26" :box (:line-width 2 :color "#1A1B26")))))
 '(tab-bar-tab-inactive ((t (:foreground "#737AA2" :background "#1A1B26"))))

 ;; misc
 '(secondary-selection ((t (:background "#292E42"))))
 '(shadow ((t (:foreground "#545C7E")))))

(provide-theme 'tokyo-night)
