
;;; vanta-black-theme.el --- Generated by Book of Colours

(deftheme vanta-black "vanta-black")

(custom-theme-set-faces
 'vanta-black

 ;; common
 '(default ((t (:foreground "#FFFFFF" :background "#000000"))))
 '(cursor ((t (:foreground "#0D0D0D" :background "#FFFFFF"))))
 '(region ((t (:foreground "#FFFFFF" :background "#000000"))))
 '(hl-line ((t (:background "#2A2A2A"))))
 '(minibuffer-prompt ((t (:foreground "#A0A0A0"))))
 '(link ((t (:foreground "#DFDFDF" :underline t))))
 '(warning ((t (:foreground "#DFDFDF"))))
 '(error ((t (:foreground "#DFDFDF"))))
 '(success ((t (:foreground "#DFDFDF"))))
 '(bold ((t (:foreground "#B8B8B8" :weight bold))))
 '(isearch ((t (:foreground "#FFFFFF" :background "#000000"))))
 '(lazy-highlight ((t (:foreground "#DFDFDF" :background "#000000"))))
 '(query-replace ((t (:inherit isearch))))
 '(match ((t (:foreground "#DFDFDF" :background "#000000" :weight bold))))
 '(tooltip ((t (:foreground "#B8B8B8" :background "#343434" :weight bold))))
 '(fringe ((t (:background "#000000"))))
 '(vertical-border ((t (:foreground "#2A2A2A"))))
 '(escape-glyph ((t (:inherit default))))
 '(nobreak-hyphen ((t (:foreground "#FFFFFF"))))
 '(header-line ((t (:foreground "#A0A0A0" :background "#000000"))))
 '(header-line-highlight ((t (:foreground "#B8B8B8" :background "#000000"))))
 '(highlight ((t (:foreground "#DFDFDF" :background "#000000"))))
 '(button ((t (:foreground "#DFDFDF" :underline t))))

 ;; code (font-lock)
 '(font-lock-comment-face ((t (:foreground "#A0A0A0" :background "#343434" :extend t))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#FFFFFF" :background "#343434" :extend t))))
 '(font-lock-builtin-face ((t (:foreground "#DFDFDF"))))
 '(font-lock-type-face ((t (:foreground "#DFDFDF"))))
 '(font-lock-preprocessor-face ((t (:foreground "#DFDFDF"))))
 '(font-lock-operator-face ((t (:foreground "#888888"))))
 '(font-lock-string-face ((t (:foreground "#838383"))))
 '(font-lock-variable-name-face ((t (:foreground "#C7C7C7"))))
 '(font-lock-constant-face ((t (:foreground "#DFDFDF"))))
 '(font-lock-keyword-face ((t (:foreground "#DFDFDF"))))
 '(font-lock-warning-face ((t (:foreground "#DFDFDF"))))
 '(font-lock-function-name-face ((t (:foreground "#DFDFDF"))))
 '(font-lock-negation-char-face ((t (:foreground "#888888"))))
 '(font-lock-variable-use-face ((t (:foreground "#FFFFFF"))))
 '(font-lock-property-use-face ((t (:foreground "#FFFFFF"))))
 '(font-lock-number-face ((t (:foreground "#DFDFDF"))))
 '(font-lock-bracket-face ((t (:foreground "#DFDFDF"))))
 '(font-lock-delimiter-face ((t (:foreground "#7A7A7A"))))
 '(font-lock-escape-face ((t (:foreground "#B8B8B8"))))
 '(show-paren-match ((t (:foreground "#DFDFDF"))))
 '(show-paren-mismatch-face ((t (:foreground "#DFDFDF" :background "#000000"))))

 ;; tree-sitter
 '(tree-sitter-hl-face:comment ((t (:foreground "#A0A0A0" :background "#343434" :extend t))))
 '(tree-sitter-hl-face:string ((t (:foreground "#838383"))))
 '(tree-sitter-hl-face:function.call ((t (:foreground "#DFDFDF"))))
 '(tree-sitter-hl-face:type.builtin ((t (:foreground "#DFDFDF"))))
 '(tree-sitter-hl-face:constant ((t (:foreground "#DFDFDF"))))
 '(tree-sitter-hl-face:property ((t (:foreground "#FFFFFF"))))
 '(tree-sitter-hl-face:variable.special ((t (:foreground "#C7C7C7"))))

 ;; org-mode
 '(org-level-1 ((t (:foreground "#B8B8B8" :background "#2A2A2A" :overline "#A0A0A0"))))
 '(org-level-2 ((t (:foreground "#DFDFDF" :background "#2A2A2A" :overline "#A0A0A0"))))
 '(org-level-3 ((t (:foreground "#DFDFDF" :background "#2A2A2A" :overline "#A0A0A0"))))
 '(org-level-4 ((t (:foreground "#B8B8B8" :background "#2A2A2A" :overline "#A0A0A0"))))
 '(org-level-5 ((t (:foreground "#B8B8B8" :background "#2A2A2A" :overline "#A0A0A0"))))
 '(org-level-6 ((t (:foreground "#B8B8B8" :background "#2A2A2A" :overline "#A0A0A0"))))
 '(org-level-7 ((t (:foreground "#B8B8B8" :background "#2A2A2A" :overline "#A0A0A0"))))
 '(org-tag ((t (:foreground "#C7C7C7"))))
 '(org-headline-done ((t (:foreground "#DFDFDF" :background "#343434"))))
 '(org-done ((t (:foreground "#FFFFFF"))))
 '(org-todo ((t (:foreground "#DFDFDF"))))
 '(org-checkbox ((t (:foreground "#DFDFDF" :background "#2A2A2A"))))
 '(org-link ((t (:foreground "#DFDFDF" :background "#000000" :underline nil))))
 '(org-verbatim ((t (:foreground "#B8B8B8"))))
 '(org-code ((t (:foreground "#B8B8B8"))))
 '(org-table ((t (:foreground "#B8B8B8" :background "#000000"))))
 '(org-date ((t (:foreground "#DFDFDF" :underline t))))
 '(org-archived ((t (:foreground "#A0A0A0" :background "#343434"))))
 '(org-list-dt ((t (:foreground "#DFDFDF"))))
 '(org-drawer ((t (:foreground "#DFDFDF"))))
 '(org-special-keyword ((t (:foreground "#909090"))))
 '(org-property-value ((t (:foreground "#FFFFFF" :background "#000000"))))
 '(org-block ((t (:background "#2A2A2A" :extend t))))
 '(org-block-begin-line ((t (:foreground "#A0A0A0" :background "#000000" :extend t))))
 '(org-block-end-line ((t (:inherit org-block-begin-line))))
 '(org-meta-line ((t (:foreground "#7A7A7A"))))
 '(org-superstar-header-bullet ((t (:foreground "#DFDFDF" :background "#000000" :overline t))))
 '(org-superstar-item ((t (:foreground "#DFDFDF"))))
 '(org-superstar-ordered-item ((t (:foreground "#C7C7C7"))))
 '(org-hide ((t (:foreground "#000000"))))

 ;; markdown-mode
 '(markdown-header-face-1 ((t (:foreground "#B8B8B8" :height 220 :underline "#B8B8B8"))))
 '(markdown-header-face-2 ((t (:foreground "#B8B8B8" :height 180 :underline "#B8B8B8"))))
 '(markdown-header-face-3 ((t (:foreground "#B8B8B8" :underline "#FFFFFF"))))
 '(markdown-header-face-4 ((t (:foreground "#B8B8B8"))))
 '(markdown-header-face-5 ((t (:foreground "#B8B8B8"))))
 '(markdown-header-face-6 ((t (:foreground "#B8B8B8"))))
 '(markdown-list-face ((t (:foreground "#DFDFDF"))))
 '(markdown-inline-code-face ((t (:foreground "#B8B8B8" :background "#343434"))))
 '(markdown-language-keyword-face ((t (:foreground "#C7C7C7"))))
 '(markdown-pre-face ((t (:foreground "#B8B8B8"))))
 '(markdown-code-face ((t nil)))
 '(markdown-markup-face ((t (:foreground "#A0A0A0"))))
 '(markdown-header-delimiter-face ((t (:foreground "#DFDFDF"))))
 '(markdown-bold-face ((t (:foreground "#B8B8B8" :weight bold))))
 '(markdown-italic-face ((t (:foreground "#B8B8B8" :slant italic))))
 '(markdown-link-face ((t (:foreground "#B8B8B8"))))

 ;; compile-mode
 '(compilation-info ((t (:foreground "#B8B8B8"))))
 '(compilation-warning ((t (:foreground "#B8B8B8"))))
 '(compilation-error ((t (:foreground "#DFDFDF"))))
 '(compilation-line-number ((t (:foreground "#B8B8B8" :underline t))))
 '(compilation-column-number ((t (:foreground "#B8B8B8" :underline t))))

 ;; flycheck
 '(flycheck-fringe-error ((t (:foreground "#DFDFDF"))))
 '(flycheck-fringe-warning ((t (:foreground "#B8B8B8"))))
 '(flycheck-fringe-info ((t (:foreground "#B8B8B8"))))

 ;; lsp
 '(lsp-face-highlight-read ((t (:background "#000000"))))
 '(lsp-face-highlight-textual ((t (:background "#000000"))))
 '(lsp-face-highlight-write ((t (:background "#000000"))))

 ;; eglot
 '(eglot-highlight-symbol-face ((t (:background "#000000"))))
 '(eglot-inlay-hint-face ((t (:foreground "#B8B8B8" :background "#343434" :height 84))))

 ;; xref
 '(xref-line-number ((t (:foreground "#B8B8B8"))))

 ;; company-mode
 '(company-preview ((t (:foreground "#FFFFFF" :background "#000000"))))
 '(company-preview-common ((t (:foreground "#B8B8B8" :background "#000000"))))
 '(company-preview-search ((t (:foreground "#B8B8B8" :background "#000000"))))
 '(company-tooltip-common ((t (:foreground "#B8B8B8" :background "#000000"))))
 '(company-tooltip-common-selection ((t (:foreground "#B8B8B8" :background "#000000"))))
 '(company-tooltip-annotation ((t (:foreground "#B8B8B8" :background "#000000"))))
 '(company-tooltip-annotation-selection ((t (:foreground "#B8B8B8" :background "#000000"))))
 '(company-tooltip-search-selection ((t (:foreground "#B8B8B8" :background "#000000"))))
 '(company-tooltip-mouse ((t (:foreground "#B8B8B8" :background "#000000"))))

 ;; magit
 '(magit-section-highlight ((t (:foreground "#FFFFFF" :background "#343434"))))
 '(magit-branch-current ((t (:foreground "#B8B8B8" :box 1))))
 '(magit-branch-remote ((t (:foreground "#B8B8B8" :box 1))))

 ;; ripgrep
 '(rg-match-face ((t (:foreground "#DFDFDF"))))
 '(rg-line-number-face ((t (:foreground "#B8B8B8"))))

 ;; line numbers
 '(line-number ((t (:foreground "#A0A0A0" :background "#000000"))))
 '(line-number-current-line ((t (:foreground "#A0A0A0" :background "#000000"))))

 ;; modeline (doom + standard)
 '(doom-modeline ((t (:foreground "#373737"))))
 '(doom-modeline-bar ((t (:background "#000000"))))
 '(doom-modeline-bar-inactive ((t (:background "#000000"))))
 '(doom-modeline-buffer-modified ((t (:foreground "#C7C7C7" :weight bold))))
 '(doom-modeline-buffer-file ((t (:foreground "#DFDFDF"))))
 '(doom-modeline-project-dir ((t (:foreground "#FFFFFF"))))
 '(doom-modeline-buffer-major-mode ((t (:foreground "#FFFFFF"))))
 '(doom-modeline-urgent ((t (:foreground "#DFDFDF"))))
 '(doom-modeline-info ((t (:foreground "#FFFFFF"))))
 '(doom-modeline-warning ((t (:foreground "#DFDFDF"))))
 '(doom-modeline-error ((t (:foreground "#DFDFDF"))))
 '(doom-modeline-inactive-bar ((t (:background "#000000"))))
 '(mode-line ((t (:foreground "#1C1C1C" :background "#000000"))))
 '(mode-line-inactive ((t (:background "#000000"))))

 ;; highlight indent guides
 '(highlight-indent-guides-character-face ((t (:foreground "#1C1C1C"))))
 '(highlight-indent-guides-top-character-face ((t (:foreground "#1C1C1C"))))

 ;; tab bar
 '(tab-bar ((t (:foreground "#909090" :background "#000000"))))
 '(tab-bar-tab ((t (:foreground "#DFDFDF" :background "#000000" :box (:line-width 2 :color "#000000")))))
 '(tab-bar-tab-inactive ((t (:foreground "#7A7A7A" :background "#000000"))))

 ;; misc
 '(secondary-selection ((t (:background "#2A2A2A"))))
 '(shadow ((t (:foreground "#7A7A7A")))))

(provide-theme 'vanta-black)
